import {
  MATERIAL,
  barrelJack,
  capacitor,
  chip,
  dip,
  header,
  maleHeader,
  microUsb,
  mountHole,
  pcb,
  shieldCan,
  silk,
  smdLed,
  tactileButton,
  usbA,
  usbB,
  usbC,
} from "../build";
import type { PartModel, PinInfo, Solid } from "../types";

const DIGITAL_PINS = ["0 (RX)", "1 (TX)", "2", "~3", "4", "~5", "~6", "7", "8", "~9", "~10", "~11", "12", "13"];

/** The zig-zag PCB antenna printed on Wi-Fi modules. */
function pcbAntenna(x: number, y: number, w: number, h: number): Solid {
  const step = w / 8;
  let d = `M ${x} ${y + h}`;
  for (let i = 0; i < 8; i++) {
    const px = x + i * step;
    d += i % 2 === 0 ? ` L ${px} ${y} L ${px + step} ${y}` : ` L ${px} ${y + h} L ${px + step} ${y + h}`;
  }
  return { kind: "path", d, color: MATERIAL.gold, width: 0.5 };
}

const UNO_PINS: PinInfo[] = [
  ...DIGITAL_PINS.map((name) => ({ name: `D${name}`, role: name.startsWith("~") ? "pwm" : "digital", note: name.startsWith("~") ? "Digital, with PWM output" : "Digital input/output" }) as PinInfo),
  { name: "A0–A5", role: "analog", note: "10-bit analog inputs; A4 is SDA and A5 is SCL for I2C" },
  { name: "5V", role: "power", note: "5 V output from the regulator or USB, up to about 500 mA" },
  { name: "3.3V", role: "power", note: "3.3 V output, 50 mA max" },
  { name: "GND", role: "ground", note: "Three ground pins; all connected" },
  { name: "VIN", role: "power", note: "Unregulated input, 7–12 V" },
  { name: "RESET", role: "other", note: "Pull low to reset" },
  { name: "AREF", role: "other", note: "External reference for the analog inputs" },
];

export const BOARDS: PartModel[] = [
  {
    id: "arduino-uno",
    name: "Arduino Uno",
    aka: ["Uno R3", "ATmega328P board"],
    group: "boards",
    rank: 1,
    summary: "The board most people start on: 14 digital pins, 6 analog inputs, 5 V logic, USB-B programming, and forgiving of mistakes.",
    size: { w: 68.6, h: 53.4, d: 12.6 },
    solids: [
      pcb(68.6, 53.4, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      usbB(-6, 5.5),
      barrelJack(-3, 39),
      header(18.5, 1.6, 10, "x"),
      header(44.6, 1.6, 8, "x"),
      header(24, 49.3, 8, "x"),
      header(46.5, 49.3, 6, "x"),
      header(62, 21, 3, "y", 2),
      ...dip(30, 34, 14, "ATMEGA328P"),
      chip(14.5, 17.5, 4.4, 4.4, undefined, 0.9),
      { kind: "cyl", cx: 21, cy: 37, r: 1.6, d: 2.5, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, segments: 12 },
      ...tactileButton(12.5, 6, 4.5),
      capacitor(20.5, 30.5, 1.6, 4, 1.6),
      capacitor(24.5, 30.5, 1.6, 4, 1.6),
      { kind: "box", x: 13.5, y: 40, w: 5, h: 7, d: 2, z: 1.6, top: "linear-gradient(90deg,#b9bdc3 0 30%,#1b1c1f 30%)", side: MATERIAL.icSide, fill: MATERIAL.ic },
      smdLed(30, 8.6, "#ffb020", "led-l"),
      smdLed(30, 11.6, "#ffb020", "led-tx"),
      smdLed(30, 14.6, "#ffb020", "led-rx"),
      smdLed(36, 22, "#3ddc84", "led-on"),
      mountHole(2.5, 25),
      mountHole(66, 11),
      mountHole(66, 49),
      silk(37.5, 25.5, "HHIP", 5.5, MATERIAL.silk, { weight: 800 }),
      silk(37.5, 29, "UNO-LAYOUT  5V", 1.4),
      silk(25, 13.5, "DIGITAL (PWM~)", 1.3),
      silk(24, 48.4, "POWER", 1.3),
      silk(50, 48.4, "ANALOG IN", 1.3),
      silk(33.5, 9, "L", 1.2),
      silk(33.5, 12, "TX", 1.2),
      silk(33.5, 15, "RX", 1.2),
      silk(39.5, 22.6, "ON", 1.2),
      silk(62, 19.8, "ICSP", 1.1),
      silk(12, 12.5, "RESET", 1.1),
    ],
    features: [
      { id: "digital", label: "Digital pins 0–13", kind: "pins", x: 18.5, y: 1.6, w: 46.4, h: 2.54, note: "14 digital inputs and outputs at 5 V. Pins marked ~ can output PWM. 0 and 1 are also the serial port, so leave them free while uploading." },
      { id: "analog", label: "Analog inputs A0–A5", kind: "pins", x: 46.5, y: 49.3, w: 15.2, h: 2.54, note: "Six 10-bit analog inputs, 0–5 V. They can also be used as digital pins." },
      { id: "power", label: "Power pins", kind: "power", x: 24, y: 49.3, w: 20.3, h: 2.54, note: "5 V and 3.3 V out, two GND, VIN in (7–12 V) and RESET." },
      { id: "usb", label: "USB-B port", kind: "port", x: -6, y: 5.5, w: 16, h: 12, note: "Programming and serial over USB; also powers the board at 5 V." },
      { id: "jack", label: "Barrel jack", kind: "port", x: -3, y: 39, w: 14, h: 9, note: "7–12 V DC in. The onboard regulator makes 5 V from it." },
      { id: "mcu", label: "ATmega328P", kind: "chip", x: 30, y: 34, w: 35.6, h: 7.6, note: "The microcontroller: 16 MHz, 32 KB flash, 2 KB RAM. Socketed, so it can be replaced." },
      { id: "led-l", label: "L LED (pin 13)", kind: "led", x: 29.5, y: 8, w: 2.6, h: 1.8, note: "Wired to digital pin 13. Blink makes this one flash." },
      { id: "led-on", label: "Power LED", kind: "led", x: 35.5, y: 21.4, w: 2.6, h: 1.8, note: "Lit whenever the board has 5 V." },
      { id: "reset", label: "Reset button", kind: "button", x: 12.5, y: 6, w: 4.5, h: 4.5, note: "Restarts the sketch from the top." },
      { id: "icsp", label: "ICSP header", kind: "pins", x: 62, y: 21, w: 5.1, h: 7.6, note: "In-circuit programming of the ATmega328P with an external programmer." },
    ],
    pins: UNO_PINS,
    circuit: {
      blocks: [
        { id: "usb", label: "USB-B", sub: "5 V in, serial", kind: "connector", col: 0, row: 0, note: "The computer supplies 5 V and talks serial through the USB bridge." },
        { id: "jack", label: "Barrel jack", sub: "7–12 V in", kind: "connector", col: 0, row: 2, note: "An external supply when USB is not plugged in." },
        { id: "bridge", label: "USB bridge", sub: "ATmega16U2", kind: "ic", col: 1, row: 0, note: "Turns USB into the serial signals the main chip understands." },
        { id: "reg", label: "5 V regulator", sub: "NCP1117", kind: "regulator", col: 1, row: 2, note: "Drops VIN to a steady 5 V. A second regulator makes 3.3 V." },
        { id: "mcu", label: "ATmega328P", sub: "16 MHz", kind: "mcu", col: 2, row: 1, note: "Runs your sketch. Every pin on the headers is one of its pins." },
        { id: "digital", label: "Digital pins", sub: "D0–D13", kind: "pin", col: 3, row: 0, note: "Switch between 0 V and 5 V, source up to 20 mA each." },
        { id: "analog", label: "Analog inputs", sub: "A0–A5", kind: "pin", col: 3, row: 1, note: "Read 0–5 V as 0–1023." },
        { id: "power", label: "Power pins", sub: "5V, 3.3V, GND", kind: "power", col: 3, row: 2, note: "Feed your sensors and modules." },
      ],
      links: [
        { from: "usb", to: "bridge", kind: "data", label: "USB" },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "jack", to: "reg", kind: "power", label: "VIN" },
        { from: "bridge", to: "mcu", kind: "data", label: "TX/RX", both: true },
        { from: "reg", to: "mcu", kind: "power", label: "5 V" },
        { from: "reg", to: "power", kind: "power" },
        { from: "mcu", to: "digital", kind: "signal", both: true },
        { from: "analog", to: "mcu", kind: "analog" },
      ],
      steps: [
        "Power arrives from USB (5 V) or the barrel jack (7–12 V); the regulator settles it at 5 V for the whole board.",
        "The USB bridge chip converts the computer's USB traffic into serial for the ATmega328P, which is how sketches are uploaded.",
        "The ATmega328P runs your sketch at 16 MHz and drives the header pins directly: digital pins switch between 0 and 5 V, analog pins read voltages.",
        "The power pins pass the regulated 5 V and 3.3 V to your sensors and modules; all GND pins join the same ground.",
      ],
    },
    facts: [
      { label: "Logic", value: "5 V" },
      { label: "Clock", value: "16 MHz" },
      { label: "Memory", value: "32 KB flash, 2 KB RAM" },
      { label: "Pins", value: "14 digital (6 PWM), 6 analog" },
      { label: "Input", value: "USB 5 V or 7–12 V DC" },
      { label: "Size", value: "68.6 × 53.4 mm" },
    ],
    animate: { lit: ["led-on", "led-l"] },
    experiment: { title: "Blink", idea: "Flash the pin-13 LED once a second, then change the timing and watch the serial monitor count the blinks." },
    docs: "/docs/hardware-knowledge/arduino-uno",
    tags: ["arduino", "uno", "atmega328p", "5v", "beginner", "mcu", "board"],
  },

  {
    id: "esp32",
    name: "ESP32 DevKit",
    aka: ["ESP32 DevKit V1", "DOIT ESP32", "ESP-WROOM-32 board"],
    group: "boards",
    rank: 2,
    summary: "A fast dual-core board with Wi-Fi and Bluetooth built in, 3.3 V logic, and enough pins for a whole IoT project. The usual choice when a project needs the internet.",
    size: { w: 55, h: 28, d: 10 },
    solids: [
      pcb(55, 28, MATERIAL.pcbBlack, MATERIAL.pcbBlackEdge),
      ...maleHeader(0.5, 1, 15, "x"),
      ...maleHeader(0.5, 24.5, 15, "x"),
      shieldCan(31, 4.5, 18, 19, "ESP-WROOM-32"),
      pcbAntenna(50.5, 7, 4, 14),
      microUsb(-1.5, 11.2),
      ...tactileButton(8, 4.2, 4, "btn-en"),
      ...tactileButton(8, 19.8, 4, "btn-boot"),
      chip(16, 10.5, 5, 5, "CP2102", 0.9),
      { kind: "box", x: 22.5, y: 5, w: 6.5, h: 6.5, d: 1.2, z: 1.6, top: "#1b1c1f", side: MATERIAL.icSide, label: { text: "1117", size: 1.3, color: "#a3a7ad" } },
      smdLed(16, 20, "#ef4444", "led-pwr"),
      smdLed(23, 20, "#3b82f6", "led-io2"),
      silk(8, 9.6, "EN", 1.2),
      silk(7, 25.2, "BOOT", 1.1),
      silk(14, 23.2, "PWR", 1.0),
      silk(21, 23.2, "IO2", 1.0),
      silk(31, 26.2, "DOIT ESP32 DEVKIT V1", 1.1),
    ],
    features: [
      { id: "module", label: "ESP-WROOM-32 module", kind: "chip", x: 31, y: 4.5, w: 18, h: 19, note: "The radio module: a dual-core ESP32 at 240 MHz, 4 MB flash, Wi-Fi and Bluetooth, under a metal shield." },
      { id: "antenna", label: "PCB antenna", kind: "antenna", x: 50, y: 6, w: 5, h: 16, note: "The printed Wi-Fi and Bluetooth antenna. Keep metal and fingers away from it for the best range." },
      { id: "usb", label: "Micro-USB", kind: "port", x: -1.5, y: 11.2, w: 7.5, h: 5.5, note: "Programming, serial monitor and 5 V power." },
      { id: "top-pins", label: "Pins, top row", kind: "pins", x: 0.5, y: 1, w: 38.1, h: 2.54, note: "15 pins: EN, sensor inputs, analog pins 32–39 and GPIO. Everything is 3.3 V; 5 V on a GPIO will damage it." },
      { id: "bottom-pins", label: "Pins, bottom row", kind: "pins", x: 0.5, y: 24.5, w: 38.1, h: 2.54, note: "15 pins including GND, VIN (5 V in), GPIO 23 to 1, TX0 and RX0." },
      { id: "en", label: "EN button", kind: "button", x: 8, y: 4.2, w: 4, h: 4, note: "Reset. Hold BOOT while pressing it to enter the bootloader by hand." },
      { id: "boot", label: "BOOT button", kind: "button", x: 8, y: 19.8, w: 4, h: 4, note: "Hold during an upload if the board refuses to connect." },
      { id: "bridge", label: "CP2102 USB bridge", kind: "chip", x: 16, y: 10.5, w: 5, h: 5, note: "Makes USB look like a serial port to the ESP32." },
      { id: "led-pwr", label: "Power LED", kind: "led", x: 15.5, y: 19.4, w: 2.6, h: 1.8, note: "Red; lit whenever the board has power." },
      { id: "led-io2", label: "GPIO2 LED", kind: "led", x: 22.5, y: 19.4, w: 2.6, h: 1.8, note: "Blue; the built-in LED, on GPIO 2." },
    ],
    pins: [
      { name: "VIN", role: "power", note: "5 V in from USB or a supply; feeds the 3.3 V regulator" },
      { name: "3V3", role: "power", note: "3.3 V out, around 500 mA shared with the radio" },
      { name: "GND", role: "ground", note: "Two ground pins" },
      { name: "EN", role: "other", note: "Pull low to reset" },
      { name: "GPIO 0–39", role: "digital", note: "Up to 25 usable GPIO at 3.3 V; 34–39 are input only" },
      { name: "GPIO 32–39", role: "analog", note: "12-bit ADC inputs (ADC1); ADC2 pins stop working while Wi-Fi is on" },
      { name: "GPIO 2", role: "digital", note: "Built-in blue LED; keep low at boot" },
      { name: "TX0 / RX0", role: "uart", note: "Serial port shared with USB programming" },
      { name: "GPIO 21 / 22", role: "i2c", note: "Default SDA and SCL" },
      { name: "GPIO 18 / 19 / 23 / 5", role: "spi", note: "Default SCK, MISO, MOSI, CS (VSPI)" },
      { name: "GPIO 25 / 26", role: "analog", note: "Also 8-bit DAC outputs" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "5 V in, serial", kind: "connector", col: 0, row: 0, note: "Power and programming from the computer." },
        { id: "bridge", label: "USB bridge", sub: "CP2102", kind: "ic", col: 1, row: 0, note: "USB to serial, plus the auto-reset trick that puts the chip into bootloader mode for uploads." },
        { id: "reg", label: "3.3 V regulator", sub: "AMS1117", kind: "regulator", col: 1, row: 2, note: "Drops 5 V to the 3.3 V everything on the board runs at. Wi-Fi bursts draw up to 500 mA." },
        { id: "esp", label: "ESP32", sub: "2 cores, 240 MHz", kind: "mcu", col: 2, row: 1, note: "Runs your code on one core while the other handles Wi-Fi and Bluetooth." },
        { id: "flash", label: "Flash", sub: "4 MB", kind: "ic", col: 2, row: 2, note: "Your program and files live here, inside the module." },
        { id: "antenna", label: "Antenna", sub: "2.4 GHz", kind: "antenna", col: 3, row: 0, note: "Printed on the board; shared by Wi-Fi and Bluetooth." },
        { id: "gpio", label: "GPIO pins", sub: "3.3 V logic", kind: "pin", col: 3, row: 1, note: "Digital, PWM, I2C, SPI and UART, chosen in software." },
        { id: "adc", label: "Analog inputs", sub: "12-bit", kind: "pin", col: 3, row: 2, note: "0–3.3 V read as 0–4095." },
      ],
      links: [
        { from: "usb", to: "bridge", kind: "data", label: "USB" },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "bridge", to: "esp", kind: "data", label: "serial", both: true },
        { from: "reg", to: "esp", kind: "power", label: "3.3 V" },
        { from: "esp", to: "flash", kind: "data", both: true },
        { from: "esp", to: "antenna", kind: "rf", both: true },
        { from: "esp", to: "gpio", kind: "signal", both: true },
        { from: "adc", to: "esp", kind: "analog" },
      ],
      steps: [
        "5 V from USB (or VIN) goes through the AMS1117 regulator, which supplies 3.3 V to the module and the 3V3 pin.",
        "The CP2102 bridge turns USB into serial and can pull EN and GPIO0 to reset the chip into its bootloader for uploads.",
        "The ESP32 runs your sketch from the 4 MB flash, with the radio stack on its second core.",
        "GPIO pins work at 3.3 V; the analog pins on ADC1 (32–39) keep working while Wi-Fi is active, the others do not.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V" },
      { label: "Clock", value: "240 MHz, 2 cores" },
      { label: "Radio", value: "Wi-Fi, Bluetooth 4.2 + BLE" },
      { label: "Memory", value: "4 MB flash, 520 KB RAM" },
      { label: "Pins", value: "30, of which about 25 GPIO" },
      { label: "Size", value: "55 × 28 mm" },
    ],
    animate: { lit: ["led-pwr", "led-io2"] },
    experiment: { title: "Blink over Wi-Fi", idea: "Join a Wi-Fi network, print the IP address, then flash the GPIO2 LED when the board is pinged." },
    docs: "/docs/hardware-knowledge/esp32-devkit",
    tags: ["esp32", "wifi", "bluetooth", "iot", "3.3v", "espressif", "board", "mcu"],
  },

  {
    id: "raspberry-pi-pico",
    name: "Raspberry Pi Pico",
    aka: ["Pico", "RP2040 board"],
    group: "boards",
    rank: 3,
    summary: "A small, cheap RP2040 board with two cores, 26 GPIO and programmable I/O that can bit-bang almost any protocol. Programs in C or MicroPython, and shows up as a USB drive to flash.",
    size: { w: 51, h: 21, d: 6.6 },
    solids: [
      pcb(51, 21, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      ...Array.from({ length: 20 }, (_, i) => ({ kind: "disc", cx: 1.6 + 2.54 + i * 2.54, cy: 1.6, r: 0.9, color: MATERIAL.gold }) as Solid),
      ...Array.from({ length: 20 }, (_, i) => ({ kind: "disc", cx: 1.6 + 2.54 + i * 2.54, cy: 19.4, r: 0.9, color: MATERIAL.gold }) as Solid),
      ...Array.from({ length: 3 }, (_, i) => ({ kind: "disc", cx: 48.5, cy: 8 + i * 2.54, r: 0.9, color: MATERIAL.gold }) as Solid),
      microUsb(-1.3, 7.75),
      chip(22, 7.3, 7, 7, "RP2040", 0.9),
      chip(33, 7.5, 6, 5, "FLASH", 0.9),
      ...tactileButton(14, 8, 3.5, "bootsel"),
      smdLed(8, 4, "#3ddc84", "led"),
      { kind: "box", x: 40.5, y: 7.5, w: 4, h: 3, d: 1, z: 1.6, top: MATERIAL.ic, side: MATERIAL.icSide, label: { text: "LDO", size: 1, color: "#a3a7ad" } },
      { kind: "cyl", cx: 30.5, cy: 15.5, r: 1.3, d: 1.2, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, segments: 10 },
      silk(10, 5.2, "LED", 0.9),
      silk(12.5, 13.5, "BOOTSEL", 1),
      silk(24, 17.6, "Raspberry Pi Pico", 1.4, MATERIAL.silk, { weight: 700 }),
      silk(45, 6.4, "DEBUG", 0.9),
    ],
    features: [
      { id: "gpio-top", label: "GPIO pads, top edge", kind: "pins", x: 3, y: 0.4, w: 50.8, h: 2.4, note: "20 castellated pads: GP0–GP22 with GND every third pin. Solder headers on for a breadboard." },
      { id: "gpio-bottom", label: "GPIO pads, bottom edge", kind: "pins", x: 3, y: 18.2, w: 50.8, h: 2.4, note: "The other 20 pads, including the three analog inputs (GP26–28), 3V3, VSYS and VBUS." },
      { id: "usb", label: "Micro-USB", kind: "port", x: -1.3, y: 7.75, w: 7.5, h: 5.5, note: "Power and programming. With BOOTSEL held it appears as a drive you drop firmware onto." },
      { id: "rp2040", label: "RP2040", kind: "chip", x: 22, y: 7.3, w: 7, h: 7, note: "Two Cortex-M0+ cores at 133 MHz, 264 KB RAM and 8 programmable I/O state machines." },
      { id: "flash", label: "2 MB flash", kind: "chip", x: 33, y: 7.5, w: 6, h: 5, note: "Program storage; the RP2040 has none of its own." },
      { id: "bootsel", label: "BOOTSEL button", kind: "button", x: 14, y: 8, w: 3.5, h: 3.5, note: "Hold while plugging in USB to enter the USB mass-storage bootloader." },
      { id: "led", label: "Onboard LED", kind: "led", x: 7.5, y: 3.4, w: 2.6, h: 1.8, note: "Green, wired to GP25. The Pico has no power LED, so this is the one Blink flashes." },
      { id: "debug", label: "SWD debug pads", kind: "pins", x: 47.5, y: 7, w: 2, h: 7.6, note: "SWCLK, GND and SWDIO for a hardware debugger." },
    ],
    pins: [
      { name: "GP0–GP22", role: "digital", note: "3.3 V GPIO; any pin can do PWM, and I2C, SPI and UART are assigned in software" },
      { name: "GP26–GP28", role: "analog", note: "12-bit ADC inputs, 0–3.3 V" },
      { name: "GP25", role: "digital", note: "The onboard LED" },
      { name: "VBUS", role: "power", note: "5 V straight from USB" },
      { name: "VSYS", role: "power", note: "Main input, 1.8–5.5 V; power the board here from batteries" },
      { name: "3V3", role: "power", note: "3.3 V out from the onboard regulator, 300 mA" },
      { name: "GND", role: "ground", note: "Eight ground pads" },
      { name: "RUN", role: "other", note: "Pull low to reset" },
      { name: "SWCLK / SWDIO", role: "data", note: "Debug port" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "5 V, USB 1.1", kind: "connector", col: 0, row: 0, note: "The RP2040 speaks USB itself, so there is no bridge chip." },
        { id: "reg", label: "Buck-boost", sub: "3.3 V", kind: "regulator", col: 1, row: 1, note: "Makes 3.3 V from anything between 1.8 and 5.5 V on VSYS." },
        { id: "mcu", label: "RP2040", sub: "2 × M0+, 133 MHz", kind: "mcu", col: 2, row: 0, note: "Runs your program from external flash, with eight PIO state machines for custom protocols." },
        { id: "flash", label: "Flash", sub: "2 MB QSPI", kind: "ic", col: 2, row: 2, note: "Holds the program; the BOOTSEL button makes the chip boot from USB instead." },
        { id: "gpio", label: "GPIO pads", sub: "26 × 3.3 V", kind: "pin", col: 3, row: 0, note: "Castellated so the board can be soldered flat onto another one." },
        { id: "adc", label: "ADC", sub: "GP26–28", kind: "pin", col: 3, row: 1, note: "Three 12-bit analog inputs." },
        { id: "pwr", label: "Power pads", sub: "VSYS, VBUS, 3V3", kind: "power", col: 3, row: 2, note: "Feed the board or take 3.3 V from it." },
      ],
      links: [
        { from: "usb", to: "mcu", kind: "data", label: "USB", both: true },
        { from: "usb", to: "reg", kind: "power", label: "VBUS" },
        { from: "reg", to: "mcu", kind: "power", label: "3.3 V" },
        { from: "reg", to: "pwr", kind: "power" },
        { from: "mcu", to: "flash", kind: "data", both: true },
        { from: "mcu", to: "gpio", kind: "signal", both: true },
        { from: "adc", to: "mcu", kind: "analog" },
      ],
      steps: [
        "5 V from USB (VBUS) or anything from 1.8–5.5 V on VSYS feeds a buck-boost regulator that makes a steady 3.3 V.",
        "The RP2040 has USB built in, so the computer talks to it directly; holding BOOTSEL at power-up makes it appear as a drive.",
        "The chip executes code straight from the 2 MB flash next to it, on two Cortex-M0+ cores.",
        "The castellated pads carry 26 GPIO at 3.3 V, three of them analog, plus power and debug.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V" },
      { label: "Clock", value: "133 MHz, 2 cores" },
      { label: "Memory", value: "2 MB flash, 264 KB RAM" },
      { label: "Pins", value: "26 GPIO, 3 analog" },
      { label: "Languages", value: "C/C++, MicroPython" },
      { label: "Size", value: "51 × 21 mm" },
    ],
    animate: { lit: ["led"] },
    experiment: { title: "Blink in MicroPython", idea: "Toggle GP25 from the REPL, then read the onboard temperature sensor on ADC channel 4." },
    tags: ["pico", "rp2040", "raspberry pi", "micropython", "3.3v", "board", "mcu"],
  },

  {
    id: "arduino-mega",
    name: "Arduino Mega 2560",
    aka: ["Mega", "ATmega2560 board"],
    group: "boards",
    rank: 4,
    summary: "The Uno's big sibling: 54 digital pins, 16 analog inputs, four serial ports and far more memory, for projects that run out of pins on an Uno.",
    size: { w: 101.5, h: 53.3, d: 12.6 },
    solids: [
      pcb(101.5, 53.3, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      usbB(-6, 5.5),
      barrelJack(-3, 39),
      header(18.5, 1.6, 10, "x"),
      header(44.6, 1.6, 8, "x"),
      header(66, 1.6, 8, "x"),
      header(24, 49.3, 8, "x"),
      header(46.5, 49.3, 8, "x"),
      header(68, 49.3, 8, "x"),
      header(91, 8, 18, "y", 2),
      header(78, 23, 3, "y", 2),
      chip(60, 22, 14, 14, "ATMEGA2560", 1.2),
      chip(14.5, 17.5, 4.4, 4.4, undefined, 0.9),
      ...tactileButton(12.5, 6, 4.5),
      capacitor(20.5, 30.5, 1.6, 4, 1.6),
      capacitor(24.5, 30.5, 1.6, 4, 1.6),
      { kind: "cyl", cx: 48, cy: 22, r: 1.6, d: 2.5, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, segments: 12 },
      { kind: "box", x: 13.5, y: 40, w: 5, h: 7, d: 2, z: 1.6, top: "linear-gradient(90deg,#b9bdc3 0 30%,#1b1c1f 30%)", side: MATERIAL.icSide, fill: MATERIAL.ic },
      smdLed(30, 8.6, "#ffb020", "led-l"),
      smdLed(30, 11.6, "#ffb020", "led-tx"),
      smdLed(30, 14.6, "#ffb020", "led-rx"),
      smdLed(36, 22, "#3ddc84", "led-on"),
      mountHole(2.5, 25),
      mountHole(66, 11),
      mountHole(66, 49),
      mountHole(96, 3),
      mountHole(96, 50),
      silk(37.5, 44, "HHIP", 5, MATERIAL.silk, { weight: 800 }),
      silk(37.5, 47, "MEGA-LAYOUT  5V", 1.3),
      silk(25, 13.5, "PWM", 1.3),
      silk(66, 13.5, "COMMUNICATION", 1.2),
      silk(24, 48.4, "POWER", 1.3),
      silk(48, 48.4, "ANALOG IN", 1.3),
      silk(86, 6.5, "DIGITAL", 1.1),
      silk(33.5, 9, "L", 1.2),
      silk(33.5, 12, "TX", 1.2),
      silk(33.5, 15, "RX", 1.2),
      silk(39.5, 22.6, "ON", 1.2),
    ],
    features: [
      { id: "pwm", label: "PWM pins 2–13", kind: "pins", x: 18.5, y: 1.6, w: 46.4, h: 2.54, note: "The same digital pins as an Uno, all with PWM. Shields made for the Uno fit here." },
      { id: "comm", label: "Serial pins 14–21", kind: "pins", x: 66, y: 1.6, w: 20.3, h: 2.54, note: "Three extra hardware serial ports (TX1–TX3, RX1–RX3) plus SDA and SCL." },
      { id: "digital", label: "Digital pins 22–53", kind: "pins", x: 91, y: 8, w: 5.1, h: 45.7, note: "A double row of 36 pins at the end of the board: 32 more digital pins and power." },
      { id: "analog", label: "Analog inputs A0–A15", kind: "pins", x: 46.5, y: 49.3, w: 41, h: 2.54, note: "Sixteen 10-bit analog inputs, 0–5 V." },
      { id: "power", label: "Power pins", kind: "power", x: 24, y: 49.3, w: 20.3, h: 2.54, note: "5 V, 3.3 V, GND, VIN and RESET." },
      { id: "usb", label: "USB-B port", kind: "port", x: -6, y: 5.5, w: 16, h: 12, note: "Programming, serial and 5 V power." },
      { id: "jack", label: "Barrel jack", kind: "port", x: -3, y: 39, w: 14, h: 9, note: "7–12 V DC in. The onboard regulator makes 5 V from it." },
      { id: "mcu", label: "ATmega2560", kind: "chip", x: 60, y: 22, w: 14, h: 14, note: "A 100-pin chip with 256 KB flash and 8 KB RAM, soldered to the board." },
      { id: "led-l", label: "L LED (pin 13)", kind: "led", x: 29.5, y: 8, w: 2.6, h: 1.8, note: "Wired to digital pin 13." },
      { id: "reset", label: "Reset button", kind: "button", x: 12.5, y: 6, w: 4.5, h: 4.5, note: "Restarts the sketch." },
    ],
    pins: [
      { name: "D0–D53", role: "digital", note: "54 digital pins at 5 V; 2–13 and 44–46 can output PWM" },
      { name: "A0–A15", role: "analog", note: "16 analog inputs, 10-bit" },
      { name: "TX0–TX3 / RX0–RX3", role: "uart", note: "Four hardware serial ports; port 0 is shared with USB" },
      { name: "SDA / SCL (20 / 21)", role: "i2c", note: "I2C, also duplicated near AREF" },
      { name: "50–53", role: "spi", note: "MISO, MOSI, SCK, SS" },
      { name: "5V / 3.3V", role: "power", note: "Regulated outputs" },
      { name: "GND", role: "ground", note: "Five ground pins" },
      { name: "VIN", role: "power", note: "7–12 V in" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "USB-B", sub: "5 V in, serial", kind: "connector", col: 0, row: 0, note: "Power and programming." },
        { id: "jack", label: "Barrel jack", sub: "7–12 V in", kind: "connector", col: 0, row: 2, note: "External supply." },
        { id: "bridge", label: "USB bridge", sub: "ATmega16U2", kind: "ic", col: 1, row: 0, note: "USB to serial for uploads." },
        { id: "reg", label: "5 V regulator", kind: "regulator", col: 1, row: 2, note: "Steady 5 V for the board." },
        { id: "mcu", label: "ATmega2560", sub: "16 MHz, 100 pins", kind: "mcu", col: 2, row: 1, note: "The same family as the Uno's chip with far more pins and memory." },
        { id: "digital", label: "Digital pins", sub: "D0–D53", kind: "pin", col: 3, row: 0, note: "54 digital, 15 with PWM." },
        { id: "serial", label: "Serial ports", sub: "4 × UART", kind: "pin", col: 3, row: 1, note: "Talk to a GPS, a Bluetooth module and a computer at once." },
        { id: "analog", label: "Analog inputs", sub: "A0–A15", kind: "pin", col: 3, row: 2, note: "16 inputs, 0–5 V." },
      ],
      links: [
        { from: "usb", to: "bridge", kind: "data", label: "USB" },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "jack", to: "reg", kind: "power", label: "VIN" },
        { from: "bridge", to: "mcu", kind: "data", label: "TX/RX", both: true },
        { from: "reg", to: "mcu", kind: "power", label: "5 V" },
        { from: "mcu", to: "digital", kind: "signal", both: true },
        { from: "mcu", to: "serial", kind: "data", both: true },
        { from: "analog", to: "mcu", kind: "analog" },
      ],
      steps: [
        "Power comes from USB or the jack and is regulated to 5 V, exactly as on the Uno.",
        "The ATmega16U2 bridge handles USB; the ATmega2560 runs your sketch with 256 KB of flash.",
        "Its 100 pins fan out to 54 digital pins, 16 analog inputs and four serial ports.",
      ],
    },
    facts: [
      { label: "Logic", value: "5 V" },
      { label: "Clock", value: "16 MHz" },
      { label: "Memory", value: "256 KB flash, 8 KB RAM" },
      { label: "Pins", value: "54 digital (15 PWM), 16 analog" },
      { label: "Serial", value: "4 hardware UARTs" },
      { label: "Size", value: "101.5 × 53.3 mm" },
    ],
    animate: { lit: ["led-on", "led-l"] },
    experiment: { title: "Many sensors, one board", idea: "Read six sensors on six analog pins and print them as a table over Serial every second." },
    tags: ["arduino", "mega", "atmega2560", "5v", "board", "mcu", "many pins"],
  },

  {
    id: "esp8266",
    name: "ESP8266 NodeMCU",
    aka: ["NodeMCU", "ESP-12E board", "LoLin V3"],
    group: "boards",
    rank: 5,
    summary: "The cheapest way to put a project on Wi-Fi: an ESP-12E module on a USB-programmable board. One core, 3.3 V, fewer pins than an ESP32 but plenty for a sensor that reports online.",
    size: { w: 58, h: 31, d: 10 },
    solids: [
      pcb(58, 31, MATERIAL.pcbBlack, MATERIAL.pcbBlackEdge),
      ...maleHeader(2, 1, 15, "x"),
      ...maleHeader(2, 27.5, 15, "x"),
      shieldCan(34, 7, 16, 17, "ESP-12E"),
      pcbAntenna(51, 9, 4, 13),
      microUsb(-1.5, 12.7),
      ...tactileButton(8, 5, 4, "btn-rst"),
      ...tactileButton(8, 22, 4, "btn-flash"),
      chip(17, 12.5, 6, 6, "CH340", 0.9),
      { kind: "box", x: 25, y: 6, w: 6.5, h: 6.5, d: 1.2, z: 1.6, top: "#1b1c1f", side: MATERIAL.icSide, label: { text: "1117", size: 1.3, color: "#a3a7ad" } },
      smdLed(37, 23.5, "#3b82f6", "led"),
      silk(7.5, 10.8, "RST", 1.1),
      silk(6.5, 27.2, "FLASH", 1.0),
      silk(16, 23, "NodeMCU", 1.5, MATERIAL.silk, { weight: 700 }),
    ],
    features: [
      { id: "module", label: "ESP-12E module", kind: "chip", x: 34, y: 7, w: 16, h: 17, note: "The ESP8266 at 80 MHz with 4 MB flash and Wi-Fi, under a shield." },
      { id: "antenna", label: "PCB antenna", kind: "antenna", x: 50.5, y: 8, w: 5, h: 15, note: "Printed 2.4 GHz antenna; hang it over the edge of a breadboard for range." },
      { id: "usb", label: "Micro-USB", kind: "port", x: -1.5, y: 12.7, w: 7.5, h: 5.5, note: "Programming and 5 V power." },
      { id: "top-pins", label: "Pins, top row", kind: "pins", x: 2, y: 1, w: 38.1, h: 2.54, note: "A0 (the only analog input, 0–1 V on the chip, 0–3.3 V on the board), reserved SD pins, D0–D4 and 3V3." },
      { id: "bottom-pins", label: "Pins, bottom row", kind: "pins", x: 2, y: 27.5, w: 38.1, h: 2.54, note: "D5–D8, RX, TX, GND and VIN. Note the D numbers differ from the GPIO numbers." },
      { id: "rst", label: "RST button", kind: "button", x: 8, y: 5, w: 4, h: 4, note: "Restarts the chip; hold FLASH while pressing it to enter programming mode." },
      { id: "flash", label: "FLASH button", kind: "button", x: 8, y: 22, w: 4, h: 4, note: "Hold at reset to enter the bootloader by hand." },
      { id: "bridge", label: "CH340 USB bridge", kind: "chip", x: 17, y: 12.5, w: 6, h: 6, note: "USB to serial; needs a driver on some computers." },
      { id: "led", label: "Module LED", kind: "led", x: 36.5, y: 22.9, w: 2.6, h: 1.8, note: "Blue; on GPIO 2 (D4), lit when the pin is low." },
    ],
    pins: [
      { name: "D0–D8", role: "digital", note: "Nine GPIO at 3.3 V; D0 has no PWM or interrupt, D3, D4 and D8 are boot pins" },
      { name: "A0", role: "analog", note: "The single 10-bit analog input, 0–3.3 V via the onboard divider" },
      { name: "D1 / D2", role: "i2c", note: "Default SCL and SDA" },
      { name: "D5 / D6 / D7 / D8", role: "spi", note: "SCK, MISO, MOSI, CS" },
      { name: "TX / RX", role: "uart", note: "Serial, shared with USB" },
      { name: "VIN", role: "power", note: "5 V in" },
      { name: "3V3", role: "power", note: "3.3 V out" },
      { name: "GND", role: "ground", note: "Several ground pins" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "5 V, serial", kind: "connector", col: 0, row: 0, note: "Power and programming." },
        { id: "bridge", label: "USB bridge", sub: "CH340G", kind: "ic", col: 1, row: 0, note: "USB to serial with auto-reset for uploads." },
        { id: "reg", label: "3.3 V regulator", sub: "AMS1117", kind: "regulator", col: 1, row: 2, note: "Everything on the board runs at 3.3 V." },
        { id: "esp", label: "ESP8266", sub: "80 MHz", kind: "mcu", col: 2, row: 1, note: "One core shared between your code and the Wi-Fi stack; keep loops short so Wi-Fi gets its turn." },
        { id: "antenna", label: "Antenna", sub: "2.4 GHz", kind: "antenna", col: 3, row: 0, note: "Printed on the module." },
        { id: "gpio", label: "GPIO", sub: "D0–D8", kind: "pin", col: 3, row: 1, note: "Nine usable pins at 3.3 V." },
        { id: "adc", label: "A0", sub: "10-bit", kind: "pin", col: 3, row: 2, note: "One analog input." },
      ],
      links: [
        { from: "usb", to: "bridge", kind: "data", label: "USB" },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "bridge", to: "esp", kind: "data", label: "serial", both: true },
        { from: "reg", to: "esp", kind: "power", label: "3.3 V" },
        { from: "esp", to: "antenna", kind: "rf", both: true },
        { from: "esp", to: "gpio", kind: "signal", both: true },
        { from: "adc", to: "esp", kind: "analog" },
      ],
      steps: [
        "USB supplies 5 V; the AMS1117 makes 3.3 V for the module.",
        "The CH340 bridge carries serial to the ESP8266 and resets it into bootloader mode for uploads.",
        "The single-core ESP8266 runs your sketch between Wi-Fi tasks and drives nine GPIO at 3.3 V plus one analog input.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V" },
      { label: "Clock", value: "80 MHz, 1 core" },
      { label: "Radio", value: "Wi-Fi 2.4 GHz" },
      { label: "Memory", value: "4 MB flash, 80 KB RAM" },
      { label: "Pins", value: "9 GPIO, 1 analog" },
      { label: "Size", value: "58 × 31 mm" },
    ],
    animate: { lit: ["led"] },
    experiment: { title: "Web page from a chip", idea: "Serve a web page showing the A0 reading and refresh it every few seconds." },
    tags: ["esp8266", "nodemcu", "wifi", "iot", "3.3v", "board", "mcu"],
  },

  {
    id: "stm32",
    name: "STM32 Blue Pill",
    aka: ["Blue Pill", "STM32F103C8T6 board"],
    group: "boards",
    rank: 6,
    summary: "A tiny ARM Cortex-M3 board at 72 MHz with real hardware timers, three serial ports and 5 V-tolerant pins, for when an Arduino is too slow and an ESP32 is too much.",
    size: { w: 53, h: 22.5, d: 10 },
    solids: [
      pcb(53, 22.5, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      ...maleHeader(1.5, 0.8, 20, "x"),
      ...maleHeader(1.5, 19.2, 20, "x"),
      microUsb(-1.5, 8.5),
      chip(24.5, 7.75, 7, 7, "STM32", 1),
      ...maleHeader(13, 6, 3, "y", 2, false),
      { kind: "box", x: 13, y: 6, w: 5.08, h: 2.54, d: 5, z: 2.5, top: "#f5c518", side: "#b8900f", radius: 0.3 },
      { kind: "box", x: 13, y: 11.1, w: 5.08, h: 2.54, d: 5, z: 2.5, top: "#f5c518", side: "#b8900f", radius: 0.3 },
      ...tactileButton(8, 9, 3.5, "reset"),
      { kind: "cyl", cx: 36, cy: 6.5, r: 1.3, d: 1.2, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, segments: 10 },
      { kind: "box", x: 34, y: 14, w: 3.5, h: 1.6, d: 1, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide },
      ...maleHeader(49, 6.2, 4, "y", 1, false),
      smdLed(40, 4, "#ef4444", "led-pwr"),
      smdLed(40, 17, "#3ddc84", "led-pc13"),
      silk(10, 16.5, "BOOT1  BOOT0", 0.9),
      silk(38, 4.2, "PWR", 0.9),
      silk(38, 17.2, "PC13", 0.9),
      silk(44, 5, "SWD", 0.9),
    ],
    features: [
      { id: "mcu", label: "STM32F103C8T6", kind: "chip", x: 24.5, y: 7.75, w: 7, h: 7, note: "72 MHz Cortex-M3, 64 KB flash, 20 KB RAM, with hardware timers, three UARTs, two SPI, two I2C and a 12-bit ADC." },
      { id: "top-pins", label: "Pins, top row", kind: "pins", x: 1.5, y: 0.8, w: 50.8, h: 2.54, note: "VB, C13–C15, A0–A7, B0–B1, B10–B11, R, 3.3, G, G." },
      { id: "bottom-pins", label: "Pins, bottom row", kind: "pins", x: 1.5, y: 19.2, w: 50.8, h: 2.54, note: "G, G, 3.3, R, B11–B10, B1, B0, A7–A0, C15–C13, VB." },
      { id: "usb", label: "Micro-USB", kind: "port", x: -1.5, y: 8.5, w: 7.5, h: 5.5, note: "5 V power and, with the right bootloader, programming." },
      { id: "boot", label: "BOOT0 / BOOT1 jumpers", kind: "connector", x: 13, y: 6, w: 5.1, h: 7.6, note: "Set BOOT0 high to run the built-in serial bootloader; both low to run your program." },
      { id: "swd", label: "SWD header", kind: "pins", x: 49, y: 6.2, w: 2.54, h: 10.2, note: "3.3 V, SWDIO, SWCLK, GND for an ST-Link programmer, the easiest way to flash it." },
      { id: "reset", label: "Reset button", kind: "button", x: 8, y: 9, w: 3.5, h: 3.5, note: "Restarts the program from the top." },
      { id: "led-pc13", label: "PC13 LED", kind: "led", x: 39.5, y: 16.4, w: 2.6, h: 1.8, note: "Green; the user LED, lit when PC13 is low." },
      { id: "led-pwr", label: "Power LED", kind: "led", x: 39.5, y: 3.4, w: 2.6, h: 1.8, note: "Red; on with power." },
    ],
    pins: [
      { name: "PA0–PA15, PB0–PB15", role: "digital", note: "3.3 V GPIO; many are 5 V tolerant as inputs (check the datasheet per pin)" },
      { name: "PA0–PA7, PB0–PB1", role: "analog", note: "12-bit ADC inputs, 0–3.3 V" },
      { name: "PC13", role: "digital", note: "Onboard LED; weak output, don't load it" },
      { name: "PA9 / PA10", role: "uart", note: "USART1 TX and RX" },
      { name: "PB6 / PB7", role: "i2c", note: "I2C1 SCL and SDA" },
      { name: "PA5 / PA6 / PA7", role: "spi", note: "SPI1 SCK, MISO, MOSI" },
      { name: "5V", role: "power", note: "From USB; feeds the 3.3 V regulator" },
      { name: "3.3", role: "power", note: "3.3 V out" },
      { name: "G", role: "ground", note: "Ground" },
      { name: "VB", role: "power", note: "Battery backup for the clock" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "5 V", kind: "connector", col: 0, row: 0, note: "Power, and USB straight into the chip." },
        { id: "swd", label: "SWD", sub: "ST-Link", kind: "connector", col: 0, row: 2, note: "The debug port most people program it through." },
        { id: "reg", label: "3.3 V regulator", kind: "regulator", col: 1, row: 1, note: "Low-current regulator; power big loads elsewhere." },
        { id: "mcu", label: "STM32F103", sub: "72 MHz, M3", kind: "mcu", col: 2, row: 1, note: "An ARM chip with proper timers and DMA." },
        { id: "gpio", label: "GPIO", sub: "32 pins", kind: "pin", col: 3, row: 0, note: "3.3 V logic, many 5 V tolerant." },
        { id: "periph", label: "Peripherals", sub: "UART, SPI, I2C, CAN", kind: "pin", col: 3, row: 1, note: "Three UARTs, two SPI, two I2C, CAN and USB in hardware." },
        { id: "adc", label: "ADC", sub: "10 × 12-bit", kind: "pin", col: 3, row: 2, note: "Up to 1 million samples a second." },
      ],
      links: [
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "usb", to: "mcu", kind: "data", label: "USB", both: true },
        { from: "swd", to: "mcu", kind: "data", label: "SWD", both: true },
        { from: "reg", to: "mcu", kind: "power", label: "3.3 V" },
        { from: "mcu", to: "gpio", kind: "signal", both: true },
        { from: "mcu", to: "periph", kind: "data", both: true },
        { from: "adc", to: "mcu", kind: "analog" },
      ],
      steps: [
        "5 V from USB is regulated to 3.3 V for the chip.",
        "Programs go in through the SWD header with an ST-Link, or over serial with BOOT0 high.",
        "The Cortex-M3 runs at 72 MHz and exposes 32 GPIO, a 12-bit ADC and hardware UART, SPI, I2C and CAN.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V (many pins 5 V tolerant)" },
      { label: "Clock", value: "72 MHz Cortex-M3" },
      { label: "Memory", value: "64 KB flash, 20 KB RAM" },
      { label: "Pins", value: "32 GPIO, 10 analog" },
      { label: "Programming", value: "ST-Link (SWD) or serial bootloader" },
      { label: "Size", value: "53 × 22.5 mm" },
    ],
    animate: { lit: ["led-pwr", "led-pc13"] },
    experiment: { title: "Fast analog capture", idea: "Sample A0 at 100 kHz into a buffer and stream it over serial." },
    tags: ["stm32", "blue pill", "arm", "cortex-m3", "3.3v", "board", "mcu"],
  },

  {
    id: "raspberry-pi-4",
    name: "Raspberry Pi 4",
    aka: ["Pi 4 Model B", "Raspberry Pi"],
    group: "boards",
    rank: 7,
    summary: "A full Linux computer the size of a credit card, with 40 GPIO pins. Use it when a project needs a camera, a screen, networking or Python with real libraries.",
    size: { w: 85, h: 56, d: 16 },
    solids: [
      pcb(85, 56, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      ...maleHeader(29, 1.6, 20, "x", 2, false),
      chip(29, 24, 15, 15, "BCM2711", 1.5, "soc"),
      chip(50, 25, 12, 12, "LPDDR4", 1.2),
      shieldCan(4, 24, 10, 12, "Wi-Fi", 2.2),
      usbA(74, 2, ),
      usbA(74, 20),
      { kind: "box", x: 68, y: 38, w: 17, h: 16, d: 13.5, top: "linear-gradient(180deg,#d7dadf,#aeb3ba)", side: MATERIAL.steelSide, fill: MATERIAL.steel, radius: 0.5, label: { text: "ETH", size: 2, color: "#4b5059" } },
      usbC(3, 49.5),
      { kind: "box", x: 15, y: 50, w: 6.5, h: 5.5, d: 3, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 0.5 },
      { kind: "box", x: 28, y: 50, w: 6.5, h: 5.5, d: 3, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 0.5 },
      { kind: "cyl", cx: 52, cy: 51.5, r: 3, d: 5, z: 1.6, top: "#1b1c1f", side: MATERIAL.icSide, segments: 14 },
      { kind: "box", x: 1, y: 1.5, w: 2.5, h: 20, d: 5.5, top: "#1b1c1f", side: MATERIAL.icSide, radius: 0.3 },
      { kind: "box", x: 44, y: 44, w: 2.5, h: 11, d: 5.5, top: "#1b1c1f", side: MATERIAL.icSide, radius: 0.3 },
      chip(54, 6, 6, 6, "VL805", 0.9),
      smdLed(2, 42, "#ef4444", "led-pwr"),
      smdLed(2, 45.5, "#3ddc84", "led-act"),
      ...maleHeader(58, 1.6, 2, "x", 2, false),
      mountHole(3.5, 3.5),
      mountHole(61.5, 3.5),
      mountHole(3.5, 52.5),
      mountHole(61.5, 52.5),
      silk(5, 40.5, "PWR", 1),
      silk(5, 47, "ACT", 1),
      silk(14, 15, "Raspberry Pi 4", 2.2, MATERIAL.silk, { weight: 700 }),
      silk(14, 18.5, "Model B", 1.4),
      silk(30, 7.5, "GPIO", 1.2),
      silk(14, 48.8, "HDMI0", 0.9),
      silk(27, 48.8, "HDMI1", 0.9),
      silk(2, 48.6, "PWR IN", 0.9),
      silk(48, 48.5, "AUDIO", 0.9),
    ],
    features: [
      { id: "gpio", label: "40-pin GPIO header", kind: "pins", x: 29, y: 1.6, w: 50.8, h: 5.08, note: "26 GPIO at 3.3 V plus 5 V, 3.3 V and ground pins. No analog inputs; use an ADC chip." },
      { id: "soc", label: "BCM2711", kind: "chip", x: 29, y: 24, w: 15, h: 15, note: "Four Cortex-A72 cores at 1.5 GHz under a metal lid. It gets warm; a heatsink helps." },
      { id: "ram", label: "RAM", kind: "chip", x: 50, y: 25, w: 12, h: 12, note: "1, 2, 4 or 8 GB of LPDDR4 depending on the model." },
      { id: "usb", label: "USB ports", kind: "port", x: 74, y: 2, w: 13.5, h: 32.5, note: "Two USB 2.0 and two USB 3.0 (blue) for keyboards, cameras and drives." },
      { id: "eth", label: "Gigabit Ethernet", kind: "port", x: 68, y: 38, w: 17, h: 16, note: "Wired network; can take power over Ethernet with a HAT." },
      { id: "usbc", label: "USB-C power", kind: "port", x: 3, y: 49.5, w: 9, h: 7.5, note: "5 V at 3 A in. A weak supply is the most common cause of trouble." },
      { id: "hdmi", label: "Micro-HDMI ×2", kind: "port", x: 15, y: 50, w: 19.5, h: 5.5, note: "Two 4K displays." },
      { id: "wifi", label: "Wi-Fi and Bluetooth", kind: "antenna", x: 4, y: 24, w: 10, h: 12, note: "Dual-band Wi-Fi and Bluetooth 5 under the small shield." },
      { id: "camera", label: "Camera and display connectors", kind: "connector", x: 44, y: 44, w: 2.5, h: 11, note: "Ribbon connectors for the official camera (CSI) and display (DSI)." },
      { id: "leds", label: "PWR and ACT LEDs", kind: "led", x: 1.5, y: 41.4, w: 3, h: 5.5, note: "Red for power, green flickers with SD-card activity." },
    ],
    pins: [
      { name: "GPIO 2–27", role: "digital", note: "26 GPIO at 3.3 V; not 5 V tolerant" },
      { name: "GPIO 2 / 3", role: "i2c", note: "SDA and SCL, with onboard pull-ups" },
      { name: "GPIO 14 / 15", role: "uart", note: "TXD and RXD" },
      { name: "GPIO 9 / 10 / 11 / 8 / 7", role: "spi", note: "MISO, MOSI, SCLK, CE0, CE1" },
      { name: "GPIO 12 / 13 / 18 / 19", role: "pwm", note: "Hardware PWM" },
      { name: "5V", role: "power", note: "Two pins, straight from the USB-C input" },
      { name: "3V3", role: "power", note: "Two pins, 3.3 V out" },
      { name: "GND", role: "ground", note: "Eight ground pins" },
    ],
    circuit: {
      blocks: [
        { id: "usbc", label: "USB-C", sub: "5 V 3 A", kind: "connector", col: 0, row: 1, note: "All power enters here." },
        { id: "pmic", label: "Power manager", sub: "MXL7704", kind: "regulator", col: 1, row: 1, note: "Makes the half-dozen voltages the processor and memory need." },
        { id: "soc", label: "BCM2711", sub: "4 × A72, 1.5 GHz", kind: "mcu", col: 2, row: 0, note: "Runs Linux from the microSD card." },
        { id: "ram", label: "LPDDR4", sub: "up to 8 GB", kind: "ic", col: 2, row: 2, note: "Working memory." },
        { id: "usb", label: "USB 3 controller", sub: "VL805", kind: "ic", col: 3, row: 0, note: "Four USB ports over PCIe." },
        { id: "gpio", label: "GPIO header", sub: "40 pins", kind: "pin", col: 3, row: 1, note: "3.3 V GPIO, I2C, SPI, UART, PWM." },
        { id: "net", label: "Network", sub: "Ethernet, Wi-Fi, BT", kind: "antenna", col: 3, row: 2, note: "Gigabit wired, dual-band wireless." },
      ],
      links: [
        { from: "usbc", to: "pmic", kind: "power", label: "5 V" },
        { from: "pmic", to: "soc", kind: "power" },
        { from: "pmic", to: "ram", kind: "power" },
        { from: "soc", to: "ram", kind: "data", both: true },
        { from: "soc", to: "usb", kind: "data", label: "PCIe", both: true },
        { from: "soc", to: "gpio", kind: "signal", both: true },
        { from: "soc", to: "net", kind: "data", both: true },
      ],
      steps: [
        "5 V at up to 3 A enters by USB-C; the power manager chip converts it into the core, memory and I/O voltages.",
        "The BCM2711 boots Linux from the microSD card (underneath) using the RAM beside it.",
        "The GPIO header exposes 26 pins at 3.3 V; USB, Ethernet, HDMI and wireless are handled by their own controllers.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V" },
      { label: "Processor", value: "4 × Cortex-A72, 1.5 GHz" },
      { label: "Memory", value: "1–8 GB RAM, microSD storage" },
      { label: "Pins", value: "26 GPIO, no analog" },
      { label: "Network", value: "Gigabit Ethernet, Wi-Fi, Bluetooth 5" },
      { label: "Size", value: "85 × 56 mm" },
    ],
    animate: { lit: ["led-pwr", "led-act"] },
    experiment: { title: "Python reads a sensor", idea: "Wire a DHT11 to GPIO 4, read it from Python and log the values to a file every minute." },
    tags: ["raspberry pi", "pi 4", "linux", "sbc", "python", "3.3v", "board", "computer"],
  },

  {
    id: "microbit",
    name: "BBC micro:bit",
    aka: ["micro:bit V2"],
    group: "boards",
    rank: 8,
    summary: "A classroom board with a 5×5 LED display, two buttons, motion sensors, a speaker, a microphone and radio, all built in. Programs in blocks, Python or C++ with nothing extra to buy.",
    size: { w: 52, h: 42, d: 8 },
    solids: [
      pcb(52, 42, MATERIAL.pcbBlack, MATERIAL.pcbBlackEdge, 3),
      ...Array.from({ length: 25 }, (_, i) => smdLed(18.6 + (i % 5) * 3.2, 12 + Math.floor(i / 5) * 3.2, "#ef4444", `led-${i}`)),
      ...tactileButton(5, 16, 6, "btn-a"),
      ...tactileButton(41, 16, 6, "btn-b"),
      microUsb(22, -1),
      ...tactileButton(31, 1.5, 3, "reset"),
      { kind: "box", x: 10, y: 1.5, w: 6, h: 4.5, d: 3.5, top: MATERIAL.plasticWhite, side: "#b9bec4", radius: 0.5 },
      chip(37, 4, 5, 5, "nRF52", 0.9),
      ...Array.from({ length: 5 }, (_, i) => ({ kind: "disc", cx: 5 + i * 10.5, cy: 38.5, r: 2.4, color: MATERIAL.gold }) as Solid),
      ...Array.from({ length: 5 }, (_, i) => ({ kind: "disc", cx: 5 + i * 10.5, cy: 38.5, r: 1.1, color: MATERIAL.pcbBlack }) as Solid),
      { kind: "path", d: "M 0 35 H 52", color: MATERIAL.gold, width: 1.2 },
      { kind: "cyl", cx: 26, cy: 6, r: 1.2, d: 0.3, z: 1.6, top: "#3b3d42", side: "#1b1c1f", segments: 10 },
      { kind: "box", x: 23.5, y: 30, w: 5, h: 2.5, d: 0.3, z: 1.6, top: MATERIAL.gold, side: MATERIAL.gold, radius: 1.2 },
      silk(6.5, 24.6, "A", 1.6, MATERIAL.silk, { weight: 700 }),
      silk(42.8, 24.6, "B", 1.6, MATERIAL.silk, { weight: 700 }),
      silk(3.5, 33.6, "0", 1.3), silk(14, 33.6, "1", 1.3), silk(24.5, 33.6, "2", 1.3), silk(34, 33.6, "3V", 1.3), silk(44, 33.6, "GND", 1.3),
      silk(10, 8.2, "BATT", 0.9),
      silk(29.5, 6.5, "RESET", 0.8),
      silk(24, 9, "MIC", 0.8),
    ],
    features: [
      { id: "matrix", label: "5×5 LED display", kind: "led", x: 18, y: 11.4, w: 16.4, h: 16.4, note: "25 red LEDs that show letters, numbers and small pictures. They can also sense light." },
      { id: "btn-a", label: "Button A", kind: "button", x: 5, y: 16, w: 6, h: 6, note: "A momentary button on GPIO; read with input or an event." },
      { id: "btn-b", label: "Button B", kind: "button", x: 41, y: 16, w: 6, h: 6, note: "The second button. Press both for a third event." },
      { id: "edge", label: "Edge connector", kind: "pins", x: 0, y: 34, w: 52, h: 8, note: "Five big rings for crocodile clips (0, 1, 2, 3V, GND) and 20 small pads between them for an edge-connector breakout." },
      { id: "usb", label: "Micro-USB", kind: "port", x: 22, y: -1, w: 7.5, h: 5.5, note: "Shows up as a drive; drop a .hex file on it to program." },
      { id: "batt", label: "Battery connector", kind: "connector", x: 10, y: 1.5, w: 6, h: 4.5, note: "JST socket for a 2×AAA pack." },
      { id: "mcu", label: "nRF52833", kind: "chip", x: 37, y: 4, w: 5, h: 5, note: "64 MHz Cortex-M4 with Bluetooth and the 2.4 GHz radio used for micro:bit-to-micro:bit messages." },
      { id: "mic", label: "Microphone", kind: "sensor", x: 24.5, y: 4.6, w: 3, h: 3, note: "Measures loudness; an LED beside it lights while it listens." },
      { id: "logo", label: "Touch logo", kind: "sensor", x: 23.5, y: 30, w: 5, h: 2.5, note: "A capacitive touch input." },
    ],
    pins: [
      { name: "P0 / P1 / P2", role: "analog", note: "Large rings; digital or analog, with crocodile clips" },
      { name: "P3–P16", role: "digital", note: "Small edge pads; some are shared with the display" },
      { name: "P19 / P20", role: "i2c", note: "SCL and SDA, shared with the onboard accelerometer" },
      { name: "P13 / P14 / P15", role: "spi", note: "SCK, MISO, MOSI" },
      { name: "3V", role: "power", note: "3.3 V out, about 90 mA spare" },
      { name: "GND", role: "ground", note: "Ground ring" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "5 V, drag-and-drop", kind: "connector", col: 0, row: 0, note: "Power and programming." },
        { id: "batt", label: "Battery", sub: "2 × AAA", kind: "connector", col: 0, row: 2, note: "Runs it away from the computer." },
        { id: "iface", label: "Interface chip", sub: "KL27", kind: "ic", col: 1, row: 0, note: "Presents the board as a USB drive and programs the main chip." },
        { id: "reg", label: "3.3 V regulator", kind: "regulator", col: 1, row: 2, note: "Everything runs at 3.3 V." },
        { id: "mcu", label: "nRF52833", sub: "64 MHz, BLE", kind: "mcu", col: 2, row: 1, note: "Runs your program and the radio." },
        { id: "display", label: "LED display", sub: "5 × 5", kind: "actuator", col: 3, row: 0, note: "Scanned row by row, faster than the eye can see." },
        { id: "inputs", label: "Buttons + sensors", sub: "A, B, touch, motion", kind: "sensor", col: 3, row: 1, note: "Accelerometer and compass over I2C; microphone and buttons on GPIO." },
        { id: "edge", label: "Edge connector", sub: "P0–P20", kind: "pin", col: 3, row: 2, note: "Your pins, at 3.3 V." },
      ],
      links: [
        { from: "usb", to: "iface", kind: "data", label: "USB" },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "batt", to: "reg", kind: "power", label: "3 V" },
        { from: "iface", to: "mcu", kind: "data", label: "SWD" },
        { from: "reg", to: "mcu", kind: "power", label: "3.3 V" },
        { from: "mcu", to: "display", kind: "signal" },
        { from: "inputs", to: "mcu", kind: "signal" },
        { from: "mcu", to: "edge", kind: "signal", both: true },
      ],
      steps: [
        "USB or the battery pack supplies power, regulated to 3.3 V.",
        "The interface chip shows the board as a USB drive and writes the .hex you drop on it into the nRF52833.",
        "The nRF52833 runs your program, scans the LED display, reads the buttons and sensors, and talks over Bluetooth or micro:bit radio.",
        "The edge connector carries the same GPIO out to crocodile clips or a breakout board.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V" },
      { label: "Clock", value: "64 MHz Cortex-M4" },
      { label: "Built in", value: "25 LEDs, 2 buttons, motion, compass, mic, speaker, radio" },
      { label: "Pins", value: "3 rings + 17 edge pads" },
      { label: "Languages", value: "MakeCode blocks, Python, C++" },
      { label: "Size", value: "52 × 42 mm" },
    ],
    animate: { lit: ["led-6", "led-8", "led-12", "led-16", "led-18"] },
    experiment: { title: "Dice", idea: "Show a random number on the display when the board is shaken, using the accelerometer." },
    tags: ["microbit", "micro:bit", "bbc", "classroom", "nrf52", "3.3v", "board", "education"],
  },

  {
    id: "teensy",
    name: "Teensy 4.1",
    aka: ["Teensy", "i.MX RT1062 board"],
    group: "boards",
    rank: 9,
    summary: "The fastest Arduino-compatible board by a wide margin: a 600 MHz ARM Cortex-M7 in a small package, with an SD slot, Ethernet pads and audio-grade peripherals.",
    size: { w: 61, h: 18, d: 6.6 },
    solids: [
      pcb(61, 18, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      ...Array.from({ length: 24 }, (_, i) => ({ kind: "disc", cx: 1.27 + i * 2.54, cy: 1.27, r: 0.8, color: MATERIAL.gold }) as Solid),
      ...Array.from({ length: 24 }, (_, i) => ({ kind: "disc", cx: 1.27 + i * 2.54, cy: 16.73, r: 0.8, color: MATERIAL.gold }) as Solid),
      ...Array.from({ length: 5 }, (_, i) => ({ kind: "disc", cx: 59.7, cy: 4 + i * 2.54, r: 0.8, color: MATERIAL.gold }) as Solid),
      microUsb(-1.3, 6.25),
      chip(22, 3, 12, 12, "i.MX RT1062", 1.2, "mcu"),
      chip(38, 5.5, 5, 5, "FLASH", 0.9),
      { kind: "box", x: 48, y: 3, w: 12, h: 12, d: 2, z: 1.6, top: "linear-gradient(180deg,#d7dadf,#b9bdc3)", side: MATERIAL.steelSide, fill: MATERIAL.steel, radius: 0.5, label: { text: "microSD", size: 1.4, color: "#4b5059" } },
      ...tactileButton(8, 4, 3.5, "program"),
      smdLed(14, 12, "#f97316", "led"),
      { kind: "box", x: 8, y: 11, w: 4, h: 2.5, d: 1, z: 1.6, top: MATERIAL.ic, side: MATERIAL.icSide },
      silk(13, 15.2, "13", 0.9),
      silk(7, 9.4, "PROG", 0.8),
      silk(22, 16, "Teensy 4.1", 1.3, MATERIAL.silk, { weight: 700 }),
    ],
    features: [
      { id: "mcu", label: "i.MX RT1062", kind: "chip", x: 22, y: 3, w: 12, h: 12, note: "600 MHz Cortex-M7 with 1 MB RAM, floating-point hardware and a lot of peripherals." },
      { id: "top-pins", label: "Pins, top row", kind: "pins", x: 0, y: 0.4, w: 61, h: 1.8, note: "GND, 0–23 on this edge: digital, PWM, serial, I2C, SPI, CAN." },
      { id: "bottom-pins", label: "Pins, bottom row", kind: "pins", x: 0, y: 15.8, w: 61, h: 1.8, note: "VIN, 3.3 V, 24–41, including the analog inputs A0–A17." },
      { id: "usb", label: "Micro-USB", kind: "port", x: -1.3, y: 6.25, w: 7.5, h: 5.5, note: "Programming with the Teensy loader, serial, MIDI, audio or keyboard emulation." },
      { id: "sd", label: "microSD slot", kind: "port", x: 48, y: 3, w: 12, h: 12, note: "Built-in SD card slot on a fast interface; log data or play audio files." },
      { id: "flash", label: "8 MB flash", kind: "chip", x: 38, y: 5.5, w: 5, h: 5, note: "Program storage." },
      { id: "program", label: "Program button", kind: "button", x: 8, y: 4, w: 3.5, h: 3.5, note: "Press to put the board in programming mode." },
      { id: "led", label: "Pin 13 LED", kind: "led", x: 13.5, y: 11.4, w: 2.6, h: 1.8, note: "Orange; on pin 13." },
      { id: "eth", label: "Ethernet and PSRAM pads", kind: "pins", x: 58.5, y: 3, w: 2.5, h: 12, note: "Pads for an Ethernet magjack kit and optional extra RAM chips underneath." },
    ],
    pins: [
      { name: "0–41", role: "digital", note: "42 digital pins at 3.3 V, not 5 V tolerant; 35 with PWM" },
      { name: "A0–A17", role: "analog", note: "18 analog inputs, 12-bit" },
      { name: "0 / 1, 7 / 8, 14 / 15 …", role: "uart", note: "Eight hardware serial ports" },
      { name: "18 / 19", role: "i2c", note: "SDA0 and SCL0, plus two more I2C buses" },
      { name: "11 / 12 / 13", role: "spi", note: "MOSI, MISO, SCK, plus two more SPI buses" },
      { name: "22 / 23", role: "data", note: "CAN bus" },
      { name: "VIN", role: "power", note: "3.6–5.5 V in" },
      { name: "3.3V", role: "power", note: "3.3 V out, 250 mA" },
      { name: "GND", role: "ground", note: "Ground" },
    ],
    circuit: {
      blocks: [
        { id: "usb", label: "Micro-USB", sub: "480 Mbit/s", kind: "connector", col: 0, row: 0, note: "USB straight into the chip; it can be a serial port, MIDI device or sound card." },
        { id: "reg", label: "3.3 V regulator", kind: "regulator", col: 1, row: 1, note: "From VIN or USB." },
        { id: "mcu", label: "i.MX RT1062", sub: "600 MHz, M7", kind: "mcu", col: 2, row: 1, note: "Runs code from flash through a cache at full speed." },
        { id: "flash", label: "Flash", sub: "8 MB", kind: "ic", col: 2, row: 2, note: "Program storage." },
        { id: "sd", label: "microSD", sub: "SDIO", kind: "connector", col: 3, row: 0, note: "Fast storage for logs and audio." },
        { id: "gpio", label: "GPIO", sub: "42 × 3.3 V", kind: "pin", col: 3, row: 1, note: "Digital, PWM, 8 UART, 3 SPI, 3 I2C, CAN." },
        { id: "adc", label: "Analog inputs", sub: "A0–A17", kind: "pin", col: 3, row: 2, note: "12-bit, 0–3.3 V." },
      ],
      links: [
        { from: "usb", to: "mcu", kind: "data", label: "USB", both: true },
        { from: "usb", to: "reg", kind: "power", label: "5 V" },
        { from: "reg", to: "mcu", kind: "power", label: "3.3 V" },
        { from: "mcu", to: "flash", kind: "data", both: true },
        { from: "mcu", to: "sd", kind: "data", both: true },
        { from: "mcu", to: "gpio", kind: "signal", both: true },
        { from: "adc", to: "mcu", kind: "analog" },
      ],
      steps: [
        "USB or VIN is regulated to 3.3 V; the chip itself is not 5 V tolerant.",
        "The i.MX RT1062 talks USB natively and runs your code at 600 MHz from the 8 MB flash.",
        "42 pins carry GPIO, 18 analog inputs and eight serial ports, and the SD slot gives fast storage.",
      ],
    },
    facts: [
      { label: "Logic", value: "3.3 V (not 5 V tolerant)" },
      { label: "Clock", value: "600 MHz Cortex-M7" },
      { label: "Memory", value: "8 MB flash, 1 MB RAM" },
      { label: "Pins", value: "42 digital (35 PWM), 18 analog" },
      { label: "Extras", value: "microSD, 8 UART, CAN, Ethernet pads" },
      { label: "Size", value: "61 × 18 mm" },
    ],
    animate: { lit: ["led"] },
    experiment: { title: "Audio from an SD card", idea: "Play a WAV file from the SD slot through the audio library, then add a volume knob on A0." },
    tags: ["teensy", "pjrc", "arm", "cortex-m7", "fast", "audio", "3.3v", "board", "mcu"],
  },
];
