import { MATERIAL, chip, maleHeader, mountHole, pcb, silk, wire } from "../build";
import type { PartModel } from "../types";

export const DISPLAYS: PartModel[] = [
  {
    id: "lcd-16x2",
    name: "LCD 16×2 (I2C)",
    aka: ["1602 LCD", "HD44780 display", "character LCD"],
    group: "displays",
    rank: 1,
    summary: "Two lines of sixteen characters, readable from across the room, driven over two wires thanks to the I2C backpack on the back. The classic readout.",
    size: { w: 80, h: 36, d: 10.8 },
    solids: [
      pcb(80, 36, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      { kind: "box", id: "bezel", x: 4.4, y: 5.9, w: 71.2, h: 24.2, d: 7, z: 1.6, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.6 },
      { kind: "box", id: "glass", x: 7.2, y: 9.2, w: 65.6, h: 17.6, d: 0.6, z: 8.6, top: "#a9d33c", side: "#7ea32a", glow: "#c6ec5a", radius: 0.3 },
      silk(10, 15.6, "Hello, Kiungo!", 3.6, "#1f2a10", { z: 9.2, weight: 700 }),
      silk(10, 23.4, "Temp: 24.5 C", 3.6, "#1f2a10", { z: 9.2, weight: 700 }),
      { kind: "pins", x: 6.2, y: 0.9, count: 16, pitch: 2.54, dir: "x", len: 5, z: 1.6 },
      { kind: "box", x: -2.6, y: 12.4, w: 2.6, h: 10.3, d: 2.5, z: -2, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.3 },
      ...[13.7, 16.24, 18.78, 21.32].map((y) => wire(-9, y - 0.32, 6.6, 0.64, MATERIAL.tin, -1.3)),
      mountHole(2.5, 2.5),
      mountHole(77.5, 2.5),
      mountHole(2.5, 33.5),
      mountHole(77.5, 33.5),
      silk(40, 33.6, "LCD1602", 1.4, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      silk(6.6, 5.2, "1", 1, MATERIAL.silk),
      silk(44.3, 5.2, "16", 1, MATERIAL.silk),
      silk(1.8, 11.4, "GND VCC SDA SCL", 0.8, MATERIAL.silk, { rotate: -90, anchor: "end" }),
    ],
    features: [
      { id: "glass", label: "16 × 2 characters", kind: "other", x: 7.2, y: 9.2, w: 65.6, h: 17.6, note: "Two rows of sixteen 5 × 8 dot cells. The HD44780 controller remembers what you wrote; you only send changes." },
      { id: "backlight", label: "LED backlight", kind: "led", x: 4.4, y: 5.9, w: 71.2, h: 24.2, note: "An LED lights the glass from behind; the backpack's jumper switches it off." },
      { id: "header", label: "16 HD44780 pins", kind: "pins", x: 6.2, y: 0.9, w: 40.6, h: 2.54, note: "Used by the I2C backpack soldered to the back; you don't wire these yourself." },
      { id: "i2c", label: "I2C backpack pins", kind: "pins", x: -9, y: 12.4, w: 9, h: 10.3, note: "GND, VCC, SDA, SCL on a right-angle header at the edge. Four wires instead of twelve." },
      { id: "holes", label: "Mounting holes (×4)", kind: "mechanical", x: 1, y: 1, w: 3, h: 3, note: "M2.5 at each corner." },
    ],
    pins: [
      { name: "GND", role: "ground", note: "Ground" },
      { name: "VCC", role: "power", note: "5 V, about 25 mA with the backlight on" },
      { name: "SDA", role: "data", note: "I2C data; A4 on an Uno" },
      { name: "SCL", role: "clock", note: "I2C clock; A5 on an Uno" },
    ],
    circuit: {
      blocks: [
        { id: "i2c", label: "SDA / SCL", sub: "I2C 0x27 or 0x3F", kind: "pin", col: 0, row: 0, note: "Two wires carry every character." },
        { id: "pcf", label: "PCF8574", sub: "I/O expander", kind: "ic", col: 1, row: 0, note: "The chip on the backpack: turns I2C into eight pins for the LCD." },
        { id: "hd", label: "HD44780", sub: "controller + DDRAM", kind: "ic", col: 2, row: 0, note: "Holds the text and a built-in font; refreshes the glass on its own." },
        { id: "glass", label: "Glass", sub: "16 × 2 × 5 × 8 dots", kind: "display", col: 3, row: 0, note: "Liquid crystal that goes dark where it's driven." },
        { id: "bl", label: "Backlight LED", kind: "actuator", col: 3, row: 1, note: "Lights the glass from behind." },
        { id: "pot", label: "Contrast pot", sub: "V0", kind: "passive", col: 1, row: 1, note: "On the backpack. Blank screen or black boxes: turn this." },
        { id: "vcc", label: "VCC 5 V", kind: "power", col: 0, row: 1, note: "The backlight is most of the current." },
        { id: "gnd", label: "GND", kind: "ground", col: 0, row: 2, note: "Ground." },
      ],
      links: [
        { from: "i2c", to: "pcf", kind: "data", both: true },
        { from: "pcf", to: "hd", kind: "data", label: "4-bit bus" },
        { from: "hd", to: "glass", kind: "signal", label: "segment drive" },
        { from: "pcf", to: "bl", kind: "signal", label: "backlight" },
        { from: "pot", to: "hd", kind: "analog", label: "contrast" },
        { from: "vcc", to: "pcf", kind: "power" },
        { from: "pcf", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Your board sends characters over I2C to the PCF8574 backpack, which fans them out onto the LCD's 4-bit data bus plus RS and E.",
        "The HD44780 keeps the text in its own memory and refreshes the glass itself: each cell is a 5 × 8 grid of dots.",
        "The glass only blocks light; the backlight LED shines through from behind. The contrast pot sets the dot voltage V0: turn it if you see nothing, or only black boxes.",
        "Address 0x27 (0x3F on some backpacks); run an I2C scanner if lcd.print shows nothing.",
      ],
    },
    facts: [
      { label: "Characters", value: "16 × 2" },
      { label: "Controller", value: "HD44780" },
      { label: "Interface", value: "I2C (PCF8574 backpack)" },
      { label: "Supply", value: "5 V, ~25 mA" },
      { label: "Address", value: "0x27 / 0x3F" },
      { label: "Size", value: "80 × 36 mm" },
    ],
    animate: { lit: ["glass"] },
    experiment: { title: "Live readout", idea: "Print 'Hello' and a counter on the second row, then swap in a sensor reading and a custom degree symbol." },
    tags: ["lcd", "1602", "16x2", "hd44780", "i2c", "display", "text", "screen"],
  },

  {
    id: "oled-ssd1306",
    name: "OLED 0.96″ (SSD1306)",
    aka: ["0.96 inch OLED", "128×64 OLED", "SSD1306 display"],
    group: "displays",
    rank: 2,
    summary: "A crisp little screen where every pixel makes its own light. Text, graphs and icons at 128 × 64, over the same two I2C wires.",
    size: { w: 27, h: 27.5, d: 10.1 },
    solids: [
      pcb(27, 27.5, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "box", id: "glass", x: 0.2, y: 4.5, w: 26.6, h: 19.3, d: 1.4, z: 1.6, top: "#0e1116", side: "#05070a", radius: 0.3 },
      { kind: "box", id: "pixels", x: 2.5, y: 8.6, w: 21.7, h: 10.9, d: 0.1, z: 3, top: "#0b0d12", side: "#0b0d12", glow: "#e0f2fe", radius: 0.1 },
      silk(13.3, 15.4, "Kiungo", 4.2, "#e0f2fe", { anchor: "middle", z: 3.2, weight: 800 }),
      silk(13.3, 18.2, "ready  12:04", 1.7, "#93c5fd", { anchor: "middle", z: 3.2 }),
      { kind: "box", x: 6, y: 23.8, w: 15, h: 2.6, d: 0.3, z: 1.6, top: MATERIAL.gold, side: "#b08a3a", radius: 0.2 },
      ...maleHeader(8.42, 0.4, 4, "x", 1, false),
      chip(21.5, 1.2, 2.5, 1.4, undefined, 0.9),
      chip(3, 1.2, 2.5, 1.4, undefined, 0.9),
      ...["GND", "VCC", "SCL", "SDA"].map((name, i) => silk(9.69 + i * 2.54, 3.9, name, 0.8, MATERIAL.silk, { anchor: "middle" })),
      silk(13.5, 26.6, "0.96 OLED  I2C", 1.1, MATERIAL.silk, { anchor: "middle" }),
      mountHole(2, 2, 1.1),
      mountHole(25, 2, 1.1),
      mountHole(2, 25.5, 1.1),
      mountHole(25, 25.5, 1.1),
    ],
    features: [
      { id: "pixels", label: "128 × 64 pixels", kind: "other", x: 2.5, y: 8.6, w: 21.7, h: 10.9, note: "Each pixel is its own tiny OLED; black pixels are simply off, which is why the contrast is so deep." },
      { id: "glass", label: "Glass", kind: "other", x: 0.2, y: 4.5, w: 26.6, h: 19.3, note: "The SSD1306 driver chip is bonded onto the glass itself, under the dark border." },
      { id: "header", label: "GND, VCC, SCL, SDA", kind: "pins", x: 8.42, y: 0.4, w: 10.16, h: 2.54, note: "Check the order printed on yours: some boards swap GND and VCC." },
      { id: "flex", label: "Flex tail", kind: "connector", x: 6, y: 23.8, w: 15, h: 2.6, note: "Carries the thirty-odd lines from the glass to the board. Don't bend it." },
      { id: "holes", label: "Mounting holes", kind: "mechanical", x: 0.5, y: 0.5, w: 3, h: 3, note: "Four M2 holes, one in each corner of the board." },
    ],
    pins: [
      { name: "GND", role: "ground", note: "Ground" },
      { name: "VCC", role: "power", note: "3.3–5 V" },
      { name: "SCL", role: "clock", note: "I2C clock" },
      { name: "SDA", role: "data", note: "I2C data; address 0x3C" },
    ],
    circuit: {
      blocks: [
        { id: "i2c", label: "SDA / SCL", sub: "I2C 0x3C, 400 kHz", kind: "pin", col: 0, row: 0, note: "A whole frame is 1 KB; at 400 kHz that's ~30 ms." },
        { id: "ssd", label: "SSD1306", sub: "1 KB frame buffer", kind: "ic", col: 1, row: 0, note: "Keeps the picture and scans it onto the pixels." },
        { id: "pump", label: "Charge pump", sub: "makes 7.5 V", kind: "regulator", col: 1, row: 1, note: "OLEDs need more than 3.3 V; this boosts it on chip." },
        { id: "pixels", label: "128 × 64 OLEDs", kind: "display", col: 2, row: 0, note: "Organic LEDs, one per pixel." },
        { id: "light", label: "Light", sub: "self-emitting", kind: "world", col: 3, row: 0, note: "No backlight: lit pixels glow, dark ones are off." },
        { id: "vcc", label: "VCC 3.3–5 V", kind: "power", col: 0, row: 1, note: "About 20 mA with half the pixels lit." },
      ],
      links: [
        { from: "i2c", to: "ssd", kind: "data", both: true },
        { from: "ssd", to: "pixels", kind: "signal", label: "row/column scan" },
        { from: "pixels", to: "light", kind: "light" },
        { from: "vcc", to: "pump", kind: "power" },
        { from: "pump", to: "pixels", kind: "power", label: "7.5 V" },
        { from: "vcc", to: "ssd", kind: "power" },
      ],
      steps: [
        "Your board draws into a 1 KB buffer in RAM (128 × 64 bits) and ships it over I2C to the SSD1306 at 0x3C.",
        "An internal charge pump boosts 3.3 V to about 7.5 V for the organic LEDs.",
        "The driver scans rows and columns; every lit pixel emits its own light, so there is no backlight and black is truly off.",
        "Leave a static image for days and it can burn in; keep text moving or dim it.",
      ],
    },
    facts: [
      { label: "Resolution", value: "128 × 64" },
      { label: "Diagonal", value: "0.96 in (21.7 × 10.9 mm)" },
      { label: "Interface", value: "I2C (SPI variants exist)" },
      { label: "Supply", value: "3.3–5 V, ~20 mA" },
      { label: "Colour", value: "Mono: white, blue or yellow/blue" },
      { label: "Size", value: "27 × 27 mm" },
    ],
    animate: { lit: ["pixels"] },
    experiment: { title: "Dashboard", idea: "Show a sensor value large in the middle with a bar graph underneath; refresh ten times a second." },
    tags: ["oled", "ssd1306", "i2c", "display", "128x64", "screen", "graphics"],
  },

  {
    id: "tft-display",
    name: "TFT 1.8″ colour (ST7735)",
    aka: ["1.8 inch TFT", "ST7735 display", "SPI colour screen"],
    group: "displays",
    rank: 3,
    summary: "A proper colour screen, 160 × 128 pixels, with a microSD slot on the back. Gauges, photos, menus, over SPI.",
    size: { w: 34, h: 56, d: 10.1 },
    solids: [
      pcb(34, 56, MATERIAL.pcbRed, MATERIAL.pcbRedEdge),
      { kind: "box", id: "glass", x: 2.5, y: 2.5, w: 29, h: 40, d: 2, z: 1.6, top: MATERIAL.plasticBlack, side: "#0a0b0c", radius: 0.6 },
      { kind: "box", id: "pixels", x: 3.5, y: 5, w: 27, h: 35, d: 0.1, z: 3.6, top: "linear-gradient(160deg,#1d4ed8,#7c3aed 55%,#f472b6)", side: "#4338ca", fill: "#4338ca", glow: "#c4b5fd", radius: 0.2 },
      silk(17, 21.5, "Kiungo", 6, "#ffffff", { anchor: "middle", z: 3.8, weight: 800 }),
      silk(17, 26.5, "160 × 128", 2.2, "#ede9fe", { anchor: "middle", z: 3.8 }),
      { kind: "path", d: "M 6 31 h 22 M 6 34 h 15 M 6 37 h 18", color: "#ffffff", width: 0.9, z: 3.8 },
      { kind: "box", x: 8, y: 43, w: 18, h: 2.5, d: 0.3, z: 1.6, top: MATERIAL.gold, side: "#b08a3a", radius: 0.2 },
      ...maleHeader(6.84, 52, 8, "x", 1, false),
      ...["VCC", "GND", "CS", "RST", "A0", "SDA", "SCK", "LED"].map((name, i) => silk(6.84 + 1.27 + i * 2.54 + 0.3, 51.3, name, 0.7, MATERIAL.silk, { rotate: -90 })),
      silk(17, 47.8, "1.8 TFT SPI", 1.3, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      mountHole(2.2, 48.8, 1.2),
      mountHole(31.8, 48.8, 1.2),
    ],
    features: [
      { id: "pixels", label: "160 × 128 colour pixels", kind: "other", x: 3.5, y: 5, w: 27, h: 35, note: "An LCD with an LED backlight behind it; 16-bit colour (65 k shades) per pixel." },
      { id: "header", label: "VCC, GND, CS, RST, A0, SDA, SCK, LED", kind: "pins", x: 6.84, y: 52, w: 20.3, h: 2.54, note: "SPI: SDA is MOSI, SCK the clock, A0 (DC) picks command or data, LED feeds the backlight." },
      { id: "flex", label: "Flex tail", kind: "connector", x: 8, y: 43, w: 18, h: 2.5, note: "Connects the glass to the board; the ST7735 driver sits on the glass end of it." },
      { id: "sd", label: "microSD slot (on the back)", kind: "other", x: 2.5, y: 2.5, w: 29, h: 40, note: "Behind the screen is a microSD holder on the same SPI bus, with its own chip-select pin on most boards." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3–5 V (a regulator on most boards)" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "CS", role: "digital", note: "SPI chip select" },
      { name: "RST", role: "digital", note: "Reset" },
      { name: "A0 (DC)", role: "digital", note: "Data / command select" },
      { name: "SDA (MOSI)", role: "spi", note: "SPI data in" },
      { name: "SCK", role: "spi", note: "SPI clock" },
      { name: "LED", role: "power", note: "Backlight: 3.3 V, or a PWM pin to dim" },
    ],
    circuit: {
      blocks: [
        { id: "spi", label: "SPI", sub: "MOSI, SCK, CS, DC", kind: "pin", col: 0, row: 0, note: "Hardware SPI pins; software SPI works but crawls." },
        { id: "st", label: "ST7735", sub: "controller, 40 KB RAM", kind: "ic", col: 1, row: 0, note: "Holds the whole frame so your board doesn't have to." },
        { id: "lcd", label: "LCD panel", sub: "160 × 128 × RGB", kind: "display", col: 2, row: 0, note: "Each pixel is three tiny shutters with colour filters." },
        { id: "light", label: "Colour image", kind: "world", col: 3, row: 0, note: "What you see." },
        { id: "bl", label: "Backlight LEDs", kind: "actuator", col: 2, row: 1, note: "White LEDs behind the panel." },
        { id: "led", label: "LED pin", sub: "3.3 V or PWM", kind: "pin", col: 1, row: 1, note: "Switch or dim the backlight." },
        { id: "vcc", label: "VCC", kind: "power", col: 0, row: 1, note: "About 50 mA, mostly backlight." },
        { id: "sd", label: "microSD slot", sub: "same SPI bus", kind: "connector", col: 1, row: 2, note: "Images and logs, one CS pin away." },
      ],
      links: [
        { from: "spi", to: "st", kind: "data", label: "commands + pixels" },
        { from: "st", to: "lcd", kind: "signal", label: "drives rows/cols" },
        { from: "lcd", to: "light", kind: "light" },
        { from: "bl", to: "lcd", kind: "light", label: "backlight" },
        { from: "led", to: "bl", kind: "power" },
        { from: "vcc", to: "st", kind: "power" },
        { from: "spi", to: "sd", kind: "data", both: true },
      ],
      steps: [
        "Over SPI your board sends commands and 16-bit pixel data; the ST7735 holds the whole frame in its own 40 KB RAM.",
        "The controller drives the LCD's rows and columns; each pixel is a tiny shutter with red, green and blue filters.",
        "White backlight LEDs shine through from behind; the LED pin switches or dims them.",
        "The microSD slot on the back shares the SPI bus: store images or log data and show it on screen. Use 3.3 V logic or a level shifter.",
      ],
    },
    facts: [
      { label: "Resolution", value: "160 × 128, 65 k colours" },
      { label: "Diagonal", value: "1.8 in" },
      { label: "Controller", value: "ST7735" },
      { label: "Interface", value: "SPI + backlight pin" },
      { label: "Supply", value: "3.3–5 V, ~50 mA" },
      { label: "Extras", value: "microSD slot" },
    ],
    animate: { lit: ["pixels"] },
    experiment: { title: "Live gauge", idea: "Draw a round gauge whose needle follows a potentiometer, then log the values to the microSD card." },
    tags: ["tft", "st7735", "spi", "display", "colour", "color", "screen", "lcd", "graphics"],
  },
];
