import { MATERIAL, chip, dip, led5mm, lyingCylinder, maleHeader, mountHole, pcb, screwTerminal, silk, smdLed, wire } from "../build";
import type { PartModel, Solid } from "../types";

/** A single component leg hanging below z = 0, centred at (cx, cy). */
function leg(cx: number, cy: number, len: number): Solid {
  return { kind: "pins", x: cx - 1.27, y: cy - 1.27, count: 1, pitch: 2.54, dir: "x", len: -len, z: 0, size: 0.5 };
}

const TAN = { top: "#b9a67a", side: "#8a7a55" };

export const OUTPUTS: PartModel[] = [
  {
    id: "led",
    name: "LED, 5 mm",
    aka: ["light-emitting diode", "red LED", "indicator LED"],
    group: "outputs",
    rank: 1,
    summary: "The first thing anyone makes a board do. Current goes in the long leg, light comes out the top, and a resistor in series keeps both alive.",
    size: { w: 6, h: 6, d: 8.8 },
    plan: "front",
    solids: [...led5mm(3, 3, "#ff3b3b", "led"), leg(4.27, 3, 13), leg(1.73, 3, 11)],
    features: [
      { id: "dome", label: "Dome", kind: "led", x: 0.5, y: 0, w: 5, h: 2.3, note: "Tinted epoxy that shapes the light into a ~30° beam. The colour comes from the semiconductor inside, not the plastic." },
      { id: "body", label: "Body", kind: "other", x: 0.5, y: 2.3, w: 5, h: 5.5, note: "Inside: a tiny die sitting in the cathode's reflector cup, with a hair-thin wire bond to the anode." },
      { id: "rim", label: "Rim with a flat side", kind: "other", x: 0.1, y: 7.8, w: 5.8, h: 1, note: "The flat edge of the rim marks the cathode (−)." },
      { id: "anode", label: "Anode (+), longer leg", kind: "pin", x: 3.9, y: 8.8, w: 0.8, h: 13, note: "Current enters here. Always through a resistor." },
      { id: "cathode", label: "Cathode (−), shorter leg", kind: "pin", x: 1.3, y: 8.8, w: 0.8, h: 11, note: "Current leaves here, to GND." },
    ],
    pins: [
      { name: "Anode (+)", role: "power", note: "Longer leg. From the pin, through a 220 Ω resistor" },
      { name: "Cathode (−)", role: "ground", note: "Shorter leg, flat side of the rim. To GND" },
    ],
    circuit: {
      blocks: [
        { id: "gpio", label: "Board pin", sub: "HIGH = 5 V", kind: "pin", col: 0, row: 0, note: "Any digital pin; a ~ pin if you want to dim it with PWM." },
        { id: "res", label: "220 Ω resistor", sub: "yours, in series", kind: "passive", col: 1, row: 0, note: "Sets the current: (5 − 2 V) ÷ 220 Ω ≈ 14 mA. Without it the LED or the pin burns." },
        { id: "anode", label: "Anode +", kind: "pin", col: 2, row: 0, note: "The longer leg." },
        { id: "die", label: "LED die", sub: "drops ~2 V", kind: "actuator", col: 3, row: 0, note: "A semiconductor junction; electrons crossing it give off light of one colour." },
        { id: "light", label: "Light", sub: "~20 mA = full bright", kind: "world", col: 3, row: 1, note: "Brightness follows current, not voltage." },
        { id: "cathode", label: "Cathode −", kind: "pin", col: 2, row: 1, note: "The shorter leg, on the flat side." },
        { id: "gnd", label: "GND", kind: "ground", col: 1, row: 1, note: "Back to the board's ground." },
      ],
      links: [
        { from: "gpio", to: "res", kind: "power", label: "5 V" },
        { from: "res", to: "anode", kind: "power", label: "~14 mA" },
        { from: "anode", to: "die", kind: "power" },
        { from: "die", to: "light", kind: "light" },
        { from: "die", to: "cathode", kind: "power" },
        { from: "cathode", to: "gnd", kind: "ground" },
      ],
      steps: [
        "The pin goes HIGH (5 V). The resistor sets the current: (5 − 2 V) ÷ 220 Ω ≈ 14 mA. Never skip it; without it the LED or the pin burns.",
        "Current enters at the anode, crosses the semiconductor junction, and electrons give up their energy as light of one colour.",
        "It leaves by the cathode to GND. Reverse it and nothing lights: an LED is a one-way valve.",
        "Dim it with PWM: analogWrite switches it on and off faster than your eye can follow.",
      ],
    },
    facts: [
      { label: "Forward voltage", value: "~2 V red, ~3.2 V blue/white" },
      { label: "Current", value: "20 mA max" },
      { label: "Resistor", value: "220–330 Ω at 5 V" },
      { label: "Beam", value: "~30°" },
      { label: "Polarity", value: "Long leg = +" },
      { label: "Size", value: "Ø5 mm" },
    ],
    animate: { lit: ["led", "led-body"] },
    experiment: { title: "Blink, then breathe", idea: "Blink it once a second, then fade it up and down with analogWrite on a ~ pin." },
    tags: ["led", "light", "diode", "blink", "5mm", "indicator", "output"],
  },

  {
    id: "rgb-led",
    name: "RGB LED, 5 mm",
    aka: ["tri-colour LED", "common-cathode LED", "colour LED"],
    group: "outputs",
    rank: 2,
    summary: "Three LEDs in one clear dome with a shared leg. Three PWM pins and you can mix any colour you can name.",
    size: { w: 9, h: 6, d: 8.8 },
    plan: "front",
    solids: [
      { kind: "cyl", cx: 4.5, cy: 3, r: 2.9, d: 1, z: 0, top: "#d9dde2", side: "#aeb3ba", segments: 16 },
      { kind: "cyl", id: "rgb-body", cx: 4.5, cy: 3, r: 2.5, d: 5.5, z: 1, top: "#e3e9ef", side: "#c5cbd2", segments: 16, glow: "#d946ef" },
      { kind: "dome", id: "rgb", cx: 4.5, cy: 3, r: 2.5, d: 2.3, z: 6.5, color: "#e3e9ef", glow: "#d946ef", clear: true },
      leg(0.69, 3, 11),
      leg(3.23, 3, 14),
      leg(5.77, 3, 11),
      leg(8.31, 3, 11),
    ],
    features: [
      { id: "dome", label: "Clear dome", kind: "led", x: 2, y: 0, w: 5, h: 2.3, note: "Three dies inside: red, green and blue. Mix their brightness for any colour." },
      { id: "body", label: "Body", kind: "other", x: 2, y: 2.3, w: 5, h: 5.5, note: "Water-clear so the three colours blend; look closely while it's lit and you can see the three dots." },
      { id: "r", label: "Red (+)", kind: "pin", x: 0.3, y: 8.8, w: 0.8, h: 11, note: "Red anode, through its own 220 Ω resistor." },
      { id: "c", label: "Common cathode (−), longest", kind: "pin", x: 2.8, y: 8.8, w: 0.8, h: 14, note: "Shared by all three; to GND. On common-anode parts this leg goes to 5 V instead." },
      { id: "g", label: "Green (+)", kind: "pin", x: 5.4, y: 8.8, w: 0.8, h: 11, note: "Green anode, through 220 Ω." },
      { id: "b", label: "Blue (+)", kind: "pin", x: 7.9, y: 8.8, w: 0.8, h: 11, note: "Blue anode, through 220 Ω." },
    ],
    pins: [
      { name: "R", role: "power", note: "Red anode, through 220 Ω to a ~ pin" },
      { name: "GND", role: "ground", note: "Common cathode, the longest leg" },
      { name: "G", role: "power", note: "Green anode, through 220 Ω to a ~ pin" },
      { name: "B", role: "power", note: "Blue anode, through 220 Ω to a ~ pin" },
    ],
    circuit: {
      blocks: [
        { id: "pwm", label: "PWM pins ×3", sub: "~9, ~10, ~11", kind: "pin", col: 0, row: 0, note: "One PWM output per colour." },
        { id: "res", label: "3 × 220 Ω", sub: "yours, one per colour", kind: "passive", col: 1, row: 0, note: "Each die needs its own resistor; they must not share one." },
        { id: "dies", label: "R, G, B dies", sub: "2.0 / 3.2 / 3.2 V", kind: "actuator", col: 2, row: 0, note: "Three separate junctions under one dome." },
        { id: "light", label: "Mixed colour", sub: "16 M combinations", kind: "world", col: 3, row: 0, note: "Your eye adds the three colours together." },
        { id: "cathode", label: "Common cathode", kind: "pin", col: 2, row: 1, note: "The longest leg." },
        { id: "gnd", label: "GND", kind: "ground", col: 1, row: 1, note: "Ground." },
      ],
      links: [
        { from: "pwm", to: "res", kind: "power", label: "3 channels" },
        { from: "res", to: "dies", kind: "power" },
        { from: "dies", to: "light", kind: "light" },
        { from: "dies", to: "cathode", kind: "power" },
        { from: "cathode", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Three separate LEDs share one cathode leg. Each anode gets its own resistor and its own PWM pin.",
        "PWM sets how long each die is on; red + green reads as yellow, all three as white.",
        "Blue and green need ~3.2 V, red ~2 V: with equal resistors red looks brighter at the same duty, so trim it in code.",
        "Common-anode versions are wired the other way: longest leg to 5 V, and pins pull low to light a colour.",
      ],
    },
    facts: [
      { label: "Dies", value: "Red, green, blue" },
      { label: "Forward voltage", value: "2.0 / 3.2 / 3.2 V" },
      { label: "Current", value: "20 mA per die" },
      { label: "Legs", value: "4, longest = common" },
      { label: "Type", value: "Common cathode" },
      { label: "Size", value: "Ø5 mm" },
    ],
    animate: { lit: ["rgb", "rgb-body"] },
    experiment: { title: "Colour fader", idea: "Cycle smoothly around the hue wheel with three analogWrite calls, then map a potentiometer to the hue." },
    tags: ["rgb", "led", "colour", "color", "pwm", "light", "output"],
  },

  {
    id: "buzzer",
    name: "Buzzer, 12 mm active",
    aka: ["piezo buzzer", "beeper", "active buzzer"],
    group: "outputs",
    rank: 3,
    summary: "A black can that beeps the moment you give it voltage. Alarms, confirmations, the sound of a project waking up.",
    size: { w: 12, h: 12, d: 9.5 },
    solids: [
      { kind: "cyl", id: "buzzer", cx: 6, cy: 6, r: 6, d: 9.5, z: 0, top: MATERIAL.plasticBlack, side: "#111214", segments: 28 },
      { kind: "disc", cx: 6, cy: 6, r: 1.3, color: "#000000", z: 9.5 },
      silk(10.1, 3.1, "+", 2, "#eef0f2", { anchor: "middle", z: 9.5, weight: 700 }),
      silk(6, 10.8, "5V ACTIVE", 0.9, "#9aa0a7", { anchor: "middle", z: 9.5 }),
      { kind: "pins", x: -1.6, y: 2.2, count: 2, pitch: 7.6, dir: "x", len: -7, z: 0, size: 0.5 },
    ],
    features: [
      { id: "hole", label: "Sound hole", kind: "other", x: 4.5, y: 4.5, w: 3, h: 3, note: "Sound leaves here. Peel the sticker off a new one or it will be muffled." },
      { id: "plus", label: "+ mark", kind: "pin", x: 9, y: 1.3, w: 2.5, h: 2.5, note: "The positive leg is under this mark (and is the longer one)." },
      { id: "body", label: "Case", kind: "other", x: 0, y: 0, w: 12, h: 12, note: "An active buzzer has its own oscillator inside: give it DC and it sounds at one fixed pitch. A passive buzzer needs a tone signal instead." },
      { id: "legs", label: "Two legs, 7.6 mm apart", kind: "pins", x: 1.5, y: 4.7, w: 9, h: 2.6, note: "+ to a pin (or 5 V through a transistor), − to GND." },
    ],
    pins: [
      { name: "+", role: "power", note: "3.5–5.5 V; most draw under 30 mA, fine straight from a pin" },
      { name: "−", role: "ground", note: "GND" },
    ],
    circuit: {
      blocks: [
        { id: "pin", label: "Board pin", sub: "HIGH = on", kind: "pin", col: 0, row: 0, note: "Digital HIGH starts it; LOW stops it." },
        { id: "osc", label: "Oscillator", sub: "~2.3 kHz, built in", kind: "ic", col: 1, row: 0, note: "A small circuit that makes the tone on its own." },
        { id: "coil", label: "Coil + disc", sub: "electromagnetic", kind: "actuator", col: 2, row: 0, note: "The oscillator drives a coil that snaps a thin metal disc back and forth." },
        { id: "sound", label: "Sound", sub: "~85 dB at 10 cm", kind: "world", col: 3, row: 0, note: "Loud enough to notice from the next room." },
        { id: "gnd", label: "GND", kind: "ground", col: 1, row: 1, note: "Ground." },
      ],
      links: [
        { from: "pin", to: "osc", kind: "power", label: "+" },
        { from: "osc", to: "coil", kind: "signal" },
        { from: "coil", to: "sound", kind: "sound" },
        { from: "coil", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Take + high: the built-in oscillator starts straight away.",
        "It drives a coil that snaps a metal disc back and forth about 2300 times a second.",
        "The disc pushes air through the hole: a steady beep. Pulse the pin for beeps and patterns.",
        "A passive buzzer (no oscillator) needs tone() instead, but it can play any note, so melodies.",
      ],
    },
    facts: [
      { label: "Type", value: "Active (oscillator inside)" },
      { label: "Tone", value: "~2.3 kHz" },
      { label: "Supply", value: "3.5–5.5 V" },
      { label: "Current", value: "~30 mA" },
      { label: "Loudness", value: "~85 dB at 10 cm" },
      { label: "Size", value: "Ø12 × 9.5 mm" },
    ],
    experiment: { title: "Alarm patterns", idea: "Beep twice a second, then make the gap shrink as a distance sensor reads closer." },
    tags: ["buzzer", "sound", "beep", "piezo", "alarm", "speaker", "output"],
  },

  {
    id: "servo",
    name: "Servo, SG90",
    aka: ["micro servo", "9 g servo", "hobby servo"],
    group: "outputs",
    rank: 4,
    summary: "A motor that goes where you tell it: send an angle, it turns there and holds. Robot arms, steering, the lid that opens by itself.",
    size: { w: 40.3, h: 12.2, d: 28.3 },
    solids: [
      { kind: "box", id: "body", x: 12.9, y: 0, w: 22.5, h: 12.2, d: 19.5, top: MATERIAL.plasticBlue, side: "#1f4c96", radius: 0.8 },
      { kind: "box", x: 8, y: 3.6, w: 32.3, h: 5, d: 2.5, z: 10, top: MATERIAL.plasticBlue, side: "#1f4c96", radius: 0.8 },
      { kind: "disc", cx: 10.2, cy: 6.1, r: 1, color: "#0f2b52", z: 12.5 },
      { kind: "disc", cx: 38.1, cy: 6.1, r: 1, color: "#0f2b52", z: 12.5 },
      { kind: "cyl", cx: 19, cy: 6.1, r: 6, d: 3.2, z: 19.5, top: MATERIAL.plasticBlue, side: "#1f4c96", segments: 24 },
      { kind: "cyl", cx: 29, cy: 6.1, r: 3.2, d: 3.2, z: 19.5, top: MATERIAL.plasticBlue, side: "#1f4c96", segments: 16 },
      { kind: "cyl", id: "spline", cx: 19, cy: 6.1, r: 2.4, d: 2.2, z: 22.7, top: MATERIAL.plasticWhite, side: "#c5c9ce", segments: 16 },
      { kind: "box", id: "horn", x: 9.5, y: 3.9, w: 19, h: 4.4, d: 1.6, z: 24.9, top: MATERIAL.plasticWhite, side: "#c5c9ce", radius: 2.2 },
      { kind: "cyl", cx: 19, cy: 6.1, r: 3, d: 1.8, z: 26.5, top: MATERIAL.plasticWhite, side: "#c5c9ce", segments: 16 },
      { kind: "box", x: 0, y: 3.5, w: 5.5, h: 4.2, d: 2.6, z: 1.5, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.4 },
      wire(5.5, 4.3, 7.4, 1, "#7c4a1e", 2),
      wire(5.5, 5.6, 7.4, 1, "#d12d2d", 2),
      wire(5.5, 6.9, 7.4, 1, "#f08a24", 2),
    ],
    features: [
      { id: "horn", label: "Horn", kind: "mechanical", x: 9.5, y: 3.9, w: 19, h: 4.4, note: "Screws onto the splined shaft and swings through about 180°. Fit it after sending 90°, so centre is centre." },
      { id: "spline", label: "Output spline", kind: "mechanical", x: 16.6, y: 3.7, w: 4.8, h: 4.8, note: "21 teeth on the last gear; the position potentiometer turns with it." },
      { id: "ears", label: "Mounting ears", kind: "mechanical", x: 8, y: 3.6, w: 4.9, h: 5, note: "Two tabs with holes, 28 mm apart, for tiny screws or a zip tie." },
      { id: "cable", label: "Lead: brown, red, orange", kind: "connector", x: 0, y: 3.5, w: 12.9, h: 4.2, note: "Brown GND, red 5 V, orange signal. The connector pushes straight onto three header pins." },
      { id: "body", label: "Case", kind: "other", x: 12.9, y: 0, w: 22.5, h: 12.2, note: "Motor, four-stage gear train, potentiometer and control board inside." },
    ],
    pins: [
      { name: "GND (brown)", role: "ground", note: "Ground, shared with the board" },
      { name: "VCC (red)", role: "power", note: "4.8–6 V; a separate supply if more than one servo" },
      { name: "Signal (orange)", role: "pwm", note: "50 Hz pulses: 1 ms = 0°, 1.5 ms = 90°, 2 ms = 180°" },
    ],
    circuit: {
      blocks: [
        { id: "sig", label: "Signal", sub: "1–2 ms pulse, 50 Hz", kind: "pin", col: 0, row: 0, note: "servo.write(angle) makes this pulse for you." },
        { id: "ctl", label: "Control IC", sub: "pulse vs. pot", kind: "ic", col: 1, row: 0, note: "Compares where you asked for with where the pot says it is." },
        { id: "hb", label: "H-bridge", kind: "driver", col: 2, row: 0, note: "Drives the motor either way, hard while the error is big." },
        { id: "motor", label: "DC motor", kind: "actuator", col: 3, row: 0, note: "A small coreless motor." },
        { id: "gears", label: "Gear train", sub: "4 stages", kind: "actuator", col: 3, row: 1, note: "Slows the motor down and multiplies torque." },
        { id: "shaft", label: "Output shaft", sub: "0–180°", kind: "actuator", col: 3, row: 2, note: "What the horn is screwed to." },
        { id: "pot", label: "Position pot", sub: "turns with shaft", kind: "passive", col: 2, row: 2, note: "The feedback: a potentiometer on the output gear." },
        { id: "vcc", label: "VCC 4.8–6 V", kind: "power", col: 0, row: 1, note: "Up to 650 mA when it strains." },
        { id: "gnd", label: "GND", kind: "ground", col: 0, row: 2, note: "Ground." },
      ],
      links: [
        { from: "sig", to: "ctl", kind: "signal" },
        { from: "ctl", to: "hb", kind: "signal", label: "direction" },
        { from: "hb", to: "motor", kind: "power" },
        { from: "motor", to: "gears", kind: "mechanical" },
        { from: "gears", to: "shaft", kind: "mechanical" },
        { from: "shaft", to: "pot", kind: "mechanical" },
        { from: "pot", to: "ctl", kind: "analog", label: "feedback" },
        { from: "vcc", to: "ctl", kind: "power" },
        { from: "ctl", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Every 20 ms your board sends a pulse 1–2 ms long. The control IC turns the pulse length into a target position.",
        "A potentiometer on the output shaft reports where the horn is now. The IC drives the motor through the H-bridge until the two agree.",
        "A four-stage gear train slows the motor and multiplies its torque; the last gear carries the spline and the pot.",
        "Hold the horn and the motor fights back, drawing up to 650 mA: power servos from a separate 5 V supply with a shared GND.",
      ],
    },
    facts: [
      { label: "Travel", value: "180° (±90°)" },
      { label: "Torque", value: "1.8 kg·cm at 4.8 V" },
      { label: "Speed", value: "0.1 s per 60°" },
      { label: "Supply", value: "4.8–6 V" },
      { label: "Stall current", value: "~650 mA" },
      { label: "Size", value: "22.5 × 12.2 × 22.7 mm" },
    ],
    animate: { sweep: ["horn"] },
    experiment: { title: "Sweep and point", idea: "Sweep 0–180° and back, then map a potentiometer (or a distance reading) to the angle." },
    docs: "/docs/hardware-knowledge/servo-motor",
    tags: ["servo", "sg90", "pwm", "angle", "motor", "arm", "output"],
  },

  {
    id: "dc-motor",
    name: "DC gear motor (TT)",
    aka: ["TT motor", "yellow gear motor", "robot wheel motor"],
    group: "outputs",
    rank: 5,
    summary: "The yellow motor under every classroom robot. Spins one way or the other depending on which way the current flows; a gearbox turns speed into push.",
    size: { w: 65, h: 22.5, d: 28.5 },
    solids: [
      { kind: "box", id: "gearbox", x: 0, y: 0, w: 37, h: 22.5, d: 18.5, top: "#f2c21b", side: "#c49a0f", radius: 1 },
      { kind: "disc", cx: 3, cy: 3, r: 0.9, color: MATERIAL.steel, z: 18.5, ring: { color: "#8f949b", width: 0.2 } },
      { kind: "disc", cx: 34, cy: 3, r: 0.9, color: MATERIAL.steel, z: 18.5, ring: { color: "#8f949b", width: 0.2 } },
      { kind: "disc", cx: 3, cy: 19.5, r: 0.9, color: MATERIAL.steel, z: 18.5, ring: { color: "#8f949b", width: 0.2 } },
      { kind: "disc", cx: 34, cy: 19.5, r: 0.9, color: MATERIAL.steel, z: 18.5, ring: { color: "#8f949b", width: 0.2 } },
      silk(22, 12, "1:48", 2.4, "#8a6c0a", { anchor: "middle", z: 18.5, weight: 700 }),
      { kind: "cyl", cx: 11.3, cy: 11.25, r: 3, d: 1, z: 18.5, top: "#d6d9dd", side: "#9aa0a7", segments: 16 },
      { kind: "box", id: "shaft", x: 8.6, y: 9.4, w: 5.4, h: 3.7, d: 9, z: 19.5, top: MATERIAL.plasticWhite, side: "#c5c9ce", radius: 0.8 },
      ...lyingCylinder(37, 11.25, 25, 10, "#c9ccd1", 0, "can"),
      { kind: "box", x: 62, y: 5, w: 1.6, h: 12.5, d: 12, z: 4, top: "#26272b", side: "#111214", radius: 0.4 },
      { kind: "box", x: 63.6, y: 7, w: 1.4, h: 1, d: 2.5, z: 9, top: MATERIAL.copper, side: "#8a5223" },
      { kind: "box", x: 63.6, y: 14.5, w: 1.4, h: 1, d: 2.5, z: 9, top: MATERIAL.copper, side: "#8a5223" },
    ],
    features: [
      { id: "shaft", label: "Double-D shaft", kind: "mechanical", x: 8, y: 8.8, w: 6.6, h: 4.9, note: "Two flats so a wheel can't slip. The same shaft comes out underneath." },
      { id: "gearbox", label: "Gearbox (1:48)", kind: "mechanical", x: 0, y: 0, w: 37, h: 22.5, note: "Plastic spur gears; the ratio trades speed for torque. 1:90 and 1:120 variants exist." },
      { id: "can", label: "Motor can", kind: "other", x: 37, y: 1.25, w: 25, h: 20, note: "A brushed DC motor, 3–6 V, spinning at ~15 000 rpm before the gears slow it down." },
      { id: "terminals", label: "Terminals", kind: "pins", x: 62, y: 5, w: 3, h: 12.5, note: "Solder two wires here. No polarity: swap them to reverse the direction." },
    ],
    pins: [
      { name: "M1", role: "power", note: "Motor terminal; swap M1/M2 to reverse" },
      { name: "M2", role: "power", note: "Motor terminal" },
      { name: "IN1 / IN2", role: "digital", note: "On the H-bridge driver: direction" },
      { name: "EN / PWM", role: "pwm", note: "On the driver: speed" },
    ],
    circuit: {
      blocks: [
        { id: "pwm", label: "PWM + IN1/IN2", sub: "from your board", kind: "pin", col: 0, row: 0, note: "Three pins: speed and direction." },
        { id: "hb", label: "H-bridge", sub: "L298N / TB6612", kind: "driver", col: 1, row: 0, note: "Four switches that route the supply through the motor either way. Your board's pins can't supply this current." },
        { id: "m1", label: "M1", kind: "pin", col: 2, row: 0, note: "One terminal." },
        { id: "rotor", label: "Rotor + brushes", sub: "~15 000 rpm", kind: "actuator", col: 3, row: 0, note: "Coils on the rotor, magnets on the can; the commutator keeps flipping the current so it keeps turning." },
        { id: "m2", label: "M2", kind: "pin", col: 2, row: 1, note: "The other terminal." },
        { id: "gears", label: "Gear train", sub: "1:48", kind: "actuator", col: 3, row: 1, note: "Four plastic gears." },
        { id: "shaft", label: "Shaft", sub: "~300 rpm at 6 V", kind: "actuator", col: 3, row: 2, note: "Slow and strong enough to push a small robot." },
        { id: "supply", label: "Motor supply", sub: "3–6 V, up to 250 mA", kind: "power", col: 0, row: 1, note: "Batteries, not the board's 5 V pin." },
        { id: "gnd", label: "GND", kind: "ground", col: 0, row: 2, note: "Shared between the driver, the batteries and your board." },
      ],
      links: [
        { from: "pwm", to: "hb", kind: "signal" },
        { from: "supply", to: "hb", kind: "power" },
        { from: "hb", to: "m1", kind: "power" },
        { from: "m1", to: "rotor", kind: "power" },
        { from: "rotor", to: "m2", kind: "power" },
        { from: "m2", to: "hb", kind: "power", label: "return" },
        { from: "rotor", to: "gears", kind: "mechanical" },
        { from: "gears", to: "shaft", kind: "mechanical" },
        { from: "hb", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Your board can't power a motor directly (40 mA per pin); an H-bridge driver switches the motor supply instead. IN1/IN2 pick the direction, PWM the speed.",
        "Current flows through the brushes and commutator into the rotor coils; their magnetic field pushes against the magnets and the rotor spins.",
        "A 1:48 plastic gear train slows ~15 000 rpm to ~300 rpm and multiplies the torque; the double-D shaft turns the wheel.",
        "Motors kick noise back into the supply: a 100 nF capacitor across the terminals and a separate battery for the motors keep the board happy.",
      ],
    },
    facts: [
      { label: "Supply", value: "3–6 V" },
      { label: "No-load speed", value: "~200–300 rpm" },
      { label: "Current", value: "150–250 mA (stall ~1 A)" },
      { label: "Ratio", value: "1:48 (1:90, 1:120 variants)" },
      { label: "Shaft", value: "Double-D, 5.4 mm" },
      { label: "Size", value: "70 × 22 × 18 mm" },
    ],
    animate: { spin: ["shaft"] },
    experiment: { title: "Wheel speed ramp", idea: "Through an H-bridge, ramp PWM from 0 to 255 and back, then reverse; add a second motor for a two-wheel robot." },
    tags: ["dc", "motor", "tt", "gear", "wheel", "h-bridge", "robot", "output"],
  },

  {
    id: "relay",
    name: "Relay module, 5 V",
    aka: ["relay board", "1-channel relay", "SRD-05VDC"],
    group: "outputs",
    rank: 6,
    summary: "A switch your board can throw: a small coil pulls a contact that can handle a lamp, a pump or a heater, with nothing electrical in common between the two sides.",
    size: { w: 50, h: 26, d: 18.5 },
    solids: [
      pcb(50, 26, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "box", id: "relay", x: 14, y: 4, w: 19, h: 15.5, d: 15.3, z: 1.6, top: "#1e5fbf", side: "#163f86", radius: 0.6, label: { text: "SRD-05VDC\n10A 250VAC", size: 1.3, color: "#dfe7ff" } },
      ...screwTerminal(35, 9.5, 3, "#1e5fbf", 5),
      ...maleHeader(1, 9.19, 3, "y", 1, false),
      smdLed(5.5, 3.5, "#ff3b3b", "led"),
      chip(6, 6, 4.4, 3, "817", 1.5, "opto"),
      chip(7, 11, 2.9, 1.6, undefined, 1.1, "transistor"),
      { kind: "box", id: "diode", x: 6.5, y: 14.5, w: 4, h: 1.6, d: 1.1, z: 1.6, top: "linear-gradient(90deg,#1b1c1f 0 72%,#d7dadf 72% 84%,#1b1c1f 84%)", side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.2 },
      { kind: "box", x: 6.5, y: 17.5, w: 2, h: 1, d: 0.6, z: 1.6, ...TAN, radius: 0.1 },
      { kind: "box", x: 9, y: 17.5, w: 2, h: 1, d: 0.6, z: 1.6, ...TAN, radius: 0.1 },
      mountHole(2.5, 2.5),
      mountHole(47.5, 2.5),
      mountHole(2.5, 23.5),
      mountHole(47.5, 23.5),
      silk(4.1, 10.9, "VCC", 0.9, MATERIAL.silk),
      silk(4.1, 13.4, "GND", 0.9, MATERIAL.silk),
      silk(4.1, 15.9, "IN", 0.9, MATERIAL.silk),
      silk(37.5, 8.6, "NC", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(42.5, 8.6, "COM", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(47.5, 8.6, "NO", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(23.5, 23.6, "RELAY 5V", 1.6, MATERIAL.silk, { anchor: "middle", weight: 700 }),
    ],
    features: [
      { id: "relay", label: "Relay", kind: "other", x: 14, y: 4, w: 19, h: 15.5, note: "A coil pulls a spring-loaded contact. 5 V coil on one side; contacts rated 10 A at 250 V AC on the other, fully isolated from each other." },
      { id: "terminal", label: "Screw terminals: NC, COM, NO", kind: "connector", x: 35, y: 9.5, w: 15, h: 7.5, note: "COM is the common contact. NO (normally open) connects to COM only while energised; NC the opposite." },
      { id: "header", label: "VCC, GND, IN", kind: "pins", x: 1, y: 9.2, w: 2.54, h: 7.6, note: "IN is the control signal from your board. Many modules are active-low: IN low = relay on." },
      { id: "opto", label: "Optocoupler", kind: "chip", x: 6, y: 6, w: 4.4, h: 3, note: "An LED and a phototransistor in one package: your board's signal crosses as light, so the coil side can never reach back into it." },
      { id: "transistor", label: "Driver transistor", kind: "chip", x: 7, y: 11, w: 2.9, h: 1.6, note: "Switches the ~70 mA the coil needs; a pin alone could not." },
      { id: "diode", label: "Flyback diode", kind: "chip", x: 6.5, y: 14.5, w: 4, h: 1.6, note: "Catches the voltage spike the coil makes when it switches off." },
      { id: "led", label: "Status LED", kind: "led", x: 5, y: 3, w: 2.6, h: 1.8, note: "Lit while the relay is energised." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "5 V for the coil (JD-VCC on some modules)" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "IN", role: "digital", note: "Control: LOW energises on most modules (active-low)" },
      { name: "COM", role: "other", note: "Common contact" },
      { name: "NO", role: "other", note: "Normally open: joined to COM only when energised" },
      { name: "NC", role: "other", note: "Normally closed: opens when energised" },
    ],
    circuit: {
      blocks: [
        { id: "in", label: "IN", sub: "from your board", kind: "pin", col: 0, row: 0, note: "A few milliamps is all it asks of the pin." },
        { id: "opto", label: "Optocoupler", sub: "light, not wires", kind: "ic", col: 1, row: 0, note: "Electrically separates the board from the coil circuit." },
        { id: "tr", label: "Transistor", sub: "sinks ~70 mA", kind: "driver", col: 2, row: 0, note: "The muscle for the coil." },
        { id: "coil", label: "Coil", sub: "5 V, 70 mA", kind: "actuator", col: 3, row: 0, note: "An electromagnet." },
        { id: "contacts", label: "Contacts", sub: "COM ↔ NO / NC", kind: "actuator", col: 3, row: 1, note: "The armature moves COM from NC to NO." },
        { id: "load", label: "Your load", sub: "lamp, pump, ≤ 10 A", kind: "world", col: 3, row: 2, note: "Anything, on its own supply, wired through COM and NO." },
        { id: "vcc", label: "VCC 5 V", kind: "power", col: 2, row: 1, note: "The coil's supply." },
        { id: "diode", label: "Flyback diode", kind: "passive", col: 2, row: 2, note: "Absorbs the coil's switch-off spike." },
        { id: "gnd", label: "GND", kind: "ground", col: 1, row: 2, note: "Ground." },
      ],
      links: [
        { from: "in", to: "opto", kind: "signal", label: "LOW = on" },
        { from: "opto", to: "tr", kind: "signal" },
        { from: "tr", to: "coil", kind: "power" },
        { from: "vcc", to: "coil", kind: "power" },
        { from: "coil", to: "contacts", kind: "mechanical", label: "pulls in" },
        { from: "contacts", to: "load", kind: "power", label: "≤ 10 A" },
        { from: "diode", to: "coil", kind: "power", label: "spike" },
        { from: "tr", to: "gnd", kind: "ground" },
      ],
      steps: [
        "IN goes low (active-low on most modules). That lights the LED inside the optocoupler and its phototransistor turns on. Your board never touches the coil circuit.",
        "The transistor lets ~70 mA flow through the coil from VCC; the magnetic field pulls the armature over with a click.",
        "The armature moves the common contact from NC to NO, so whatever is wired between COM and NO gets its power: a lamp, a pump, a 12 V strip.",
        "Switch off and the coil's collapsing field makes a spike; the flyback diode absorbs it. Mains wiring belongs in a box, done by someone qualified.",
      ],
    },
    facts: [
      { label: "Coil", value: "5 V, ~70 mA" },
      { label: "Contacts", value: "10 A at 250 V AC / 30 V DC" },
      { label: "Control", value: "Active-low IN" },
      { label: "Isolation", value: "Optocoupler" },
      { label: "Switching", value: "~10 ms" },
      { label: "Size", value: "50 × 26 mm" },
    ],
    animate: { lit: ["led"] },
    experiment: { title: "Timed switch", idea: "Click the relay on for five seconds and off for five with a 12 V lamp or fan on COM/NO; then let a sensor decide." },
    tags: ["relay", "switch", "mains", "load", "optocoupler", "high power", "output"],
  },

  {
    id: "stepper-motor",
    name: "Stepper motor, 28BYJ-48 + ULN2003",
    aka: ["28BYJ-48", "stepper with driver", "ULN2003 stepper"],
    group: "outputs",
    rank: 7,
    summary: "A motor that moves in exact steps: 2048 of them per turn, no feedback needed. Clocks, camera sliders, anything that must come back to the same spot.",
    size: { w: 92, h: 40, d: 30.3 },
    solids: [
      { kind: "box", x: 0, y: 16.5, w: 41, h: 7, d: 0.8, z: 0, top: "#b4b9c0", side: "#8f949b", radius: 3.5 },
      { kind: "disc", cx: 3, cy: 20, r: 2.1, color: "#0b0c0e", z: 0.8 },
      { kind: "disc", cx: 38, cy: 20, r: 2.1, color: "#0b0c0e", z: 0.8 },
      { kind: "cyl", id: "can", cx: 20.5, cy: 20, r: 14, d: 19, z: 0.8, top: "linear-gradient(135deg,#d7dadf,#aeb3ba)", side: "#9aa0a7", fill: "#b4b9c0", segments: 28 },
      silk(20.5, 29, "28BYJ-48  5V", 1.6, "#1b1c1f", { anchor: "middle", z: 19.8, weight: 600 }),
      { kind: "cyl", cx: 20.5, cy: 12, r: 4.5, d: 1.5, z: 19.8, top: "#b4b9c0", side: "#8f949b", segments: 20 },
      { kind: "box", id: "shaft", x: 18, y: 10.5, w: 5, h: 3, d: 9, z: 21.3, top: "#d6d9dd", side: "#9aa0a7", radius: 0.6 },
      { kind: "box", x: 32.5, y: 24.5, w: 6, h: 6, d: 5, z: 0.8, top: "#26272b", side: "#111214", radius: 0.4 },
      ...["#2f6fd6", "#f472b6", "#f5d90a", "#f08a24", "#d12d2d"].map((color, i) => wire(38.5, 25 + i * 1.2, 11.5, 1, color, 2)),
      { kind: "box", x: 50, y: 23.5, w: 5, h: 9.5, d: 5.5, z: 0.5, top: MATERIAL.plasticWhite, side: "#c5c9ce", radius: 0.5 },
      { kind: "box", id: "pcb", x: 56, y: 4, w: 35, h: 32, d: 1.6, z: 0, top: MATERIAL.pcbGreen, side: MATERIAL.pcbGreenEdge, radius: 1.5 },
      { kind: "box", x: 56.5, y: 23, w: 6.5, h: 10.5, d: 6.5, z: 1.6, top: MATERIAL.plasticWhite, side: "#c5c9ce", radius: 0.5, holes: { count: 5 } },
      ...dip(64, 10, 8, "ULN2003A"),
      smdLed(65, 22, "#ff3b3b", "led-0"),
      smdLed(69, 22, "#ff3b3b", "led-1"),
      smdLed(73, 22, "#ff3b3b", "led-2"),
      smdLed(77, 22, "#ff3b3b", "led-3"),
      ...maleHeader(88, 11, 6, "y", 1, false),
      silk(65.8, 25, "A", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(69.8, 25, "B", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(73.8, 25, "C", 1, MATERIAL.silk, { anchor: "middle" }),
      silk(77.8, 25, "D", 1, MATERIAL.silk, { anchor: "middle" }),
      ...["IN1", "IN2", "IN3", "IN4", "−", "+"].map((name, i) => silk(87.4, 12.27 + i * 2.54 + 0.35, name, 0.85, MATERIAL.silk, { anchor: "end" })),
      silk(73, 33.5, "ULN2003 DRIVER", 1.2, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      mountHole(58.5, 6.5, 1.4),
      mountHole(88.5, 6.5, 1.4),
    ],
    features: [
      { id: "shaft", label: "Shaft", kind: "mechanical", x: 17, y: 9.5, w: 7, h: 6, note: "5 mm with two flats, offset from the centre of the can. 2048 half-steps per turn after the gearbox." },
      { id: "can", label: "Motor can", kind: "other", x: 6.5, y: 6, w: 28, h: 28, note: "A unipolar stepper: four coils around a toothed rotor, plus a 1:64 gear train under the lid." },
      { id: "flange", label: "Mounting ears", kind: "mechanical", x: 0, y: 16.5, w: 6, h: 7, note: "Two holes 35 mm apart." },
      { id: "cable", label: "5-wire lead", kind: "connector", x: 32.5, y: 23.5, w: 22.5, h: 9.5, note: "Red is the common; blue, pink, yellow and orange are the coil ends. Plugs straight into the driver board." },
      { id: "uln", label: "ULN2003A", kind: "chip", x: 64, y: 10, w: 20.3, h: 7.6, note: "Seven Darlington transistor pairs; four are used to sink the coil currents your board's pins cannot." },
      { id: "leds", label: "A B C D LEDs", kind: "led", x: 64.5, y: 21.5, w: 15.5, h: 2, note: "One per coil; they chase round as the motor steps." },
      { id: "header", label: "IN1–IN4, −, +", kind: "pins", x: 88, y: 11, w: 2.54, h: 15.24, note: "IN1–IN4 from four digital pins; − and + take 5 V for the motor." },
    ],
    pins: [
      { name: "IN1–IN4", role: "digital", note: "Four digital pins; the library steps them in sequence" },
      { name: "+", role: "power", note: "5 V for the coils, ~240 mA" },
      { name: "−", role: "ground", note: "GND" },
      { name: "Motor plug", role: "other", note: "5-pin JST: red common; blue, pink, yellow, orange coils" },
    ],
    circuit: {
      blocks: [
        { id: "pins", label: "IN1–IN4", sub: "step sequence", kind: "pin", col: 0, row: 0, note: "Your board energises the coils in order; Stepper or AccelStepper libraries do it." },
        { id: "uln", label: "ULN2003A", sub: "Darlington sinks", kind: "driver", col: 1, row: 0, note: "Each input turns on a transistor pair that pulls one coil to ground." },
        { id: "coils", label: "Four coils", sub: "red = common", kind: "actuator", col: 2, row: 0, note: "Electromagnets around the rotor; the red wire feeds them all from +5 V." },
        { id: "rotor", label: "Rotor", sub: "32 steps / rev", kind: "actuator", col: 3, row: 0, note: "A toothed permanent magnet that snaps to whichever coil is on." },
        { id: "gears", label: "Gear train", sub: "1 : 64", kind: "actuator", col: 3, row: 1, note: "Slows the rotor and multiplies torque." },
        { id: "shaft", label: "Shaft", sub: "2048 steps / rev", kind: "actuator", col: 3, row: 2, note: "About 15 rpm at most; faster and it skips steps." },
        { id: "vcc", label: "+5 V", sub: "~240 mA", kind: "power", col: 2, row: 1, note: "The motor supply, through the red wire." },
        { id: "leds", label: "A–D LEDs", kind: "actuator", col: 1, row: 1, note: "Show which coil is energised." },
        { id: "gnd", label: "GND", kind: "ground", col: 0, row: 1, note: "Ground." },
      ],
      links: [
        { from: "pins", to: "uln", kind: "signal", label: "4 lines" },
        { from: "uln", to: "coils", kind: "power", label: "sinks current" },
        { from: "vcc", to: "coils", kind: "power" },
        { from: "coils", to: "rotor", kind: "mechanical", label: "magnetic pull" },
        { from: "rotor", to: "gears", kind: "mechanical" },
        { from: "gears", to: "shaft", kind: "mechanical" },
        { from: "uln", to: "leds", kind: "signal" },
        { from: "uln", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Your board energises the four coils in sequence (full or half-step). The ULN2003 sinks the current each coil needs; the LEDs show which is on.",
        "Each coil pulls the toothed rotor one step round: 32 steps for a full turn of the rotor.",
        "A 1:64 gear train slows it, so the shaft needs 2048 half-steps per turn: slow, strong-ish and exact, no feedback needed.",
        "Top speed is about 15 rpm; faster and it skips. Power the coils from 5 V with enough current, not from the board's 3.3 V pin.",
      ],
    },
    facts: [
      { label: "Steps", value: "2048 per turn (half-step)" },
      { label: "Gear ratio", value: "1:64" },
      { label: "Supply", value: "5 V, ~240 mA" },
      { label: "Torque", value: "~34 mN·m" },
      { label: "Max speed", value: "~15 rpm" },
      { label: "Driver", value: "ULN2003 board" },
    ],
    animate: { spin: ["shaft"], lit: ["led-0", "led-1", "led-2", "led-3"] },
    experiment: { title: "One exact turn", idea: "Step exactly one revolution clockwise, pause, then back; mark the shaft with tape and check it returns to the mark." },
    tags: ["stepper", "28byj-48", "uln2003", "motor", "steps", "precise", "output"],
  },
];
