import { MATERIAL, chip, maleHeader, pads, pcb, shieldCan, silk, smdLed, tactileButton, wire } from "../build";
import type { PartModel, Solid } from "../types";

/** A printed meander antenna running along y, zig-zagging across x. */
function meander(x: number, y: number, w: number, h: number, turns = 7, z?: number): Solid {
  const step = h / turns;
  let d = `M ${x} ${y}`;
  for (let i = 0; i < turns; i++) {
    const py = y + i * step;
    d += i % 2 === 0 ? ` L ${x + w} ${py} L ${x + w} ${py + step}` : ` L ${x} ${py} L ${x} ${py + step}`;
  }
  return { kind: "path", d, color: MATERIAL.gold, width: 0.45, z };
}

const IC_TOP = "linear-gradient(180deg,#232428,#17181b)";

export const RADIOS: PartModel[] = [
  {
    id: "hc-05",
    name: "HC-05 Bluetooth",
    aka: ["HC05", "Bluetooth serial module", "HC-06 cousin"],
    group: "radios",
    rank: 1,
    summary: "A wireless serial cable. Pair it with a phone and whatever your board prints arrives there; whatever you type comes back. Classic Bluetooth, 9600 baud, done in an afternoon.",
    size: { w: 37.3, h: 15.7, d: 7.6 },
    solids: [
      pcb(37.3, 15.7, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "box", id: "module", x: 0.6, y: 1.35, w: 27, h: 13, d: 1, z: 1.6, top: MATERIAL.pcbGreen, side: MATERIAL.pcbGreenEdge, radius: 0.3 },
      meander(1.6, 2.6, 4.2, 10.5, 7, 2.65),
      { kind: "box", id: "bc417", x: 9.5, y: 4, w: 6, h: 6, d: 0.9, z: 2.6, top: IC_TOP, side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.3, label: { text: "BC417", size: 1, color: "#a3a7ad" } },
      { kind: "box", id: "flash", x: 17.5, y: 5, w: 4, h: 5.2, d: 1.1, z: 2.6, top: IC_TOP, side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.3, label: { text: "FLASH", size: 0.75, color: "#a3a7ad" } },
      { kind: "box", x: 17.5, y: 1.9, w: 4, h: 2.2, d: 0.9, z: 2.6, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 0.5 },
      { kind: "box", x: 22.5, y: 2, w: 1.6, h: 0.8, d: 0.5, z: 2.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 22.5, y: 3.5, w: 1.6, h: 0.8, d: 0.5, z: 2.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      smdLed(30, 2.3, "#ff3b3b", "led"),
      chip(29, 6, 2.9, 1.6, undefined, 1.1, "reg"),
      ...tactileButton(29.5, 10.2, 3.5, "btn"),
      { kind: "box", x: 37.3, y: 0.2, w: 2.5, h: 15.3, d: 2.5, z: 0, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.3 },
      ...[1.5, 4.04, 6.58, 9.12, 11.66, 14.2].map((y) => wire(37.3, y - 0.32, 6, 0.64, MATERIAL.tin, 0.5)),
      ...["STATE", "RXD", "TXD", "GND", "VCC", "EN"].map((name, i) => silk(36.8, 1.5 + i * 2.54 + 0.3, name, 0.75, MATERIAL.silk, { anchor: "end" })),
      silk(14, 13.2, "HC-05", 1.2, MATERIAL.silk, { anchor: "middle", weight: 700, z: 2.65 }),
    ],
    features: [
      { id: "module", label: "Bluetooth module", kind: "chip", x: 0.6, y: 1.35, w: 27, h: 13, note: "The radio: a BC417 chip with the Bluetooth stack in flash. Classic Bluetooth 2.0 with the Serial Port Profile: a wireless serial cable." },
      { id: "antenna", label: "PCB antenna", kind: "antenna", x: 1.2, y: 2.2, w: 5, h: 11.5, note: "A meander of copper tuned to 2.4 GHz. Keep metal and fingers away from this end." },
      { id: "led", label: "Status LED", kind: "led", x: 29.5, y: 1.8, w: 2.6, h: 1.8, note: "Fast blink: waiting to pair. Slow double blink: connected. Slow blink: AT mode." },
      { id: "btn", label: "EN button", kind: "button", x: 29.5, y: 10.2, w: 3.5, h: 3.5, note: "Hold while powering up to enter AT command mode (38400 baud) and change the name, PIN or baud rate." },
      { id: "reg", label: "3.3 V regulator", kind: "chip", x: 29, y: 6, w: 2.9, h: 1.6, note: "Lets VCC take 3.6–6 V. RXD is still 3.3 V logic: use a divider from a 5 V board." },
      { id: "pins", label: "STATE, RXD, TXD, GND, VCC, EN", kind: "pins", x: 37.3, y: 0.2, w: 6, h: 15.3, note: "Right-angle pins. Cross them over: the module's TXD goes to your board's RX and vice versa." },
    ],
    pins: [
      { name: "STATE", role: "digital", note: "High while connected" },
      { name: "RXD", role: "uart", note: "Serial in, 3.3 V logic: divider from a 5 V TX" },
      { name: "TXD", role: "uart", note: "Serial out; safe to read on a 5 V board" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "VCC", role: "power", note: "3.6–6 V" },
      { name: "EN / KEY", role: "digital", note: "High at power-up = AT command mode" },
    ],
    circuit: {
      blocks: [
        { id: "uart", label: "RXD / TXD", sub: "9600 baud default", kind: "pin", col: 0, row: 1, note: "Plain serial, like the USB monitor." },
        { id: "bc", label: "BC417", sub: "Bluetooth 2.0 + EDR", kind: "ic", col: 1, row: 1, note: "Radio, baseband and the whole Bluetooth stack in one chip." },
        { id: "ant", label: "PCB antenna", sub: "2.4 GHz", kind: "antenna", col: 2, row: 1, note: "Printed copper; no part to lose." },
        { id: "phone", label: "Phone or PC", sub: "SPP, ~10 m", kind: "world", col: 3, row: 1, note: "Any Bluetooth serial terminal app." },
        { id: "vcc", label: "VCC 3.6–6 V", kind: "power", col: 0, row: 0, note: "30–40 mA while paired." },
        { id: "reg", label: "3.3 V regulator", kind: "regulator", col: 1, row: 0, note: "The module itself is a 3.3 V part." },
        { id: "flash", label: "Flash", sub: "stack, name, PIN", kind: "ic", col: 2, row: 0, note: "Settings survive power-off here." },
        { id: "en", label: "EN / KEY", sub: "AT mode", kind: "pin", col: 0, row: 2, note: "High at boot switches to command mode." },
        { id: "led", label: "Status LED", kind: "actuator", col: 1, row: 2, note: "Blink patterns tell you the state." },
      ],
      links: [
        { from: "uart", to: "bc", kind: "data", label: "serial", both: true },
        { from: "bc", to: "ant", kind: "rf", both: true },
        { from: "ant", to: "phone", kind: "rf", label: "radio", both: true },
        { from: "vcc", to: "reg", kind: "power" },
        { from: "reg", to: "bc", kind: "power", label: "3.3 V" },
        { from: "flash", to: "bc", kind: "data", both: true },
        { from: "en", to: "bc", kind: "signal" },
        { from: "bc", to: "led", kind: "signal" },
      ],
      steps: [
        "Power on VCC is dropped to 3.3 V; the BC417 boots the Bluetooth stack from flash and blinks fast: discoverable as 'HC-05', PIN 1234.",
        "A phone or PC pairs and opens a Serial Port Profile link: a two-way wireless serial cable at 9600 baud.",
        "Whatever your board writes to TXD goes out over the antenna; whatever the phone sends arrives on RXD. Classic Bluetooth, up to about 10 m.",
        "Hold EN at power-up for AT mode (38400 baud) to rename it, change the PIN, or make it a master that connects to another HC-05.",
      ],
    },
    facts: [
      { label: "Bluetooth", value: "2.0 + EDR, Classic" },
      { label: "Profile", value: "SPP (serial)" },
      { label: "Range", value: "~10 m" },
      { label: "Defaults", value: "9600 baud, PIN 1234" },
      { label: "Supply", value: "3.6–6 V, 30–40 mA" },
      { label: "Logic", value: "3.3 V" },
    ],
    animate: { lit: ["led"] },
    experiment: { title: "Phone remote", idea: "Pair with a Bluetooth serial app on your phone and toggle an LED with the letters you type; then stream a sensor reading back." },
    tags: ["hc-05", "hc05", "bluetooth", "serial", "wireless", "uart", "phone", "radio"],
  },

  {
    id: "wifi-module",
    name: "ESP-01 Wi-Fi module",
    aka: ["ESP8266 ESP-01", "Wi-Fi module", "AT-command Wi-Fi"],
    group: "radios",
    rank: 2,
    summary: "A postage stamp that joins your Wi-Fi. Talk to it with AT commands over serial, or program the ESP8266 on it directly and it becomes the whole project.",
    size: { w: 24.8, h: 14.3, d: 10.1 },
    solids: [
      pcb(24.8, 14.3, MATERIAL.pcbBlack, MATERIAL.pcbBlackEdge),
      meander(1.2, 1.4, 6, 11.6, 9),
      { kind: "box", id: "soc", x: 10, y: 2, w: 5, h: 5, d: 0.9, z: 1.6, top: IC_TOP, side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.3, label: { text: "8266", size: 0.9, color: "#a3a7ad" } },
      { kind: "box", id: "flash", x: 16.3, y: 2, w: 5.3, h: 5.3, d: 1.1, z: 1.6, top: IC_TOP, side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.3, label: { text: "FLASH", size: 0.8, color: "#a3a7ad" } },
      smdLed(10, 9, "#ff3b3b", "led-pwr"),
      smdLed(13, 9, "#3b82f6", "led-tx"),
      { kind: "box", id: "xtal", x: 16.5, y: 8.5, w: 3.2, h: 2.5, d: 0.8, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 0.4 },
      ...maleHeader(19.72, 2.07, 4, "y", 2, false),
      silk(13, 13.3, "ESP-01", 1.1, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      silk(9.2, 11.6, "PWR", 0.7, MATERIAL.silk),
      silk(12.6, 11.6, "TX", 0.7, MATERIAL.silk),
    ],
    features: [
      { id: "antenna", label: "PCB antenna", kind: "antenna", x: 0.8, y: 1, w: 7, h: 12.4, note: "Printed meander for 2.4 GHz Wi-Fi. Decent range indoors; keep it clear of the board it plugs into." },
      { id: "soc", label: "ESP8266EX", kind: "chip", x: 10, y: 2, w: 5, h: 5, note: "80 MHz Wi-Fi SoC: it runs your code and the whole TCP/IP stack. The same chip as on a NodeMCU." },
      { id: "flash", label: "SPI flash", kind: "chip", x: 16.3, y: 2, w: 5.3, h: 5.3, note: "1 MB (older ones 512 KB) holding the firmware or your sketch." },
      { id: "leds", label: "Power and TX LEDs", kind: "led", x: 9.5, y: 8.5, w: 5.5, h: 2, note: "Red: powered. Blue: flashes when it transmits on the serial port." },
      { id: "header", label: "2 × 4 header", kind: "pins", x: 19.72, y: 2.07, w: 5.08, h: 10.16, note: "GND, GPIO2, GPIO0, RX on one row; TX, CH_PD, RST, VCC on the other. 3.3 V only." },
      { id: "xtal", label: "26 MHz crystal", kind: "chip", x: 16.5, y: 8.5, w: 3.2, h: 2.5, note: "The clock the radio is timed from." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3 V only, 300 mA peaks: not the Uno's 3.3 V pin" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "TX", role: "uart", note: "Serial out, 3.3 V" },
      { name: "RX", role: "uart", note: "Serial in, 3.3 V logic: divider from a 5 V board" },
      { name: "CH_PD (EN)", role: "digital", note: "Pull high to run" },
      { name: "RST", role: "digital", note: "Low to reset" },
      { name: "GPIO0", role: "digital", note: "Low at boot = flashing mode; free afterwards" },
      { name: "GPIO2", role: "digital", note: "Spare I/O; must be high at boot" },
    ],
    circuit: {
      blocks: [
        { id: "uart", label: "TX / RX", sub: "AT commands or code", kind: "pin", col: 0, row: 1, note: "115200 baud on most firmware." },
        { id: "soc", label: "ESP8266EX", sub: "80 MHz + TCP/IP", kind: "mcu", col: 1, row: 1, note: "A real microcontroller with Wi-Fi built in." },
        { id: "radio", label: "Wi-Fi radio", sub: "802.11 b/g/n", kind: "antenna", col: 2, row: 1, note: "2.4 GHz transceiver on the same chip." },
        { id: "ant", label: "PCB antenna", kind: "antenna", col: 3, row: 1, note: "Printed copper." },
        { id: "router", label: "Router / cloud", kind: "world", col: 3, row: 2, note: "Your network, then the internet." },
        { id: "flash", label: "SPI flash", sub: "1 MB", kind: "ic", col: 1, row: 0, note: "Firmware lives here." },
        { id: "vcc", label: "VCC 3.3 V", sub: "300 mA peaks", kind: "power", col: 0, row: 0, note: "A weak supply shows up as random resets." },
        { id: "boot", label: "GPIO0 / CH_PD", sub: "boot mode, enable", kind: "pin", col: 0, row: 2, note: "CH_PD high to run; GPIO0 low at reset to flash." },
      ],
      links: [
        { from: "uart", to: "soc", kind: "data", both: true },
        { from: "soc", to: "radio", kind: "data", both: true },
        { from: "radio", to: "ant", kind: "rf", both: true },
        { from: "ant", to: "router", kind: "rf", label: "Wi-Fi", both: true },
        { from: "flash", to: "soc", kind: "data", both: true },
        { from: "vcc", to: "soc", kind: "power" },
        { from: "boot", to: "soc", kind: "signal" },
      ],
      steps: [
        "CH_PD high and 3.3 V on VCC: the chip boots from the flash. With GPIO0 low at that moment it waits for new firmware instead.",
        "Stock firmware speaks AT commands over the serial pins: AT+CWJAP joins your Wi-Fi, AT+CIPSTART opens a TCP connection.",
        "Or program it directly with the Arduino core: then it is a tiny Wi-Fi computer with two spare GPIOs.",
        "Transmit bursts draw up to 300 mA at 3.3 V; a weak supply reboots it. A proper 3.3 V regulator plus 100 µF fixes most 'random resets'.",
      ],
    },
    facts: [
      { label: "Chip", value: "ESP8266EX, 80 MHz" },
      { label: "Wi-Fi", value: "802.11 b/g/n, 2.4 GHz" },
      { label: "Flash", value: "1 MB" },
      { label: "GPIO", value: "2 spare (GPIO0, GPIO2)" },
      { label: "Supply", value: "3.3 V, 70–300 mA" },
      { label: "Size", value: "24.8 × 14.3 mm" },
    ],
    animate: { lit: ["led-pwr", "led-tx"] },
    experiment: { title: "Join the Wi-Fi", idea: "Send AT+CWJAP with your network name and watch it get an IP address; then fetch a web page with AT+CIPSTART." },
    tags: ["esp-01", "esp8266", "wifi", "wi-fi", "wireless", "at commands", "internet", "radio", "module"],
  },

  {
    id: "nrf24l01",
    name: "nRF24L01+ radio",
    aka: ["NRF24", "2.4 GHz transceiver", "RF24 module"],
    group: "radios",
    rank: 3,
    summary: "Board-to-board radio without Wi-Fi or Bluetooth: tiny packets, hardware acknowledgements, six channels, 100 m. The link inside most DIY remote controls.",
    size: { w: 29, h: 15.3, d: 4.1 },
    solids: [
      pcb(29, 15.3, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      meander(1.2, 1.4, 7.5, 12.5, 9),
      { kind: "box", id: "nrf", x: 12.5, y: 5.5, w: 4, h: 4, d: 0.9, z: 1.6, top: IC_TOP, side: MATERIAL.icSide, fill: MATERIAL.ic, radius: 0.3, label: { text: "nRF24", size: 0.75, color: "#a3a7ad" } },
      { kind: "box", id: "xtal", x: 18, y: 2.5, w: 3.2, h: 2.5, d: 0.8, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 0.4 },
      { kind: "box", x: 18, y: 7, w: 1.6, h: 0.8, d: 0.5, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 18, y: 8.6, w: 1.6, h: 0.8, d: 0.5, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 12.5, y: 11, w: 1.6, h: 0.8, d: 0.5, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      ...maleHeader(23.6, 2.57, 4, "y", 2, true),
      silk(14, 14.3, "NRF24L01+", 1, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      silk(22.7, 4.3, "1", 0.8, MATERIAL.silk, { anchor: "end" }),
    ],
    features: [
      { id: "antenna", label: "PCB antenna", kind: "antenna", x: 0.8, y: 1, w: 8.5, h: 13.3, note: "Tuned for 2.4 GHz. The PA+LNA version swaps this for an SMA socket and a whip antenna, good for a kilometre in the open." },
      { id: "nrf", label: "nRF24L01+", kind: "chip", x: 12.5, y: 5.5, w: 4, h: 4, note: "Transceiver with a packet engine: addresses, acknowledgements and retries happen in hardware, at 250 kbps to 2 Mbps." },
      { id: "xtal", label: "16 MHz crystal", kind: "chip", x: 18, y: 2.5, w: 3.2, h: 2.5, note: "The radio's timing reference." },
      { id: "header", label: "2 × 4 header", kind: "pins", x: 23.6, y: 2.57, w: 5.08, h: 10.16, note: "GND, VCC, CE, CSN, SCK, MOSI, MISO, IRQ; pin 1 (GND) is marked. Pins point down. VCC is 3.3 V; the signal pins tolerate 5 V logic." },
    ],
    pins: [
      { name: "GND", role: "ground", note: "Ground; pin 1, square pad" },
      { name: "VCC", role: "power", note: "3.3 V only; add 10–100 µF right at the pins" },
      { name: "CE", role: "digital", note: "Chip enable: high to transmit or listen" },
      { name: "CSN", role: "spi", note: "SPI chip select, active low" },
      { name: "SCK", role: "spi", note: "SPI clock" },
      { name: "MOSI", role: "spi", note: "SPI data in" },
      { name: "MISO", role: "spi", note: "SPI data out" },
      { name: "IRQ", role: "digital", note: "Interrupt: packet received or sent" },
    ],
    circuit: {
      blocks: [
        { id: "spi", label: "SPI", sub: "MOSI, MISO, SCK, CSN", kind: "pin", col: 0, row: 1, note: "Configuration and payloads, up to 10 MHz." },
        { id: "eng", label: "Packet engine", sub: "auto-ack, retries", kind: "ic", col: 1, row: 1, note: "Builds packets, checks CRCs, waits for acknowledgements." },
        { id: "radio", label: "2.4 GHz radio", sub: "126 channels", kind: "ic", col: 2, row: 1, note: "GFSK transceiver." },
        { id: "ant", label: "PCB antenna", kind: "antenna", col: 3, row: 1, note: "Printed copper." },
        { id: "peer", label: "Other node", sub: "up to 6 pipes", kind: "world", col: 3, row: 2, note: "Another board with the same module." },
        { id: "xtal", label: "16 MHz crystal", kind: "passive", col: 1, row: 0, note: "Timing for the radio." },
        { id: "ce", label: "CE / IRQ", sub: "go, done", kind: "pin", col: 0, row: 0, note: "CE starts the radio; IRQ tells you when something happened." },
        { id: "vcc", label: "VCC 3.3 V", sub: "+ capacitor", kind: "power", col: 0, row: 2, note: "The number-one cause of trouble is a sagging supply." },
      ],
      links: [
        { from: "spi", to: "eng", kind: "data", both: true },
        { from: "eng", to: "radio", kind: "data", both: true },
        { from: "radio", to: "ant", kind: "rf", both: true },
        { from: "ant", to: "peer", kind: "rf", label: "2.4 GHz", both: true },
        { from: "xtal", to: "radio", kind: "signal", label: "clock" },
        { from: "ce", to: "eng", kind: "signal" },
        { from: "vcc", to: "eng", kind: "power" },
      ],
      steps: [
        "Your board configures the chip over SPI: channel, data rate, and a 5-byte address for each 'pipe'.",
        "CE high: the packet engine sends your bytes, waits for the other node's acknowledgement and retries on its own if it didn't come.",
        "Receiving nodes filter packets by address in hardware, so up to six transmitters can talk to one receiver.",
        "Most 'it doesn't work' cases are power: 3.3 V with a 10–100 µF capacitor soldered across VCC and GND.",
      ],
    },
    facts: [
      { label: "Band", value: "2.4 GHz, 126 channels" },
      { label: "Data rate", value: "250 kbps – 2 Mbps" },
      { label: "Range", value: "~100 m open air (PA+LNA ~1 km)" },
      { label: "Interface", value: "SPI + CE, IRQ" },
      { label: "Supply", value: "1.9–3.6 V, ~12 mA TX" },
      { label: "Size", value: "29 × 15 mm" },
    ],
    experiment: { title: "Wireless button", idea: "Two boards, two modules: press a button on one and light an LED on the other, then send a sensor reading every second." },
    tags: ["nrf24l01", "nrf24", "2.4ghz", "wireless", "spi", "radio", "rf24", "remote"],
  },

  {
    id: "lora",
    name: "LoRa Ra-02 (SX1278)",
    aka: ["LoRa module", "SX1278", "433 MHz LoRa", "Ai-Thinker Ra-02"],
    group: "radios",
    rank: 4,
    summary: "Kilometres on a coin cell's worth of power. Slow, tiny packets that survive below the noise floor: farm sensors, weather stations, anything far from a plug.",
    size: { w: 56, h: 16, d: 4 },
    solids: [
      { kind: "box", id: "pcb", x: 0, y: 0, w: 17, h: 16, d: 1, top: MATERIAL.pcbGreen, side: MATERIAL.pcbGreenEdge, radius: 0.6 },
      shieldCan(1, 1, 15, 10.5, "Ra-02\nSX1278", 2.3, 1),
      ...pads(2.5, 0.5, 8, "x", 2, 0.5, 1.05),
      ...pads(2.5, 15.5, 8, "x", 2, 0.5, 1.05),
      { kind: "box", id: "ufl", x: 13.5, y: 12.5, w: 2.6, h: 2.6, d: 1.2, z: 1, top: MATERIAL.gold, side: "#9c7a35", radius: 0.3 },
      { kind: "disc", cx: 14.8, cy: 13.8, r: 0.7, color: "#1b1c1f", z: 2.2 },
      chip(2, 12.2, 2.2, 1.2, undefined, 0.6, undefined, 1),
      chip(5, 12.2, 2.2, 1.2, undefined, 0.6, undefined, 1),
      chip(8, 12.2, 2.2, 1.2, undefined, 0.6, undefined, 1),
      { kind: "path", d: "M 14.8 13.8 L 19 13.8 L 21.5 9 L 24 7", color: "#1b1c1f", width: 0.8, z: 1.3 },
      { kind: "box", id: "antenna", x: 24, y: 5, w: 32, h: 4, d: 4, z: 0, top: "repeating-linear-gradient(90deg,#d79556 0 3px,#8a5223 3px 5px)", side: "#8a5223", fill: "#c77e3a", radius: 2 },
      silk(8.5, 15.3, "433 MHz", 0.8, MATERIAL.silk, { anchor: "middle" }),
    ],
    features: [
      { id: "can", label: "Shielded radio (SX1278)", kind: "chip", x: 1, y: 1, w: 15, h: 10.5, note: "The LoRa transceiver, its 32 MHz crystal and the RF switch live under this tin lid. 410–525 MHz; the Ra-02 ships tuned for 433 MHz." },
      { id: "ufl", label: "u.FL antenna socket", kind: "connector", x: 13.3, y: 12.3, w: 3, h: 3, note: "Never transmit without an antenna attached: the output stage can be damaged." },
      { id: "pads-top", label: "Pads: GND, DIO0–DIO5, 3.3 V", kind: "pins", x: 1.8, y: -0.3, w: 15.4, h: 1.5, note: "Castellated pads at 2 mm pitch; solder it to a breakout or carrier board." },
      { id: "pads-bottom", label: "Pads: GND, NSS, MOSI, MISO, SCK, RST", kind: "pins", x: 1.8, y: 14.8, w: 15.4, h: 1.5, note: "The SPI side: chip select, data in and out, clock, and reset." },
      { id: "antenna", label: "433 MHz spring antenna", kind: "antenna", x: 19, y: 4, w: 37, h: 6, note: "A quarter-wave helical. A proper whip gives more range; keep it vertical and away from the ground plane." },
    ],
    pins: [
      { name: "3.3V", role: "power", note: "1.8–3.7 V; 120 mA while transmitting" },
      { name: "GND", role: "ground", note: "Ground, several pads" },
      { name: "NSS", role: "spi", note: "SPI chip select" },
      { name: "MOSI", role: "spi", note: "SPI data in" },
      { name: "MISO", role: "spi", note: "SPI data out" },
      { name: "SCK", role: "spi", note: "SPI clock" },
      { name: "RST", role: "digital", note: "Reset, active low" },
      { name: "DIO0", role: "digital", note: "Interrupt: packet sent or received" },
      { name: "DIO1–DIO5", role: "digital", note: "More interrupt outputs: timeouts, channel activity" },
    ],
    circuit: {
      blocks: [
        { id: "spi", label: "SPI + NSS", kind: "pin", col: 0, row: 1, note: "Registers and the packet FIFO." },
        { id: "sx", label: "SX1278", sub: "LoRa modem", kind: "ic", col: 1, row: 1, note: "Spreads each symbol into a chirp; decodes chirps below the noise." },
        { id: "fe", label: "RF front end", sub: "PA + LNA + switch", kind: "ic", col: 2, row: 1, note: "Up to +20 dBm out; a sensitive receiver in." },
        { id: "ant", label: "Spring antenna", sub: "433 MHz", kind: "antenna", col: 3, row: 1, note: "Via the u.FL pigtail." },
        { id: "far", label: "Nodes km away", sub: "−148 dBm sensitivity", kind: "world", col: 3, row: 2, note: "Other LoRa radios on the same frequency and settings." },
        { id: "dio", label: "DIO0", sub: "interrupt", kind: "pin", col: 0, row: 0, note: "Goes high when a packet has gone out or come in." },
        { id: "xtal", label: "32 MHz crystal", kind: "passive", col: 1, row: 0, note: "Frequency reference; both ends must agree within a few kHz." },
        { id: "vcc", label: "3.3 V", sub: "120 mA TX", kind: "power", col: 0, row: 2, note: "Sleeps at ~1 µA between packets." },
      ],
      links: [
        { from: "spi", to: "sx", kind: "data", both: true },
        { from: "sx", to: "fe", kind: "rf", both: true },
        { from: "fe", to: "ant", kind: "rf", both: true },
        { from: "ant", to: "far", kind: "rf", label: "LoRa chirps", both: true },
        { from: "sx", to: "dio", kind: "signal", label: "done" },
        { from: "xtal", to: "sx", kind: "signal" },
        { from: "vcc", to: "sx", kind: "power" },
      ],
      steps: [
        "Your board writes the frequency, spreading factor and bandwidth into the SX1278 over SPI and hands it a payload of up to 255 bytes.",
        "The modem spreads each symbol into a chirp that sweeps across the bandwidth; a receiver can pick chirps out well below the noise floor.",
        "The front end amplifies it (up to +20 dBm) and the antenna radiates at 433 MHz; DIO0 goes high when the packet has left, or when one arrives.",
        "Slow and far: a few hundred bits per second reach several kilometres in the open, and the chip sleeps at 1 µA between packets.",
      ],
    },
    facts: [
      { label: "Band", value: "410–525 MHz (433 MHz)" },
      { label: "Modulation", value: "LoRa chirp spread spectrum" },
      { label: "Sensitivity", value: "−148 dBm" },
      { label: "Power", value: "up to +20 dBm" },
      { label: "Range", value: "2–10+ km line of sight" },
      { label: "Supply", value: "1.8–3.7 V, 120 mA TX" },
    ],
    experiment: { title: "Long-range ping", idea: "Two nodes: send a counter every 5 s and print the signal strength on the other; walk away with one and find where the link drops." },
    tags: ["lora", "ra-02", "sx1278", "433mhz", "long range", "spi", "radio", "wireless", "iot"],
  },
];
