import { MATERIAL, chip, flatLegs, maleHeader, mountHole, pads, pcb, silk, smdLed, trimPot, wire } from "../build";
import type { PartModel, Solid } from "../types";

/** The snake-shaped light-sensitive track printed on a photoresistor face. */
function serpentine(cx: number, cy: number, r: number): Solid {
  const rows = 7;
  const gap = (r * 1.7) / (rows - 1);
  let d = "";
  for (let i = 0; i < rows; i++) {
    const y = cy - r * 0.85 + i * gap;
    const half = Math.sqrt(Math.max(0, r * r - (y - cy) * (y - cy))) - 0.35;
    const x1 = cx - half;
    const x2 = cx + half;
    d += i === 0 ? `M ${x1.toFixed(2)} ${y.toFixed(2)} L ${x2.toFixed(2)} ${y.toFixed(2)}` : i % 2 === 1 ? ` L ${x2.toFixed(2)} ${y.toFixed(2)} L ${x1.toFixed(2)} ${y.toFixed(2)}` : ` L ${x1.toFixed(2)} ${y.toFixed(2)} L ${x2.toFixed(2)} ${y.toFixed(2)}`;
  }
  return { kind: "path", d, color: "#3b2f2a", width: 0.3, z: 2.05 };
}

/** The white DHT22 / AM2302 housing lying on its back, slots up. */
function dhtHousing(label: string): Solid[] {
  const slots: Solid[] = Array.from({ length: 6 }, (_, i) => ({ kind: "box", x: 2.3, y: 5 + i * 2.6, w: 10.5, h: 1.1, d: 0.25, z: 7.5, top: "#8e949b", side: "#6b7280", radius: 0.5 }) as Solid);
  return [
    { kind: "box", id: "body", x: 0, y: 0, w: 15.1, h: 25.1, d: 7.7, top: MATERIAL.plasticWhite, side: "#c5c9ce", radius: 1 },
    ...slots,
    { kind: "disc", cx: 7.55, cy: 2.3, r: 1.2, color: "#5b6066", z: 7.7 },
    silk(7.55, 23.6, label, 1.4, "#6b7280", { anchor: "middle", z: 7.7, weight: 600 }),
  ];
}

const DHT_STEPS_11 = [
  "Your board pulls DATA low for at least 18 ms to ask for a reading, then releases the line.",
  "The chip inside measures the resistive humidity film and the NTC thermistor and converts both to numbers.",
  "It answers on the same wire with 40 bits: humidity, temperature and a checksum, each bit told apart by pulse length.",
  "One reading a second at most; the library you use handles the timing for you.",
];

export const SENSORS: PartModel[] = [
  {
    id: "dht11",
    name: "DHT11 humidity & temperature",
    aka: ["DHT-11", "blue climate sensor"],
    group: "sensors",
    rank: 1,
    summary: "The little blue box that tells you how warm and how humid the room is, over one wire. Cheap, slow, and the first sensor most people wire up.",
    size: { w: 15.5, h: 22, d: 5.5 },
    solids: [
      { kind: "box", id: "body", x: 0, y: 0, w: 15.5, h: 12, d: 5.5, top: MATERIAL.plasticBlue, side: "#1f4c96", radius: 0.6 },
      ...Array.from({ length: 12 }, (_, i) => ({ kind: "disc", cx: 3.5 + (i % 4) * 2.9, cy: 2.6 + Math.floor(i / 4) * 2.4, r: 0.7, color: "#17408f", z: 5.5 }) as Solid),
      silk(7.75, 10.9, "DHT11", 1.3, "#dbe7ff", { anchor: "middle", z: 5.5, weight: 600 }),
      ...flatLegs(3.94, 12, 4, 10, 2.54, 2.2),
    ],
    features: [
      { id: "grille", label: "Sensing grille", kind: "sensor", x: 2, y: 1.2, w: 11.5, h: 7.4, note: "Air reaches the humidity element and the thermistor through these holes. Keep them clear; never cover them with tape or glue." },
      { id: "legs", label: "Legs: VCC, DATA, NC, GND", kind: "pins", x: 3.4, y: 12, w: 8.7, h: 10, note: "Left to right with the grille facing you: VCC, DATA, not connected, GND. Three-pin modules drop the NC leg and add the pull-up resistor for you." },
      { id: "body", label: "Blue housing", kind: "other", x: 0, y: 0, w: 15.5, h: 12, note: "Holds an 8-bit chip that reads the two elements and answers on the single data wire." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3–5.5 V" },
      { name: "DATA", role: "data", note: "Single-wire bus; add a 10 kΩ pull-up to VCC (modules have it)" },
      { name: "NC", role: "other", note: "Not connected" },
      { name: "GND", role: "ground", note: "Ground" },
    ],
    circuit: {
      blocks: [
        { id: "air", label: "Air", sub: "humidity, temperature", kind: "world", col: 0, row: 0, note: "What it measures: the air that reaches the grille." },
        { id: "hum", label: "Humidity film", sub: "resistive", kind: "sensor", col: 1, row: 0, note: "A polymer film whose resistance changes with moisture." },
        { id: "ntc", label: "Thermistor", sub: "NTC", kind: "sensor", col: 1, row: 1, note: "A resistor that drops in value as it warms." },
        { id: "mcu", label: "Sensor chip", sub: "8-bit, 40-bit frames", kind: "ic", col: 2, row: 0, note: "Reads both elements and answers on the single data wire." },
        { id: "data", label: "DATA", sub: "one wire, both ways", kind: "pin", col: 3, row: 0, note: "Your board asks here and the reply comes back on the same wire." },
        { id: "vcc", label: "VCC", sub: "3–5.5 V", kind: "power", col: 3, row: 1, note: "Power for the chip; about 1 mA while measuring." },
        { id: "gnd", label: "GND", kind: "ground", col: 3, row: 2, note: "Shared ground with your board." },
      ],
      links: [
        { from: "air", to: "hum", kind: "physical", label: "moisture" },
        { from: "air", to: "ntc", kind: "physical", label: "heat" },
        { from: "hum", to: "mcu", kind: "analog" },
        { from: "ntc", to: "mcu", kind: "analog" },
        { from: "mcu", to: "data", kind: "data", label: "1 wire", both: true },
        { from: "vcc", to: "mcu", kind: "power" },
        { from: "mcu", to: "gnd", kind: "ground" },
      ],
      steps: DHT_STEPS_11,
    },
    facts: [
      { label: "Humidity", value: "20–80 % RH, ±5 %" },
      { label: "Temperature", value: "0–50 °C, ±2 °C" },
      { label: "Supply", value: "3–5.5 V" },
      { label: "Interface", value: "Single wire" },
      { label: "Sampling", value: "1 reading / s" },
      { label: "Size", value: "15.5 × 12 × 5.5 mm" },
    ],
    experiment: { title: "Room climate logger", idea: "Read temperature and humidity every two seconds and print them, then breathe on the grille and watch the humidity jump and settle back." },
    docs: "/docs/hardware-knowledge/dht11",
    tags: ["dht11", "humidity", "temperature", "climate", "single-wire", "sensor"],
  },

  {
    id: "hc-sr04",
    name: "HC-SR04 ultrasonic distance",
    aka: ["ultrasonic sensor", "sonar module", "HC SR04"],
    group: "sensors",
    rank: 2,
    summary: "Two 'eyes' that ping with sound you can't hear and time the echo. Measures 2 cm to 4 m, and makes a robot stop before the wall.",
    size: { w: 45, h: 20, d: 13.6 },
    solids: [
      pcb(45, 20, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "cyl", id: "tx", cx: 10, cy: 10, r: 8, d: 12, z: 1.6, top: "radial-gradient(circle,#1f2124 0 42%,#8c9198 46%,#b7bcc3 60%,#8c9198)", side: "#9aa0a7", fill: "#8c9198", segments: 24 },
      { kind: "cyl", id: "rx", cx: 35, cy: 10, r: 8, d: 12, z: 1.6, top: "radial-gradient(circle,#1f2124 0 42%,#8c9198 46%,#b7bcc3 60%,#8c9198)", side: "#9aa0a7", fill: "#8c9198", segments: 24 },
      { kind: "box", id: "xtal", x: 19.3, y: 2.1, w: 6.4, h: 2.6, d: 2.6, z: 1.6, top: MATERIAL.steel, side: MATERIAL.steelSide, radius: 1.3 },
      chip(20, 15.2, 2, 1.2, undefined, 0.6),
      chip(23, 15.2, 2, 1.2, undefined, 0.6),
      chip(26, 15.2, 2, 1.2, undefined, 0.6),
      ...flatLegs(19.96, 20, 4, 8, 2.54, -1.2),
      ...pads(19.96, 18.7, 4, "x", 2.54, 0.6, 1.6),
      silk(22.5, 13.6, "HC-SR04", 2, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      silk(10, 19.3, "T", 1.3, MATERIAL.silk, { anchor: "middle" }),
      silk(35, 19.3, "R", 1.3, MATERIAL.silk, { anchor: "middle" }),
      silk(20.3, 17.9, "VCC", 0.8, MATERIAL.silk, { rotate: -90 }),
      silk(22.85, 17.9, "Trig", 0.8, MATERIAL.silk, { rotate: -90 }),
      silk(25.4, 17.9, "Echo", 0.8, MATERIAL.silk, { rotate: -90 }),
      silk(27.95, 17.9, "Gnd", 0.8, MATERIAL.silk, { rotate: -90 }),
    ],
    features: [
      { id: "tx", label: "Transmitter (T)", kind: "sensor", x: 2, y: 2, w: 16, h: 16, note: "Fires eight pulses at 40 kHz, a sound far above hearing, into a 15° cone." },
      { id: "rx", label: "Receiver (R)", kind: "sensor", x: 27, y: 2, w: 16, h: 16, note: "Listens for the echo coming back from the nearest hard surface." },
      { id: "xtal", label: "Crystal", kind: "chip", x: 19.3, y: 2.1, w: 6.4, h: 2.6, note: "Times the 40 kHz burst and the echo measurement." },
      { id: "pins", label: "VCC, Trig, Echo, GND", kind: "pins", x: 19.5, y: 20, w: 8.4, h: 8, note: "Trig in, Echo out. Echo swings to 5 V; on a 3.3 V board put a divider on it." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "5 V, about 15 mA" },
      { name: "Trig", role: "digital", note: "Hold high for 10 µs to start a measurement" },
      { name: "Echo", role: "digital", note: "Goes high for as long as the sound took to return; 5 V logic" },
      { name: "GND", role: "ground", note: "Ground" },
    ],
    circuit: {
      blocks: [
        { id: "trig", label: "Trig", sub: "10 µs pulse in", kind: "pin", col: 0, row: 0, note: "Your board starts each measurement here." },
        { id: "mcu", label: "Controller", sub: "times the burst", kind: "ic", col: 1, row: 0, note: "A small microcontroller that fires the burst and counts until the echo." },
        { id: "drv", label: "Driver", sub: "MAX232, ±10 V", kind: "driver", col: 2, row: 0, note: "Borrowed from serial ports: it makes the ±10 V swing the transducer needs." },
        { id: "tx", label: "Transmitter", sub: "40 kHz, 8 pulses", kind: "sensor", col: 3, row: 0, note: "A piezo disc that rings at 40 kHz." },
        { id: "obj", label: "Object", sub: "2–400 cm away", kind: "world", col: 3, row: 1, note: "Hard, flat things reflect well; cloth and sharp angles swallow the ping." },
        { id: "rx", label: "Receiver", kind: "sensor", col: 3, row: 2, note: "A matching piezo that turns the faint echo into microvolts." },
        { id: "amp", label: "Amplifier", sub: "LM324", kind: "ic", col: 2, row: 2, note: "Boosts and filters the echo so the controller can see it." },
        { id: "echo", label: "Echo", sub: "pulse width out", kind: "pin", col: 0, row: 2, note: "High from the moment the ping leaves until the echo returns." },
        { id: "vcc", label: "VCC 5 V", kind: "power", col: 0, row: 1, note: "15 mA; the 3.3 V pin is not enough." },
      ],
      links: [
        { from: "trig", to: "mcu", kind: "signal" },
        { from: "mcu", to: "drv", kind: "signal", label: "8 pulses" },
        { from: "drv", to: "tx", kind: "power", label: "±10 V" },
        { from: "tx", to: "obj", kind: "sound", label: "ping" },
        { from: "obj", to: "rx", kind: "sound", label: "echo" },
        { from: "rx", to: "amp", kind: "analog" },
        { from: "amp", to: "mcu", kind: "signal", label: "heard it" },
        { from: "mcu", to: "echo", kind: "signal", label: "high while waiting" },
        { from: "vcc", to: "mcu", kind: "power" },
      ],
      steps: [
        "Your board holds Trig high for 10 µs; the controller fires eight 40 kHz pulses through the driver into the transmitter.",
        "Echo goes high the moment the burst leaves. The sound crosses the room, bounces off the nearest object and comes back.",
        "The receiver hears the echo; the amplifier cleans it up and the controller pulls Echo low.",
        "Distance = Echo high time × 0.0343 cm/µs ÷ 2. No echo within 38 ms means nothing in range.",
      ],
    },
    facts: [
      { label: "Range", value: "2–400 cm" },
      { label: "Resolution", value: "3 mm" },
      { label: "Beam", value: "15°" },
      { label: "Supply", value: "5 V, 15 mA" },
      { label: "Interface", value: "Trig / Echo pulses" },
      { label: "Size", value: "45 × 20 × 15 mm" },
    ],
    experiment: { title: "Parking sensor", idea: "Print the distance ten times a second, then make a buzzer beep faster the closer your hand gets." },
    docs: "/docs/hardware-knowledge/hc-sr04",
    tags: ["hc-sr04", "ultrasonic", "distance", "sonar", "range", "obstacle", "sensor"],
  },

  {
    id: "pir",
    name: "PIR motion sensor (HC-SR501)",
    aka: ["HC-SR501", "passive infrared", "motion detector"],
    group: "sensors",
    rank: 3,
    summary: "The white dome from burglar alarms. It sees body heat move across its view and raises one pin for a few seconds. No moving parts, almost no current.",
    size: { w: 32, h: 24, d: 13.3 },
    solids: [
      pcb(32, 24, MATERIAL.pcbGreen, MATERIAL.pcbGreenEdge),
      { kind: "cyl", cx: 16, cy: 12, r: 11.8, d: 1.2, z: 1.6, top: "#f3f4f6", side: "#c9ccd1", segments: 28 },
      { kind: "dome", id: "lens", cx: 16, cy: 12, r: 11.5, d: 10.5, z: 2.8, color: "#f1f2f4" },
      ...trimPot(0.5, 0.5, 5, "#d9772b", "pot-sens"),
      ...trimPot(0.5, 18.5, 5, "#d9772b", "pot-time"),
      { kind: "pins", x: 29, y: 8.19, count: 3, pitch: 2.54, dir: "y", len: -9, z: 0 },
      ...pads(30.27, 9.46, 3, "y", 2.54, 0.7, 1.6),
      { kind: "pins", x: 26.8, y: 0.4, count: 3, pitch: 2.54, dir: "x", len: 5, z: 1.6, size: 0.6 },
      { kind: "box", x: 29.3, y: 0.3, w: 2.6, h: 2.8, d: 5.5, z: 1.6, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.3 },
      chip(24.5, 19.2, 2.4, 1.4, undefined, 0.6),
      chip(27.5, 19.2, 2.4, 1.4, undefined, 0.6),
      silk(31.2, 9.8, "+", 1.1, MATERIAL.silk, { anchor: "end" }),
      silk(31.3, 15.3, "−", 1.1, MATERIAL.silk, { anchor: "end" }),
      silk(27.8, 22.9, "SR501", 1.1, MATERIAL.silk, { anchor: "middle" }),
      silk(26.6, 4.6, "H", 0.9, MATERIAL.silk),
      silk(32.1, 4.6, "L", 0.9, MATERIAL.silk, { anchor: "end" }),
    ],
    features: [
      { id: "lens", label: "Fresnel lens dome", kind: "sensor", x: 4.5, y: 0.5, w: 23, h: 23, note: "Dozens of small lenses focus body heat from a 110° field onto the pyroelectric element underneath. Nothing inside moves." },
      { id: "pot-sens", label: "Sensitivity trimmer", kind: "mechanical", x: 0.5, y: 0.5, w: 5, h: 5, note: "Turn clockwise for longer reach, up to about 7 m." },
      { id: "pot-time", label: "Time-delay trimmer", kind: "mechanical", x: 0.5, y: 18.5, w: 5, h: 5, note: "How long OUT stays high after motion: from about 3 s to 5 min." },
      { id: "pins", label: "VCC, OUT, GND", kind: "pins", x: 29, y: 8.2, w: 2.6, h: 7.6, note: "Pins face down, away from the lens. VCC takes 5–20 V; OUT is 3.3 V logic." },
      { id: "jumper", label: "Trigger-mode jumper", kind: "other", x: 26.8, y: 0.3, w: 5.2, h: 2.8, note: "H (default): retriggers while motion continues. L: fires once per delay period, then waits." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "5–20 V; a regulator on board makes 3.3 V" },
      { name: "OUT", role: "digital", note: "3.3 V while motion is seen, 0 V otherwise" },
      { name: "GND", role: "ground", note: "Ground" },
    ],
    circuit: {
      blocks: [
        { id: "body", label: "Warm body moving", sub: "infrared", kind: "world", col: 0, row: 1, note: "People and animals glow in infrared. A still scene cancels out; movement is what registers." },
        { id: "lens", label: "Fresnel lens", sub: "focuses the heat", kind: "sensor", col: 1, row: 1, note: "Splits the view into zones; crossing a zone edge makes the signal." },
        { id: "pyro", label: "Pyro element", sub: "two slices, opposed", kind: "sensor", col: 2, row: 1, note: "Two crystal slices wired against each other: steady heat cancels, a change makes microvolts." },
        { id: "vcc", label: "VCC 5–20 V", kind: "power", col: 1, row: 0, note: "Almost any supply works; the board drops it to 3.3 V." },
        { id: "reg", label: "3.3 V regulator", sub: "HT7133", kind: "regulator", col: 2, row: 0, note: "Powers the chip; also why OUT is 3.3 V logic." },
        { id: "biss", label: "BISS0001", sub: "amp + timer", kind: "ic", col: 3, row: 0, note: "Amplifies the tiny signal, compares it with the sensitivity setting and runs the hold timer." },
        { id: "pots", label: "Trimmers", sub: "range, hold time", kind: "passive", col: 2, row: 2, note: "The two orange potentiometers." },
        { id: "out", label: "OUT", sub: "3.3 V logic", kind: "pin", col: 3, row: 1, note: "High for the hold time whenever motion is detected." },
      ],
      links: [
        { from: "body", to: "lens", kind: "light", label: "infrared" },
        { from: "lens", to: "pyro", kind: "light" },
        { from: "pyro", to: "biss", kind: "analog", label: "µV changes" },
        { from: "vcc", to: "reg", kind: "power" },
        { from: "reg", to: "biss", kind: "power", label: "3.3 V" },
        { from: "pots", to: "biss", kind: "analog" },
        { from: "biss", to: "out", kind: "signal", label: "HIGH on motion" },
      ],
      steps: [
        "Warm bodies radiate infrared. The lens splits the view into many zones and focuses each onto the pyroelectric element.",
        "The element has two halves wired against each other. A steady scene cancels out; a warm body crossing zones makes a small changing voltage.",
        "The BISS0001 amplifies that, compares it with the sensitivity setting and starts its timer.",
        "OUT goes to 3.3 V for the delay time. The jumper picks whether continued motion keeps extending it (H) or it fires once (L). Allow a minute to settle after power-up.",
      ],
    },
    facts: [
      { label: "Range", value: "up to 7 m" },
      { label: "Field of view", value: "~110°" },
      { label: "Supply", value: "5–20 V, 65 µA" },
      { label: "Output", value: "3.3 V logic" },
      { label: "Hold time", value: "3 s – 5 min" },
      { label: "Warm-up", value: "~60 s" },
    ],
    experiment: { title: "Motion night-light", idea: "Light an LED while OUT is high, then try both jumper settings and the two trimmers and note how long the light stays on." },
    docs: "/docs/hardware-knowledge/pir-sensor",
    tags: ["pir", "hc-sr501", "motion", "infrared", "presence", "alarm", "sensor"],
  },

  {
    id: "dht22",
    name: "DHT22 humidity & temperature",
    aka: ["AM2302 chip", "DHT-22", "white climate sensor"],
    group: "sensors",
    rank: 4,
    summary: "The DHT11's grown-up sibling: the same one-wire conversation, but ±0.5 °C, full 0–100 % humidity and readings below freezing.",
    size: { w: 15.1, h: 35.1, d: 7.75 },
    solids: [...dhtHousing("DHT22"), ...flatLegs(3.74, 25.1, 4, 10, 2.54, 3.5)],
    features: [
      { id: "slots", label: "Ventilation slots", kind: "sensor", x: 2, y: 4.5, w: 11, h: 15.5, note: "Air passes through to the capacitive humidity element and the thermistor behind them." },
      { id: "hole", label: "Mounting hole", kind: "mechanical", x: 6, y: 0.8, w: 3, h: 3, note: "Screw it to a wall or a case; the sensor is on the slotted face." },
      { id: "legs", label: "Legs: VCC, DATA, NC, GND", kind: "pins", x: 3.3, y: 25.1, w: 8.5, h: 10, note: "Same order as the DHT11. Needs a 10 kΩ pull-up on DATA; modules include it." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3–6 V" },
      { name: "DATA", role: "data", note: "Single wire, 40-bit frames; pull-up needed" },
      { name: "NC", role: "other", note: "Not connected" },
      { name: "GND", role: "ground", note: "Ground" },
    ],
    circuit: {
      blocks: [
        { id: "air", label: "Air", sub: "humidity, temperature", kind: "world", col: 0, row: 0, note: "The air that passes through the slots." },
        { id: "hum", label: "Humidity element", sub: "capacitive", kind: "sensor", col: 1, row: 0, note: "A capacitor whose dielectric soaks up moisture; its value tracks humidity." },
        { id: "ntc", label: "Thermistor", sub: "NTC, ±0.5 °C", kind: "sensor", col: 1, row: 1, note: "A precision thermistor; also used to correct the humidity reading." },
        { id: "mcu", label: "Sensor chip", sub: "8-bit, calibrated", kind: "ic", col: 2, row: 0, note: "Measures both, applies factory calibration and answers on the data wire." },
        { id: "data", label: "DATA", sub: "one wire, both ways", kind: "pin", col: 3, row: 0, note: "Request and reply share this wire." },
        { id: "vcc", label: "VCC", sub: "3.3–6 V", kind: "power", col: 3, row: 1, note: "About 1.5 mA while measuring." },
        { id: "gnd", label: "GND", kind: "ground", col: 3, row: 2, note: "Shared ground with your board." },
      ],
      links: [
        { from: "air", to: "hum", kind: "physical", label: "moisture" },
        { from: "air", to: "ntc", kind: "physical", label: "heat" },
        { from: "hum", to: "mcu", kind: "analog" },
        { from: "ntc", to: "mcu", kind: "analog" },
        { from: "mcu", to: "data", kind: "data", label: "1 wire", both: true },
        { from: "vcc", to: "mcu", kind: "power" },
        { from: "mcu", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Your board pulls DATA low for about 1 ms to ask for a reading, then releases the line.",
        "The chip measures the capacitive humidity element and the thermistor, and applies its factory calibration.",
        "It answers with 40 bits: humidity ×10, temperature ×10 (with a sign bit) and a checksum.",
        "One reading every two seconds at most; the sensor itself sets the pace.",
      ],
    },
    facts: [
      { label: "Humidity", value: "0–100 % RH, ±2–5 %" },
      { label: "Temperature", value: "−40–80 °C, ±0.5 °C" },
      { label: "Supply", value: "3.3–6 V" },
      { label: "Interface", value: "Single wire" },
      { label: "Sampling", value: "1 reading / 2 s" },
      { label: "Size", value: "15.1 × 25.1 × 7.7 mm" },
    ],
    experiment: { title: "Window-sill test", idea: "Read it every two seconds, then move it from the desk to a cold window sill and watch both numbers drift; compare with a DHT11 side by side." },
    tags: ["dht22", "am2302", "humidity", "temperature", "climate", "sensor"],
  },

  {
    id: "am2302",
    name: "AM2302 wired humidity & temperature",
    aka: ["wired DHT22", "AM2302 cable sensor"],
    group: "sensors",
    rank: 5,
    summary: "The DHT22 with its wires already attached and the pull-up resistor inside: the same sensor, ready to tape wherever the air is.",
    size: { w: 15.1, h: 45.1, d: 7.75 },
    solids: [
      ...dhtHousing("AM2302"),
      wire(4.85, 25.1, 0.9, 20, "#d12d2d", 3.2),
      wire(7.1, 25.1, 0.9, 20, "#1b1c1f", 3.2),
      wire(9.35, 25.1, 0.9, 20, "#f5d90a", 3.2),
      { kind: "box", x: 3.6, y: 25.1, w: 7.9, h: 3, d: 2.4, z: 2.6, top: "#26272b", side: "#111214", radius: 0.8 },
    ],
    features: [
      { id: "slots", label: "Ventilation slots", kind: "sensor", x: 2, y: 4.5, w: 11, h: 15.5, note: "Same capacitive humidity element and thermistor as the DHT22 behind them." },
      { id: "hole", label: "Mounting hole", kind: "mechanical", x: 6, y: 0.8, w: 3, h: 3, note: "Hang it where you want to measure; the wires do the rest." },
      { id: "wires", label: "Leads: red, black, yellow", kind: "connector", x: 4.3, y: 25.1, w: 6.5, h: 20, note: "Red VCC, black GND, yellow DATA. The pull-up resistor is already inside, so three wires straight to the board." },
    ],
    pins: [
      { name: "Red", role: "power", note: "VCC, 3.3–5.5 V" },
      { name: "Yellow", role: "data", note: "DATA; pull-up already fitted" },
      { name: "Black", role: "ground", note: "GND" },
    ],
    circuit: {
      blocks: [
        { id: "air", label: "Air", sub: "humidity, temperature", kind: "world", col: 0, row: 0, note: "The air at the end of the cable." },
        { id: "hum", label: "Humidity element", sub: "capacitive", kind: "sensor", col: 1, row: 0, note: "Same element as the DHT22." },
        { id: "ntc", label: "Thermistor", sub: "NTC, ±0.5 °C", kind: "sensor", col: 1, row: 1, note: "Same thermistor as the DHT22." },
        { id: "mcu", label: "Sensor chip", sub: "8-bit, calibrated", kind: "ic", col: 2, row: 0, note: "Measures, calibrates, answers." },
        { id: "pull", label: "Pull-up", sub: "built in", kind: "passive", col: 2, row: 1, note: "Holds the data wire high between bits so you don't need your own resistor." },
        { id: "data", label: "Yellow wire", sub: "DATA", kind: "pin", col: 3, row: 0, note: "To any digital pin." },
        { id: "vcc", label: "Red wire", sub: "VCC", kind: "power", col: 3, row: 1, note: "3.3–5.5 V." },
        { id: "gnd", label: "Black wire", sub: "GND", kind: "ground", col: 3, row: 2, note: "Ground." },
      ],
      links: [
        { from: "air", to: "hum", kind: "physical", label: "moisture" },
        { from: "air", to: "ntc", kind: "physical", label: "heat" },
        { from: "hum", to: "mcu", kind: "analog" },
        { from: "ntc", to: "mcu", kind: "analog" },
        { from: "mcu", to: "data", kind: "data", label: "1 wire", both: true },
        { from: "pull", to: "data", kind: "power" },
        { from: "vcc", to: "mcu", kind: "power" },
        { from: "mcu", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Wire red to VCC, black to GND and yellow to a digital pin; nothing else is needed.",
        "Your board pulls the data wire low for about 1 ms; the built-in pull-up lets it float high again.",
        "The chip measures humidity and temperature and sends 40 bits back on the yellow wire.",
        "Keep the cable under a couple of metres, read no more than every two seconds, and the readings match a DHT22 exactly.",
      ],
    },
    facts: [
      { label: "Humidity", value: "0–100 % RH, ±2–5 %" },
      { label: "Temperature", value: "−40–80 °C, ±0.5 °C" },
      { label: "Supply", value: "3.3–5.5 V" },
      { label: "Interface", value: "Single wire, pull-up inside" },
      { label: "Cable", value: "3 wires, ~20 cm" },
      { label: "Size", value: "15.1 × 25.1 × 7.7 mm" },
    ],
    experiment: { title: "Inside and out", idea: "Hang it outside a window on its wires, read every two seconds, and chart the difference against a DHT22 indoors." },
    tags: ["am2302", "dht22", "wired", "humidity", "temperature", "sensor"],
  },

  {
    id: "ldr",
    name: "Light-dependent resistor",
    aka: ["LDR", "photoresistor", "photocell", "CdS cell"],
    group: "sensors",
    rank: 6,
    summary: "A resistor that gives way to light: megohms in the dark, a few hundred ohms in the sun. One fixed resistor beside it and an analog pin can read the room.",
    size: { w: 5.5, h: 5.5, d: 2.2 },
    solids: [
      { kind: "cyl", id: "face", cx: 2.75, cy: 2.75, r: 2.5, d: 2, z: 0, top: "#d9a066", side: "#b07a3f", segments: 24 },
      serpentine(2.75, 2.75, 2.5),
      { kind: "pins", x: -0.65, y: 1.05, count: 2, pitch: 3.4, dir: "x", len: -8, z: 0, size: 0.5 },
    ],
    features: [
      { id: "face", label: "Light-sensitive track", kind: "sensor", x: 0.25, y: 0.25, w: 5, h: 5, note: "A snake of cadmium sulphide between two combs. Light frees charge carriers in it and its resistance falls, from megohms in the dark to a few hundred ohms in sunlight." },
      { id: "legs", label: "Two legs", kind: "pins", x: 0.5, y: 1.2, w: 4.5, h: 3.1, note: "No polarity. Wire one leg to 5 V and the other to an analog pin plus a 10 kΩ resistor to GND." },
    ],
    pins: [
      { name: "Leg 1", role: "analog", note: "Either leg; to VCC" },
      { name: "Leg 2", role: "analog", note: "To an analog pin, with 10 kΩ to GND" },
    ],
    circuit: {
      blocks: [
        { id: "light", label: "Light", sub: "lux", kind: "world", col: 0, row: 0, note: "Daylight, a lamp, a shadow passing: the amount of light on the face." },
        { id: "ldr", label: "CdS track", sub: "MΩ dark, ~300 Ω sun", kind: "sensor", col: 1, row: 0, note: "Resistance falls as light increases. Every part differs: calibrate in place." },
        { id: "vcc", label: "5 V", kind: "power", col: 0, row: 1, note: "The top of the divider." },
        { id: "node", label: "Junction", sub: "→ analog pin A0", kind: "pin", col: 2, row: 0, note: "The voltage here rises with light; A0 reads it as 0–1023." },
        { id: "res", label: "10 kΩ resistor", sub: "yours, to GND", kind: "passive", col: 2, row: 1, note: "The fixed half of the divider. Change it to shift the sensitive range." },
        { id: "gnd", label: "GND", kind: "ground", col: 2, row: 2, note: "Ground." },
      ],
      links: [
        { from: "light", to: "ldr", kind: "light" },
        { from: "vcc", to: "ldr", kind: "power" },
        { from: "ldr", to: "node", kind: "analog" },
        { from: "node", to: "res", kind: "power" },
        { from: "res", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Light frees charge carriers in the CdS track, so its resistance falls as it gets brighter.",
        "With a fixed 10 kΩ resistor it forms a voltage divider: the junction voltage rises with light.",
        "An analog pin reads that voltage, 0–1023. Calibrate against the room, not a datasheet: every LDR differs.",
        "It responds in tens of milliseconds, slower in the dark; fine for day/night, not for data links.",
      ],
    },
    facts: [
      { label: "Dark resistance", value: "~1 MΩ" },
      { label: "Bright resistance", value: "200 Ω – 1 kΩ" },
      { label: "Peak sensitivity", value: "~540 nm (green)" },
      { label: "Rating", value: "100 mW" },
      { label: "Interface", value: "Analog divider" },
      { label: "Size", value: "Ø5 mm" },
    ],
    experiment: { title: "Automatic night light", idea: "Read the divider on A0 and print it, then switch an LED on below a threshold you choose by covering it with your hand." },
    tags: ["ldr", "photoresistor", "photocell", "light", "cds", "analog", "sensor"],
  },

  {
    id: "ds18b20",
    name: "DS18B20 temperature probe",
    aka: ["Dallas temperature sensor", "1-Wire thermometer", "DS18B20 waterproof"],
    group: "sensors",
    rank: 7,
    summary: "A thermometer in a transistor case. Digital, ±0.5 °C, and dozens can share one wire, each with its own serial number. The waterproof version is this chip in a steel probe.",
    size: { w: 5, h: 4.3, d: 5.2 },
    plan: "front",
    solids: [
      { kind: "cyl", id: "body", cx: 2.5, cy: 2.1, r: 2.35, d: 5.2, z: 0, top: MATERIAL.plasticBlack, side: "#141517", segments: 20 },
      { kind: "box", x: 0.2, y: 3.5, w: 4.6, h: 0.8, d: 5.2, z: 0, top: MATERIAL.plasticBlack, side: "#1b1c1f", radius: 0.2 },
      { kind: "pins", x: 0.6, y: 1.47, count: 3, pitch: 1.27, dir: "x", len: -10, z: 0, size: 0.45 },
    ],
    features: [
      { id: "body", label: "TO-92 body", kind: "chip", x: 0.15, y: 0, w: 4.7, h: 5.2, note: "The whole sensor is inside: a temperature core, a 12-bit converter and a 64-bit serial number burned in at the factory." },
      { id: "gnd", label: "GND (left)", kind: "pin", x: 0.8, y: 5.2, w: 0.8, h: 10, note: "Ground, with the flat face towards you." },
      { id: "dq", label: "DQ (middle)", kind: "pin", x: 2.1, y: 5.2, w: 0.8, h: 10, note: "The 1-Wire data line. Add a 4.7 kΩ pull-up to VDD." },
      { id: "vdd", label: "VDD (right)", kind: "pin", x: 3.4, y: 5.2, w: 0.8, h: 10, note: "3–5.5 V. Tie it to GND for parasite power from DQ." },
    ],
    pins: [
      { name: "GND", role: "ground", note: "Ground" },
      { name: "DQ", role: "data", note: "1-Wire data; 4.7 kΩ pull-up; many sensors can share it" },
      { name: "VDD", role: "power", note: "3–5.5 V, or GND for parasite mode" },
    ],
    circuit: {
      blocks: [
        { id: "host", label: "DQ", sub: "1-Wire, one pin", kind: "pin", col: 0, row: 1, note: "Your board talks to every sensor on the wire through this single pin." },
        { id: "logic", label: "1-Wire logic", sub: "64-bit ROM address", kind: "ic", col: 1, row: 1, note: "Decodes commands and answers only when its own address is called." },
        { id: "core", label: "Temperature core", sub: "12-bit, ±0.5 °C", kind: "sensor", col: 2, row: 1, note: "A band-gap sensor and a counter that turns temperature into a 12-bit number." },
        { id: "world", label: "Surroundings", sub: "−55 to 125 °C", kind: "world", col: 3, row: 1, note: "Air, water, a heatsink: whatever the case touches." },
        { id: "pullup", label: "4.7 kΩ pull-up", sub: "yours, to VDD", kind: "passive", col: 0, row: 0, note: "Holds the wire high between pulses; without it nothing answers." },
        { id: "vdd", label: "VDD 3–5.5 V", kind: "power", col: 1, row: 0, note: "Normal power; parasite mode steals it from the data line instead." },
        { id: "scratch", label: "Scratchpad", sub: "9 bytes + CRC", kind: "ic", col: 2, row: 0, note: "Where the result waits until you read it." },
        { id: "gnd", label: "GND", kind: "ground", col: 1, row: 2, note: "Ground." },
      ],
      links: [
        { from: "host", to: "logic", kind: "data", label: "1 wire", both: true },
        { from: "world", to: "core", kind: "physical", label: "heat" },
        { from: "core", to: "scratch", kind: "data", label: "result" },
        { from: "scratch", to: "logic", kind: "data" },
        { from: "pullup", to: "host", kind: "power" },
        { from: "vdd", to: "logic", kind: "power" },
        { from: "logic", to: "gnd", kind: "ground" },
      ],
      steps: [
        "Your board resets the bus, then addresses this sensor by its unique 64-bit ROM code, so many can share one wire.",
        "Convert T starts a measurement; at 12 bits it takes 750 ms, less at lower resolution.",
        "The result lands in the scratchpad with a CRC; the host reads nine bytes and checks it.",
        "Temperature = raw ÷ 16 in °C. The waterproof version is this chip sealed in a steel probe on a cable.",
      ],
    },
    facts: [
      { label: "Range", value: "−55 to 125 °C" },
      { label: "Accuracy", value: "±0.5 °C (−10 to 85 °C)" },
      { label: "Resolution", value: "9–12 bit" },
      { label: "Supply", value: "3–5.5 V" },
      { label: "Interface", value: "1-Wire" },
      { label: "Package", value: "TO-92" },
    ],
    experiment: { title: "Many probes, one pin", idea: "Read one sensor and print its address, then add a second on the same wire and show both temperatures side by side." },
    tags: ["ds18b20", "1-wire", "onewire", "temperature", "probe", "dallas", "waterproof", "sensor"],
  },

  {
    id: "soil-moisture",
    name: "Soil moisture sensor",
    aka: ["hygrometer probe", "FC-28", "soil sensor"],
    group: "sensors",
    rank: 8,
    summary: "A two-pronged probe you push into a flowerpot and a small board that turns 'how well does the soil conduct' into a number and a wet/dry switch.",
    size: { w: 60, h: 40, d: 10.6 },
    solids: [
      pcb(12, 20, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "box", x: 12, y: 0.5, w: 48, h: 6.5, d: 1.6, top: MATERIAL.pcbBlue, side: MATERIAL.pcbBlueEdge, radius: 1 },
      { kind: "box", x: 12, y: 13, w: 48, h: 6.5, d: 1.6, top: MATERIAL.pcbBlue, side: MATERIAL.pcbBlueEdge, radius: 1 },
      { kind: "path", d: "M 14 1.6 h 44 v 4.3 h -44 z", fill: MATERIAL.gold, color: "#b08a3a", width: 0.2 },
      { kind: "path", d: "M 14 14.1 h 44 v 4.3 h -44 z", fill: MATERIAL.gold, color: "#b08a3a", width: 0.2 },
      ...maleHeader(1.5, 6.5, 2, "y", 1, false),
      silk(7.5, 4.2, "SOIL", 1.5, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      { kind: "box", x: 28, y: 24, w: 30, h: 16, d: 1.6, top: MATERIAL.pcbBlue, side: MATERIAL.pcbBlueEdge, radius: 1 },
      chip(42, 29, 5, 4, "LM393", 1.2, "lm393"),
      ...trimPot(30, 25.5, 6, "#1e5fbf", "pot"),
      smdLed(49, 26, "#ff3b3b", "led-pwr"),
      smdLed(49, 28.6, "#ff3b3b", "led-d0"),
      ...maleHeader(53.5, 27, 4, "y", 1, false),
      ...maleHeader(29, 33, 2, "y", 1, false),
      { kind: "path", d: "M 2.8 7.8 L 7 7.8 L 7 21 L 24 21 L 24 36.8 L 30.3 36.8", color: "#1b1c1f", width: 0.9, z: 1.9 },
      { kind: "path", d: "M 2.8 10.3 L 5.5 10.3 L 5.5 23 L 26 23 L 26 34.3 L 30.3 34.3", color: "#d12d2d", width: 0.9, z: 1.9 },
      silk(52.9, 28.6, "VCC", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(52.9, 31.1, "GND", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(52.9, 33.7, "D0", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(52.9, 36.2, "A0", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(42, 38.6, "LM393 MODULE", 1, MATERIAL.silk, { anchor: "middle" }),
    ],
    features: [
      { id: "tines", label: "Probe tines", kind: "sensor", x: 12, y: 0.5, w: 48, h: 19, note: "Two exposed tracks. Wet soil between them conducts better, so the resistance between the tines drops. Bare copper corrodes; gold-plated ones last longer." },
      { id: "pot", label: "Threshold trimmer", kind: "mechanical", x: 30, y: 25.5, w: 6, h: 6, note: "Sets the moisture level at which D0 switches." },
      { id: "lm393", label: "LM393 comparator", kind: "chip", x: 42, y: 29, w: 5, h: 4, note: "Compares the probe voltage with the trimmer and drives D0." },
      { id: "header", label: "VCC, GND, D0, A0", kind: "pins", x: 53.5, y: 27, w: 2.6, h: 10.2, note: "A0 gives the raw level to an analog pin; D0 is a wet/dry switch." },
      { id: "leds", label: "Power and D0 LEDs", kind: "led", x: 48.5, y: 25.4, w: 2.8, h: 4.6, note: "The first shows power; the second lights when D0 says 'wet'." },
      { id: "wires", label: "Probe leads", kind: "connector", x: 2, y: 7, w: 29, h: 30, note: "Two wires: to the module the probe is just a resistor that changes with moisture." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3–5 V" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "D0", role: "digital", note: "Low when wetter than the trimmer threshold" },
      { name: "A0", role: "analog", note: "Raw moisture level: dry ≈ 1023, wet ≈ 300" },
    ],
    circuit: {
      blocks: [
        { id: "soil", label: "Soil", sub: "water between tines", kind: "world", col: 0, row: 0, note: "Wet soil conducts; dry soil barely does." },
        { id: "probe", label: "Probe tines", sub: "resistance ↓ when wet", kind: "sensor", col: 1, row: 0, note: "The probe is simply a resistor made of soil." },
        { id: "div", label: "Divider", sub: "10 kΩ on module", kind: "passive", col: 2, row: 0, note: "Probe plus fixed resistor: a voltage that falls as the soil gets wetter." },
        { id: "a0", label: "A0", sub: "raw level", kind: "pin", col: 3, row: 0, note: "Read with analogRead; calibrate dry and wet for your soil." },
        { id: "cmp", label: "LM393", sub: "comparator", kind: "ic", col: 2, row: 1, note: "Flips D0 when the divider crosses the trimmer setting." },
        { id: "pot", label: "Threshold pot", kind: "passive", col: 1, row: 1, note: "Your 'dry enough' setting." },
        { id: "d0", label: "D0", sub: "wet / dry", kind: "pin", col: 3, row: 1, note: "A clean digital yes/no." },
        { id: "vcc", label: "VCC 3.3–5 V", kind: "power", col: 0, row: 1, note: "Power the probe only while reading to slow corrosion." },
      ],
      links: [
        { from: "soil", to: "probe", kind: "physical", label: "moisture" },
        { from: "vcc", to: "probe", kind: "power" },
        { from: "probe", to: "div", kind: "analog" },
        { from: "div", to: "a0", kind: "analog", label: "0–VCC" },
        { from: "div", to: "cmp", kind: "analog" },
        { from: "pot", to: "cmp", kind: "analog" },
        { from: "cmp", to: "d0", kind: "signal" },
      ],
      steps: [
        "Current passes from one tine to the other through the soil; the wetter it is, the lower the resistance.",
        "On the module the probe forms a divider with a fixed resistor, so A0 drops as the soil gets wetter: dry ≈ 1023, wet ≈ 300 on a 10-bit ADC.",
        "The LM393 compares that voltage with the trimmer and pulls D0 low past the threshold; the second LED shows it.",
        "Power the probe only while reading (use a digital pin as its VCC) to slow corrosion of the tines.",
      ],
    },
    facts: [
      { label: "Output", value: "Analog + digital" },
      { label: "Supply", value: "3.3–5 V" },
      { label: "Probe", value: "60 × 20 mm" },
      { label: "Reading", value: "dry ≈ 1023, wet ≈ 300" },
      { label: "Threshold", value: "Trimmer on module" },
      { label: "Caveat", value: "Corrodes if powered constantly" },
    ],
    experiment: { title: "Plant that asks for water", idea: "Read A0 every minute and print it, turn an LED on when it climbs above your 'dry' number, then water the pot and watch it fall." },
    tags: ["soil", "moisture", "hygrometer", "plant", "water", "analog", "lm393", "sensor"],
  },

  {
    id: "mq2",
    name: "MQ-2 gas & smoke sensor",
    aka: ["MQ2", "smoke sensor", "LPG sensor"],
    group: "sensors",
    rank: 9,
    summary: "A heated bead under a steel mesh that conducts better when flammable gas or smoke touches it. Gives a rising analog level and a threshold switch.",
    size: { w: 32, h: 20, d: 17.6 },
    solids: [
      pcb(32, 20, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      { kind: "cyl", cx: 11, cy: 10, r: 8, d: 2, z: 1.6, top: MATERIAL.plasticBlack, side: "#111214", segments: 24 },
      { kind: "cyl", id: "can", cx: 11, cy: 10, r: 7.6, d: 14, z: 3.6, top: "radial-gradient(circle,#4b4f55 0 55%,#9aa0a7 58%,#8c9198)", side: "#aeb3ba", fill: "#8c9198", segments: 24 },
      chip(21, 3, 5, 4, "LM393", 1.2, "lm393"),
      ...trimPot(20.5, 9, 5.5, "#1e5fbf", "pot"),
      smdLed(27.5, 3.5, "#ff3b3b", "led-pwr"),
      smdLed(27.5, 6.5, "#ff3b3b", "led-d0"),
      { kind: "box", x: 32, y: 8.2, w: 2.5, h: 10.2, d: 2.5, z: 0.5, top: MATERIAL.plasticBlack, side: "#111214", radius: 0.3 },
      ...[9.46, 12, 14.54, 17.08].map((y) => wire(32, y - 0.32, 7, 0.64, MATERIAL.tin, 1.2)),
      silk(11, 19.4, "MQ-2", 1.3, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      silk(31.4, 9.8, "VCC", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(31.4, 12.35, "GND", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(31.4, 14.9, "D0", 0.85, MATERIAL.silk, { anchor: "end" }),
      silk(31.4, 17.45, "A0", 0.85, MATERIAL.silk, { anchor: "end" }),
    ],
    features: [
      { id: "can", label: "Sensor can", kind: "sensor", x: 3, y: 2, w: 16, h: 16, note: "A heated tin-oxide bead under a steel mesh. Flammable gas or smoke changes its conductivity. The heater draws 150 mA and gets warm to the touch." },
      { id: "pot", label: "Threshold trimmer", kind: "mechanical", x: 20.5, y: 9, w: 5.5, h: 5.5, note: "Sets the level at which D0 switches." },
      { id: "lm393", label: "LM393 comparator", kind: "chip", x: 21, y: 3, w: 5, h: 4, note: "Compares the sensor voltage with the trimmer and drives D0." },
      { id: "leds", label: "Power and D0 LEDs", kind: "led", x: 27, y: 3, w: 2.8, h: 4.8, note: "Power, and 'gas above threshold'." },
      { id: "pins", label: "VCC, GND, D0, A0", kind: "pins", x: 32, y: 8.2, w: 7, h: 10.2, note: "A0 for the level, D0 for the alarm. VCC must be 5 V: the heater needs it." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "5 V, ~150 mA (the heater)" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "D0", role: "digital", note: "Low when gas is above the threshold" },
      { name: "A0", role: "analog", note: "Gas level, rises with concentration" },
    ],
    circuit: {
      blocks: [
        { id: "gas", label: "Gas or smoke", sub: "LPG, CH₄, CO, H₂", kind: "world", col: 0, row: 0, note: "Molecules that react on the hot bead." },
        { id: "bead", label: "SnO₂ bead", sub: "conducts more in gas", kind: "sensor", col: 1, row: 0, note: "Tin dioxide: its resistance drops as gas reacts on its hot surface." },
        { id: "heater", label: "Heater coil", sub: "5 V, 150 mA", kind: "passive", col: 1, row: 1, note: "Keeps the bead at a few hundred °C; cold, it senses nothing." },
        { id: "vcc", label: "VCC 5 V", kind: "power", col: 0, row: 1, note: "The heater is why this needs a real 5 V supply." },
        { id: "load", label: "Load resistor", sub: "RL ≈ 5 kΩ", kind: "passive", col: 2, row: 0, note: "With the bead it forms a divider; A0 is the midpoint." },
        { id: "a0", label: "A0", sub: "rises with gas", kind: "pin", col: 3, row: 0, note: "Read it as a trend; calibrate in clean air first." },
        { id: "cmp", label: "LM393", sub: "comparator", kind: "ic", col: 2, row: 1, note: "Compares A0 with the trimmer." },
        { id: "pot", label: "Threshold pot", kind: "passive", col: 2, row: 2, note: "Your alarm level." },
        { id: "d0", label: "D0", sub: "alarm", kind: "pin", col: 3, row: 1, note: "Low when above threshold." },
      ],
      links: [
        { from: "gas", to: "bead", kind: "physical" },
        { from: "vcc", to: "heater", kind: "power" },
        { from: "heater", to: "bead", kind: "physical", label: "heat" },
        { from: "bead", to: "load", kind: "analog" },
        { from: "load", to: "a0", kind: "analog" },
        { from: "load", to: "cmp", kind: "analog" },
        { from: "pot", to: "cmp", kind: "analog" },
        { from: "cmp", to: "d0", kind: "signal" },
      ],
      steps: [
        "A coil heats the tin-oxide bead to a few hundred °C; cold, it senses nothing. Give it a minute or two, and a day's burn-in the first time.",
        "Flammable gas or smoke molecules react on the hot surface and the bead conducts better.",
        "The bead and a load resistor divide 5 V; A0 rises with concentration. Calibrate in clean air for a baseline.",
        "The LM393 compares A0 with the trimmer and pulls D0 low above the threshold; the second LED lights.",
      ],
    },
    facts: [
      { label: "Detects", value: "LPG, propane, methane, CO, smoke" },
      { label: "Range", value: "300–10 000 ppm" },
      { label: "Supply", value: "5 V, ~150 mA" },
      { label: "Warm-up", value: "1–2 min (24 h burn-in)" },
      { label: "Output", value: "Analog + digital" },
      { label: "Size", value: "32 × 20 mm" },
    ],
    experiment: { title: "Smoke alarm", idea: "Log A0 in clean air for a minute, then hold a blown-out match near the mesh and sound a buzzer when A0 climbs 20 % above the baseline." },
    tags: ["mq2", "mq-2", "gas", "smoke", "lpg", "methane", "alarm", "sensor"],
  },

  {
    id: "mpu6050",
    name: "MPU-6050 motion sensor (GY-521)",
    aka: ["GY-521", "IMU", "accelerometer gyroscope"],
    group: "sensors",
    rank: 10,
    summary: "Six axes of motion on a thumbnail: which way is down, how fast you're turning. The sensor inside phones, drones and self-balancing robots, over two I2C wires.",
    size: { w: 21, h: 16, d: 4.1 },
    solids: [
      pcb(21, 16, MATERIAL.pcbBlue, MATERIAL.pcbBlueEdge),
      chip(8.5, 6, 4, 4, "6050", 0.9, "imu"),
      chip(14, 3, 2.9, 1.6, undefined, 1.1, "reg"),
      smdLed(3.5, 3.2, "#3ddc84", "led-pwr"),
      { kind: "box", x: 3, y: 7, w: 1.6, h: 0.8, d: 0.6, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 3, y: 8.6, w: 1.6, h: 0.8, d: 0.6, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 14.5, y: 9, w: 1.6, h: 0.8, d: 0.6, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      ...maleHeader(0.34, 13, 8, "x", 1, true),
      mountHole(2.5, 2.5, 1.5),
      mountHole(18.5, 2.5, 1.5),
      silk(10.5, 11.7, "GY-521", 1.2, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      ...["VCC", "GND", "SCL", "SDA", "XDA", "XCL", "AD0", "INT"].map((name, i) => silk(0.34 + 1.27 + i * 2.54 + 0.3, 12.6, name, 0.75, MATERIAL.silk, { rotate: -90 })),
      { kind: "path", d: "M 15 8.5 l 3.2 0 M 17.5 7.9 l 0.7 0.6 l -0.7 0.6 M 15 8.5 l 0 -3.2 M 14.4 6 l 0.6 -0.7 l 0.6 0.7", color: MATERIAL.silk, width: 0.25 },
      silk(18.6, 9.3, "X", 0.9, MATERIAL.silk),
      silk(15.6, 5.6, "Y", 0.9, MATERIAL.silk),
    ],
    features: [
      { id: "imu", label: "MPU-6050", kind: "chip", x: 8.5, y: 6, w: 4, h: 4, note: "A 3-axis accelerometer and 3-axis gyroscope on one die, plus a small processor that can fuse them into orientation." },
      { id: "header", label: "VCC, GND, SCL, SDA, XDA, XCL, AD0, INT", kind: "pins", x: 0.34, y: 13, w: 20.3, h: 2.54, note: "Only four are needed to start: VCC, GND, SCL, SDA." },
      { id: "reg", label: "3.3 V regulator", kind: "chip", x: 14, y: 3, w: 2.9, h: 1.6, note: "Lets you feed 5 V on VCC; the chip itself runs at 3.3 V." },
      { id: "led-pwr", label: "Power LED", kind: "led", x: 3, y: 2.7, w: 2.6, h: 1.8, note: "Lit whenever VCC is present." },
      { id: "holes", label: "Mounting holes", kind: "mechanical", x: 1, y: 1, w: 3, h: 3, note: "Two M3 holes; mount it firmly, or it measures the wobble of its wires." },
      { id: "axes", label: "Axis marking", kind: "other", x: 14.2, y: 4.8, w: 5, h: 4.8, note: "+X and +Y as printed; +Z points up out of the board. Readings follow this frame." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3–5 V" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "SCL", role: "clock", note: "I2C clock" },
      { name: "SDA", role: "data", note: "I2C data" },
      { name: "XDA", role: "data", note: "Auxiliary I2C data, for a magnetometer" },
      { name: "XCL", role: "clock", note: "Auxiliary I2C clock" },
      { name: "AD0", role: "digital", note: "Address select: low 0x68, high 0x69" },
      { name: "INT", role: "digital", note: "Interrupt: data ready, motion detected" },
    ],
    circuit: {
      blocks: [
        { id: "motion", label: "Motion", sub: "tilt, shake, turn", kind: "world", col: 0, row: 0, note: "Gravity counts as acceleration too, which is how it knows which way is down." },
        { id: "acc", label: "Accelerometer", sub: "±2 to ±16 g", kind: "sensor", col: 1, row: 0, note: "Tiny silicon masses on springs; their capacitance changes as they move." },
        { id: "gyro", label: "Gyroscope", sub: "±250 to ±2000 °/s", kind: "sensor", col: 1, row: 1, note: "Vibrating structures that twist when rotated." },
        { id: "adc", label: "16-bit ADCs", sub: "6 channels", kind: "ic", col: 2, row: 0, note: "Samples all six axes up to 1 kHz." },
        { id: "dmp", label: "DMP", sub: "motion processor", kind: "ic", col: 2, row: 1, note: "Can fuse the six readings into pitch, roll and yaw so your board doesn't have to." },
        { id: "i2c", label: "SDA / SCL", sub: "I2C 0x68", kind: "pin", col: 3, row: 0, note: "Register reads at up to 400 kHz." },
        { id: "int", label: "INT", kind: "pin", col: 3, row: 1, note: "Wakes your board when new data is ready or motion is seen." },
        { id: "vcc", label: "VCC", kind: "power", col: 0, row: 2, note: "3.3–5 V, under 4 mA." },
        { id: "reg", label: "3.3 V regulator", kind: "regulator", col: 1, row: 2, note: "Protects the chip from 5 V boards." },
      ],
      links: [
        { from: "motion", to: "acc", kind: "physical" },
        { from: "motion", to: "gyro", kind: "physical" },
        { from: "acc", to: "adc", kind: "analog" },
        { from: "gyro", to: "adc", kind: "analog" },
        { from: "adc", to: "dmp", kind: "data" },
        { from: "dmp", to: "i2c", kind: "data", both: true },
        { from: "dmp", to: "int", kind: "signal", label: "data ready" },
        { from: "vcc", to: "reg", kind: "power" },
        { from: "reg", to: "dmp", kind: "power", label: "3.3 V" },
      ],
      steps: [
        "Tiny silicon springs move with acceleration and vibrate with rotation; capacitance changes measure both on three axes.",
        "Six 16-bit ADCs sample them up to 1 kHz; the DMP can combine them into pitch and roll, and a temperature sensor rides along.",
        "You read the registers over I2C at address 0x68 (0x69 with AD0 high); INT can wake your board when new data is ready.",
        "The accelerometer gives tilt from gravity, the gyro gives rate of turn; fuse them (complementary filter or DMP) for a stable angle.",
      ],
    },
    facts: [
      { label: "Accelerometer", value: "±2 / 4 / 8 / 16 g" },
      { label: "Gyroscope", value: "±250 – 2000 °/s" },
      { label: "Interface", value: "I2C, 400 kHz" },
      { label: "Supply", value: "3.3–5 V (regulator on board)" },
      { label: "Extras", value: "Temperature, DMP, INT" },
      { label: "Size", value: "21 × 16 mm" },
    ],
    animate: { lit: ["led-pwr"] },
    experiment: { title: "Digital spirit level", idea: "Print pitch and roll from the accelerometer, then light an LED when the board is level within 2°." },
    tags: ["mpu6050", "gy-521", "imu", "accelerometer", "gyroscope", "tilt", "motion", "i2c", "sensor"],
  },

  {
    id: "bmp280",
    name: "BMP280 pressure & altitude",
    aka: ["barometer", "GY-BMP280", "BMP280 breakout"],
    group: "sensors",
    rank: 11,
    summary: "A barometer the size of a grain of rice. Air pressure to a hundredth of a hectopascal, which is enough to tell which floor of the building you're on.",
    size: { w: 11.5, h: 15.3, d: 10.1 },
    solids: [
      pcb(11.5, 15.3, MATERIAL.pcbPurple, MATERIAL.pcbPurpleEdge),
      ...maleHeader(0.2, 0.03, 6, "y", 1, false),
      { kind: "box", id: "bmp", x: 6, y: 6, w: 2, h: 2.5, d: 0.95, z: 1.6, top: "linear-gradient(135deg,#e4e7eb,#b9bdc3)", side: MATERIAL.steelSide, fill: MATERIAL.steel, radius: 0.2 },
      { kind: "disc", cx: 6.6, cy: 6.6, r: 0.25, color: "#1b1c1f", z: 2.6 },
      chip(4, 11, 2.9, 1.6, undefined, 1.1, "reg"),
      { kind: "box", x: 8.5, y: 11.5, w: 1.6, h: 0.8, d: 0.6, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      { kind: "box", x: 8.5, y: 13, w: 1.6, h: 0.8, d: 0.6, z: 1.6, top: "#b9a67a", side: "#8a7a55", radius: 0.1 },
      mountHole(9.2, 2.3, 1.3),
      silk(7.6, 4.6, "BMP280", 1, MATERIAL.silk, { anchor: "middle", weight: 700 }),
      ...["VCC", "GND", "SCL", "SDA", "CSB", "SDO"].map((name, i) => silk(3.3, 1.3 + i * 2.54 + 0.4, name, 0.8, MATERIAL.silk)),
    ],
    features: [
      { id: "bmp", label: "BMP280 (metal lid)", kind: "chip", x: 6, y: 6, w: 2, h: 2.5, note: "The barometer lives under this lid; the tiny hole lets air pressure in. Keep it clean and dry." },
      { id: "header", label: "VCC, GND, SCL, SDA, CSB, SDO", kind: "pins", x: 0.2, y: 0, w: 2.54, h: 15.24, note: "Four for I2C (VCC, GND, SCL, SDA); CSB and SDO choose SPI or set the address." },
      { id: "reg", label: "Regulator / level parts", kind: "chip", x: 4, y: 11, w: 2.9, h: 1.6, note: "Some boards regulate 5 V down to 3.3 V here; the plain purple one does not, so feed it 3.3 V." },
      { id: "hole", label: "Mounting hole", kind: "mechanical", x: 7.9, y: 1, w: 2.6, h: 2.6, note: "One M2 hole, for a screw or a zip tie." },
    ],
    pins: [
      { name: "VCC", role: "power", note: "3.3 V on this board; some variants take 5 V" },
      { name: "GND", role: "ground", note: "Ground" },
      { name: "SCL", role: "clock", note: "I2C clock (SPI SCK)" },
      { name: "SDA", role: "data", note: "I2C data (SPI MOSI)" },
      { name: "CSB", role: "other", note: "Chip select: high = I2C, low = SPI" },
      { name: "SDO", role: "other", note: "I2C address: low 0x76, high 0x77 (SPI MISO)" },
    ],
    circuit: {
      blocks: [
        { id: "air", label: "Air", sub: "pressure, temperature", kind: "world", col: 0, row: 0, note: "Pressure through the lid's hole; temperature by contact." },
        { id: "mems", label: "Pressure membrane", sub: "piezo-resistive", kind: "sensor", col: 1, row: 0, note: "A silicon membrane that flexes with pressure; resistors on it change value." },
        { id: "temp", label: "Temp sensor", kind: "sensor", col: 1, row: 1, note: "Needed to correct the pressure reading; you get it for free." },
        { id: "adc", label: "24-bit ADC", kind: "ic", col: 2, row: 0, note: "Digitises both with optional oversampling for lower noise." },
        { id: "comp", label: "Compensation", sub: "calibration in NVM", kind: "ic", col: 2, row: 1, note: "Factory constants turn raw counts into Pa and °C." },
        { id: "bus", label: "SDA / SCL", sub: "I2C 0x76, or SPI", kind: "pin", col: 3, row: 0, note: "Read the result registers; libraries do the maths." },
        { id: "vcc", label: "VCC 3.3 V", kind: "power", col: 3, row: 1, note: "Microamps: it can run for years on a coin cell." },
      ],
      links: [
        { from: "air", to: "mems", kind: "physical", label: "pressure" },
        { from: "air", to: "temp", kind: "physical", label: "heat" },
        { from: "mems", to: "adc", kind: "analog" },
        { from: "temp", to: "adc", kind: "analog" },
        { from: "adc", to: "comp", kind: "data" },
        { from: "comp", to: "bus", kind: "data", both: true },
        { from: "vcc", to: "comp", kind: "power" },
      ],
      steps: [
        "Air pressure flexes a silicon membrane; piezo-resistors on it change value. A temperature sensor sits beside it for correction.",
        "A 24-bit ADC digitises both; factory calibration constants in the chip's memory turn raw counts into Pa and °C.",
        "Read the registers over I2C (0x76, or 0x77 with SDO high) or SPI.",
        "Altitude comes from pressure: about 8.4 m per hPa near sea level, so it can tell when you lift it from the desk to your head.",
      ],
    },
    facts: [
      { label: "Pressure", value: "300–1100 hPa" },
      { label: "Precision", value: "±0.12 hPa (≈ 1 m)" },
      { label: "Temperature", value: "−40–85 °C, ±1 °C" },
      { label: "Interface", value: "I2C or SPI" },
      { label: "Supply", value: "1.7–3.6 V, 2.7 µA" },
      { label: "Size", value: "11.5 × 15 mm" },
    ],
    experiment: { title: "Staircase altimeter", idea: "Print pressure every second, convert it to altitude, then walk up a flight of stairs and watch it climb about three metres." },
    tags: ["bmp280", "barometer", "pressure", "altitude", "temperature", "weather", "i2c", "spi", "sensor"],
  },
];
